// Canonical Drive hero batchlari auditidan o'tgan, deploy-safe WebP URLlar.
// BIO-041 authoritative final varianti Batch 13 ichidan tasdiqlangan.
export const auditedHeroImageUrls: Record<string, string> = {
  "BIO-001": "/biolab-drive-assets/BIO-001-hero_local.webp",
  "BIO-002": "/biolab-drive-assets/BIO-002-hero_local.webp",
  "BIO-003": "/biolab-drive-assets/BIO-003-hero_local.webp",
  "BIO-004": "/biolab-drive-assets/BIO-004-hero_local.webp",
  "BIO-005": "/biolab-drive-assets/BIO-005-hero_local.webp",
  "BIO-006": "/biolab-drive-assets/BIO-006-hero_local.webp",
  "BIO-007": "/biolab-drive-assets/BIO-007-hero_local.webp",
  "BIO-008": "/biolab-drive-assets/BIO-008-hero_local.webp",
  "BIO-009": "/biolab-drive-assets/BIO-009-hero_local.webp",
  "BIO-010": "/biolab-drive-assets/BIO-010-hero_local.webp",
  "BIO-011": "/biolab-drive-assets/BIO-011-hero_local.webp",
  "BIO-012": "/biolab-drive-assets/BIO-012-hero_local.webp",
  "BIO-013": "/biolab-drive-assets/BIO-013-hero_local.webp",
  "BIO-014": "/biolab-drive-assets/BIO-014-hero_local.webp",
  "BIO-015": "/biolab-drive-assets/BIO-015-hero_local.webp",
  "BIO-023": "/biolab-drive-assets/BIO-023-hero_local.webp",
  "BIO-026": "/biolab-drive-assets/BIO-026-hero_local.webp",
  "BIO-030": "/biolab-drive-assets/BIO-030-hero_local.webp",
  "BIO-032": "/biolab-drive-assets/BIO-032-hero_local.webp",
  "BIO-034": "/biolab-drive-assets/BIO-034-hero_local.webp",
  "BIO-036": "/biolab-drive-assets/BIO-036-hero_local.webp",
  "BIO-037": "/biolab-drive-assets/BIO-037-hero_local.webp",
  "BIO-038": "/biolab-drive-assets/BIO-038-hero_local.webp",
  "BIO-039": "/biolab-drive-assets/BIO-039-hero_local.webp",
  "BIO-040": "/biolab-drive-assets/BIO-040-hero_local.webp",
  "BIO-041": "/biolab-drive-assets/BIO-041-hero_local.webp",
  "BIO-042": "/biolab-drive-assets/BIO-042-hero_local.webp",
  "BIO-043": "/biolab-drive-assets/BIO-043-hero_local.webp",
  "BIO-044": "/biolab-drive-assets/BIO-044-hero_local.webp",
  "BIO-045": "/biolab-drive-assets/BIO-045-hero_local.webp",
  "BIO-046": "/biolab-drive-assets/BIO-046-hero_local.webp",
  "BIO-047": "/biolab-drive-assets/BIO-047-hero_local.webp",
  "BIO-048": "/biolab-drive-assets/BIO-048-hero_local.webp",
  "BIO-049": "/biolab-drive-assets/BIO-049-hero_local.webp",
  "BIO-050": "/biolab-drive-assets/BIO-050-hero_local.webp",
  "BIO-051": "/biolab-drive-assets/BIO-051-hero_local.webp",
  "BIO-052": "/biolab-drive-assets/BIO-052-hero_local.webp",
  "BIO-053": "/biolab-drive-assets/BIO-053-hero_local.webp",
  "BIO-054": "/biolab-drive-assets/BIO-054-hero_local.webp",
  "BIO-055": "/biolab-drive-assets/BIO-055-hero_local.webp",
  "BIO-056": "/biolab-drive-assets/BIO-056-hero_local.webp",
  "BIO-057": "/biolab-drive-assets/BIO-057-hero_local.webp",
  "BIO-058": "/biolab-drive-assets/BIO-058-hero_local.webp",
  "BIO-059": "/biolab-drive-assets/BIO-059-hero_local.webp",
  "BIO-060": "/biolab-drive-assets/BIO-060-hero_local.webp",
  "BIO-061": "/biolab-drive-assets/BIO-061-hero_local.webp",
  "BIO-062": "/biolab-drive-assets/BIO-062-hero_local.webp",
  "BIO-063": "/biolab-drive-assets/BIO-063-hero_local.webp",
  "BIO-064": "/biolab-drive-assets/BIO-064-hero_local.webp",
  "BIO-065": "/biolab-drive-assets/BIO-065-hero_local.webp",
  "BIO-066": "/biolab-drive-assets/BIO-066-hero_local.webp",
  "BIO-067": "/biolab-drive-assets/BIO-067-hero_local.webp",
  "BIO-068": "/biolab-drive-assets/BIO-068-hero_local.webp",
  "BIO-069": "/biolab-drive-assets/BIO-069-hero_local.webp",
  "BIO-070": "/biolab-drive-assets/BIO-070-hero_local.webp",
  "BIO-071": "/biolab-drive-assets/BIO-071-hero_local.webp",
  "BIO-072": "/biolab-drive-assets/BIO-072-hero_local.webp",
  "BIO-073": "/biolab-drive-assets/BIO-073-hero_local.webp",
  "BIO-074": "/biolab-drive-assets/BIO-074-hero_local.webp",
  "BIO-075": "/biolab-drive-assets/BIO-075-hero_local.webp",
  "BIO-076": "/biolab-drive-assets/BIO-076-hero_local.webp",
  "BIO-077": "/biolab-drive-assets/BIO-077-hero_local.webp",
  "BIO-078": "/biolab-drive-assets/BIO-078-hero_local.webp",
  "BIO-079": "/biolab-drive-assets/BIO-079-hero_local.webp",
  "BIO-080": "/biolab-drive-assets/BIO-080-hero_local.webp",
  "BIO-081": "/biolab-drive-assets/BIO-081-hero_local.webp",
  "BIO-082": "/biolab-drive-assets/BIO-082-hero_local.webp",
  "BIO-083": "/biolab-drive-assets/BIO-083-hero_local.webp",
  "BIO-084": "/biolab-drive-assets/BIO-084-hero_local.webp",
  "BIO-085": "/biolab-drive-assets/BIO-085-hero_local.webp",
  "BIO-086": "/biolab-drive-assets/BIO-086-hero_local.webp",
  "BIO-087": "/biolab-drive-assets/BIO-087-hero_local.webp",
  "BIO-088": "/biolab-drive-assets/BIO-088-hero_local.webp",
  "BIO-089": "/biolab-drive-assets/BIO-089-hero_local.webp",
  "BIO-090": "/biolab-drive-assets/BIO-090-hero_local.webp",
  "BIO-091": "/biolab-drive-assets/BIO-091-hero_local.webp",
  "BIO-092": "/biolab-drive-assets/BIO-092-hero_local.webp",
  "BIO-093": "/biolab-drive-assets/BIO-093-hero_local.webp",
  "BIO-094": "/biolab-drive-assets/BIO-094-hero_local.webp",
  "BIO-095": "/biolab-drive-assets/BIO-095-hero_local.webp",
  "BIO-096": "/biolab-drive-assets/BIO-096-hero_local.webp",
  "BIO-097": "/biolab-drive-assets/BIO-097-hero_local.webp",
  "BIO-098": "/biolab-drive-assets/BIO-098-hero_local.webp",
  "BIO-099": "/biolab-drive-assets/BIO-099-hero_local.webp",
  "BIO-100": "/biolab-drive-assets/BIO-100-hero_local.webp",
};

// Batch topshirig'ida yangi fayli yo'q, ammo avvalgi auditdan o'tgan hero versiyasi
// saqlanadigan qurilmalar.
export const legacyAcceptedHeroIds = [
  "BIO-016", "BIO-017", "BIO-018", "BIO-019", "BIO-020", "BIO-021", "BIO-022",
  "BIO-024", "BIO-025", "BIO-027", "BIO-028", "BIO-029", "BIO-031", "BIO-033", "BIO-035",
] as const;
