// BioLab Interactive Guide — extracted from BIOTECH100YAGONABAZA.md.
// Data policy: preserve source values; no fabricated technical specifications.
export type Equipment = {
  id: string; number: number; name: string; category: string; model: string;
  description: string; purpose: string; newPrice: string; brands: string; models: string;
  hiddenCosts: string; purchasingStrategy: string; slug: string;
};

export const categories = [
  'Barcha uskunalar', 'Molekulyar biologiya', 'Mikroskopiya', 'Hujayra kulturalari',
  'Mikrobiologiya', 'Analitika', 'Sentrifugatsiya', 'Bioreaktorlar',
  'Sovutish va saqlash', 'Namuna tayyorlash', 'Avtomatlashtirish'
] as const;

export const equipment: Equipment[] = [
  {
    "id": "BIO-001",
    "number": 1,
    "name": "PCR (Polimeraz zanjir reaksiyasi) mashina",
    "category": "Molekulyar biologiya",
    "model": "Bio-Rad CFX96 Touch Real-Time PCR",
    "description": "DNK va RNK fragmentlarini ko'paytirish (amplifikatsiya) uchun.",
    "purpose": "Genetik diagnostika, klonlash, gen ekspressiyasini aniqlash",
    "newPrice": "$3,000–30,000",
    "brands": "Thermo Fisher Scientific / Bio-Rad / Eppendorf",
    "models": "Applied Biosystems Veriti / Bio-Rad T100 / Eppendorf Mastercycler",
    "hiddenCosts": "PCR plates/tubes, optical seals, calibration, reagents, software va servis.",
    "purchasingStrategy": "Darhol sotib olishdan oldin utilization/ROI hisoblang; ko‘pincha core facility, servis yoki contract lab orqali boshlash oqilona.",
    "slug": "pcr-polimeraz-zanjir-reaksiyasi-mashina"
  },
  {
    "id": "BIO-002",
    "number": 2,
    "name": "Avtoklav (Bug'li sterilizator)",
    "category": "Mikrobiologiya",
    "model": "Tuttnauer 2540MK",
    "description": "Yuqori bosim va bug' yordamida asbob-uskunalar va muhitlarni sterilizatsiya qiladi.",
    "purpose": "Laboratoriya asboblarini, ozuqa muhitlarini steril holga keltirish",
    "newPrice": "$2,000–30,000",
    "brands": "Tuttnauer / Systec / Getinge",
    "models": "Labclave / VX / sterilizers",
    "hiddenCosts": "Consumables, calibration, maintenance, spare parts, electricity va operator training.",
    "purchasingStrategy": "Darhol sotib olishdan oldin utilization/ROI hisoblang; ko‘pincha core facility, servis yoki contract lab orqali boshlash oqilona.",
    "slug": "avtoklav-bug-li-sterilizator"
  },
  {
    "id": "BIO-003",
    "number": 3,
    "name": "Laminar oqim shkaflari (BSC)",
    "category": "Hujayra kulturalari",
    "model": "Thermo Scientific MSC-Advantage Class II",
    "description": "Steril ish muhitini ta'minlovchi vertikal havo oqimli shkaf.",
    "purpose": "Mikrobiologik va hujayra kulturasi ishlari uchun kontaminatsiyadan himoya",
    "newPrice": "$5,000–25,000",
    "brands": "ESCO / Thermo Fisher / NuAire",
    "models": "Airstream / Heraguard / LabGard",
    "hiddenCosts": "Consumables, calibration, maintenance, spare parts, electricity va operator training.",
    "purchasingStrategy": "Darhol sotib olishdan oldin utilization/ROI hisoblang; ko‘pincha core facility, servis yoki contract lab orqali boshlash oqilona.",
    "slug": "laminar-oqim-shkaflari-bsc"
  },
  {
    "id": "BIO-004",
    "number": 4,
    "name": "Sentrifuga",
    "category": "Sentrifugatsiya",
    "model": "Eppendorf Centrifuge 5430 R",
    "description": "Qo'shimchali sovutish tizimiga ega, yuqori tezlikli aylanma qurilma.",
    "purpose": "Hujayra, DNK, oqsil ajratish, namunalarni fraksiyalash",
    "newPrice": "$5,000–25,000",
    "brands": "Eppendorf / Thermo Fisher / Hettich",
    "models": "5910 Ri / Sorvall / Rotanta",
    "hiddenCosts": "Rotorlar, buckets, adapters, maintenance, calibration va rotor certification.",
    "purchasingStrategy": "Darhol sotib olishdan oldin utilization/ROI hisoblang; ko‘pincha core facility, servis yoki contract lab orqali boshlash oqilona.",
    "slug": "sentrifuga"
  },
  {
    "id": "BIO-005",
    "number": 5,
    "name": "Spektrofotometr",
    "category": "Analitika",
    "model": "Thermo NanoDrop One",
    "description": "Nur yutilishini o'lchovchi optik qurilma.",
    "purpose": "DNK, RNK, oqsil konsentratsiyasini aniqlash",
    "newPrice": "$2,000–20,000",
    "brands": "Agilent / Shimadzu / Thermo Fisher",
    "models": "Cary / UV-1900i / Evolution",
    "hiddenCosts": "Consumables, calibration, maintenance, spare parts, electricity va operator training.",
    "purchasingStrategy": "Darhol sotib olishdan oldin utilization/ROI hisoblang; ko‘pincha core facility, servis yoki contract lab orqali boshlash oqilona.",
    "slug": "spektrofotometr"
  },
  {
    "id": "BIO-006",
    "number": 6,
    "name": "Gaz xromatografi (GC)",
    "category": "Analitika",
    "model": "Agilent 8890 GC System",
    "description": "Gaz fazasidagi moddalarni ajratib tahlil qiluvchi qurilma.",
    "purpose": "Uchar organik birikmalar, qoldiq pestitsidlar, yog' kislotalarini aniqlash",
    "newPrice": "$20,000–80,000",
    "brands": "Agilent / Shimadzu / Thermo Fisher",
    "models": "8890 / Nexis / TRACE",
    "hiddenCosts": "Columns, solvents, gases, source/ion optics maintenance, calibration va service contract.",
    "purchasingStrategy": "Darhol sotib olishdan oldin utilization/ROI hisoblang; ko‘pincha core facility, servis yoki contract lab orqali boshlash oqilona.",
    "slug": "gaz-xromatografi-gc"
  },
  {
    "id": "BIO-007",
    "number": 7,
    "name": "Suyuq xromatografi (HPLC)",
    "category": "Analitika",
    "model": "Shimadzu Nexera X3",
    "description": "Yuqori bosimli suyuqlik xromatografiyasi qurilmasi.",
    "purpose": "Vitaminlar, antioksidantlar, konservantlar miqdorini aniqlash",
    "newPrice": "$20,000–100,000",
    "brands": "Agilent / Waters / Shimadzu",
    "models": "1260 Infinity / Alliance / Nexera",
    "hiddenCosts": "Columns, solvents, gases, source/ion optics maintenance, calibration va service contract.",
    "purchasingStrategy": "Darhol sotib olishdan oldin utilization/ROI hisoblang; ko‘pincha core facility, servis yoki contract lab orqali boshlash oqilona.",
    "slug": "suyuq-xromatografi-hplc"
  },
  {
    "id": "BIO-008",
    "number": 8,
    "name": "Massa-spektrometr (LC-MS/MS)",
    "category": "Analitika",
    "model": "Waters ACQUITY UPLC I-Class / Xevo TQ-S",
    "description": "LC bilan birlashgan uch kvadrupol massa-spektrometr.",
    "purpose": "Toksinlar, dori qoldiqlari, pestitsidlarni ultraizsiz aniqlash",
    "newPrice": "$200,000–700,000+",
    "brands": "SCIEX / Waters / Thermo Fisher",
    "models": "Triple Quad / Xevo TQ / TSQ",
    "hiddenCosts": "Columns, solvents, gases, source/ion optics maintenance, calibration va service contract.",
    "purchasingStrategy": "Darhol sotib olishdan oldin utilization/ROI hisoblang; ko‘pincha core facility, servis yoki contract lab orqali boshlash oqilona.",
    "slug": "massa-spektrometr-lc-ms-ms"
  },
  {
    "id": "BIO-009",
    "number": 9,
    "name": "Elektroforez tizimi (gel)",
    "category": "Molekulyar biologiya",
    "model": "Bio-Rad PowerPac Universal",
    "description": "Agaroz yoki PAAG gelida biomolekulalarni ajratadi.",
    "purpose": "DNK/RNK/oqsil fraksiyalarini ko'rish va aniqlash",
    "newPrice": "$300–3,000",
    "brands": "Bio-Rad / Thermo Fisher / Cleaver Scientific",
    "models": "Mini-Sub Cell GT / Owl / omniPAGE",
    "hiddenCosts": "Consumables, calibration, maintenance, spare parts, electricity va operator training.",
    "purchasingStrategy": "Darhol sotib olishdan oldin utilization/ROI hisoblang; ko‘pincha core facility, servis yoki contract lab orqali boshlash oqilona.",
    "slug": "elektroforez-tizimi-gel"
  },
  {
    "id": "BIO-010",
    "number": 10,
    "name": "Western blot tizimi",
    "category": "Analitika",
    "model": "Bio-Rad ChemiDoc MP Imaging System",
    "description": "Oqsillarni antikor yordamida aniqlash va vizualizatsiya qiladi.",
    "purpose": "Maqsadli oqsilni sifat va miqdoriy tahlil qilish",
    "newPrice": "$2,000–20,000",
    "brands": "Bio-Rad / Thermo Fisher",
    "models": "Mini Trans-Blot / iBlot",
    "hiddenCosts": "Consumables, calibration, maintenance, spare parts, electricity va operator training.",
    "purchasingStrategy": "Darhol sotib olishdan oldin utilization/ROI hisoblang; ko‘pincha core facility, servis yoki contract lab orqali boshlash oqilona.",
    "slug": "western-blot-tizimi"
  },
  {
    "id": "BIO-011",
    "number": 11,
    "name": "ELISA o'quvchi (Mikroplanshet fotometr)",
    "category": "Analitika",
    "model": "BioTek Synergy HTX",
    "description": "96- yoki 384-quduqli planshetlarda optik zichlikni o'lchaydi.",
    "purpose": "Immunoferment tahlil (ELISA), ferment faolligini o'lchash",
    "newPrice": "$3,000–15,000",
    "brands": "BioTek / Thermo Fisher / Mindray",
    "models": "ELx808 / Multiskan",
    "hiddenCosts": "Consumables, calibration, maintenance, spare parts, electricity va operator training.",
    "purchasingStrategy": "Darhol sotib olishdan oldin utilization/ROI hisoblang; ko‘pincha core facility, servis yoki contract lab orqali boshlash oqilona.",
    "slug": "elisa-o-quvchi-mikroplanshet-fotometr"
  },
  {
    "id": "BIO-012",
    "number": 12,
    "name": "Lyuminometr",
    "category": "Analitika",
    "model": "Berthold Centro XS3 LB 960",
    "description": "Bioluminessensiya va kimyoluminessensiya signalini o'lchaydi.",
    "purpose": "ATP bioluminessensiyasi, gen ekspressiyasi tahlili",
    "newPrice": "$10,000–80,000",
    "brands": "Bio-Rad / Azure / Cytiva",
    "models": "ChemiDoc / Sapphire / Amersham",
    "hiddenCosts": "Consumables, calibration, maintenance, spare parts, electricity va operator training.",
    "purchasingStrategy": "Darhol sotib olishdan oldin utilization/ROI hisoblang; ko‘pincha core facility, servis yoki contract lab orqali boshlash oqilona.",
    "slug": "lyuminometr"
  },
  {
    "id": "BIO-013",
    "number": 13,
    "name": "Flotsitometr (Flow cytometer)",
    "category": "Mikroskopiya",
    "model": "BD FACSLyric",
    "description": "Individual hujayralarni lazer nurida tahlil qiladi.",
    "purpose": "Hujayra saralash, immunofenotiplash, apoptoz tahlili",
    "newPrice": "$20,000–100,000",
    "brands": "Thermo Fisher / Bio-Rad / Nexcelom",
    "models": "EVOS / ZE5 / Cellometer",
    "hiddenCosts": "Objectives, filters/lasers, camera, software license, calibration va servis.",
    "purchasingStrategy": "Darhol sotib olishdan oldin utilization/ROI hisoblang; ko‘pincha core facility, servis yoki contract lab orqali boshlash oqilona.",
    "slug": "flotsitometr-flow-cytometer"
  },
  {
    "id": "BIO-014",
    "number": 14,
    "name": "Konfokalli mikroskop",
    "category": "Mikroskopiya",
    "model": "Zeiss LSM 980",
    "description": "Lazer skanerli optik kesimlar yaratuvchi mikroskop.",
    "purpose": "Hujayra ichki tuzilishini 3D tasvirda ko'rish",
    "newPrice": "$100,000–500,000+",
    "brands": "Leica / ZEISS / Olympus",
    "models": "STELLARIS / LSM / FV series",
    "hiddenCosts": "Objectives, filters/lasers, camera, software license, calibration va servis.",
    "purchasingStrategy": "Darhol sotib olishdan oldin utilization/ROI hisoblang; ko‘pincha core facility, servis yoki contract lab orqali boshlash oqilona.",
    "slug": "konfokalli-mikroskop"
  },
  {
    "id": "BIO-015",
    "number": 15,
    "name": "Teskari faza mikroskopi",
    "category": "Mikroskopiya",
    "model": "Olympus CKX53",
    "description": "Ob'ektiv pastdan, yorug'lik yuqoridan tushadigan mikroskop.",
    "purpose": "Hujayra kulturalari holati va o'sishini kuzatish",
    "newPrice": "$3,000–30,000",
    "brands": "Leica / ZEISS / Olympus / Nikon",
    "models": "DMi1 / Primovert / CKX53 / Ts2",
    "hiddenCosts": "Objectives, filters/lasers, camera, software license, calibration va servis.",
    "purchasingStrategy": "Darhol sotib olishdan oldin utilization/ROI hisoblang; ko‘pincha core facility, servis yoki contract lab orqali boshlash oqilona.",
    "slug": "teskari-faza-mikroskopi"
  },
  {
    "id": "BIO-016",
    "number": 16,
    "name": "CO2 inkubator",
    "category": "Hujayra kulturalari",
    "model": "Thermo Scientific Heracell VIOS 160i",
    "description": "Nazorat qilinadigan CO2, harorat va namlik sharoiti yaratadi.",
    "purpose": "Hujayra va to'qima kulturalarini o'stirish",
    "newPrice": "$5,000–30,000",
    "brands": "Thermo Fisher / Eppendorf / PHCbi",
    "models": "Heracell / CellXpert / MCO",
    "hiddenCosts": "Consumables, calibration, maintenance, spare parts, electricity va operator training.",
    "purchasingStrategy": "Darhol sotib olishdan oldin utilization/ROI hisoblang; ko‘pincha core facility, servis yoki contract lab orqali boshlash oqilona.",
    "slug": "co2-inkubator"
  },
  {
    "id": "BIO-017",
    "number": 17,
    "name": "Muzlatgich (ULT, -80°C)",
    "category": "Sovutish va saqlash",
    "model": "Thermo Scientific TSX Series -86°C",
    "description": "Ultra past haroratda biologik namunalarni saqlaydi.",
    "purpose": "Hujayra liniyalari, fermentlar, plazmidalar, qon namunalarini saqlash",
    "newPrice": "$8,000–25,000",
    "brands": "Thermo Fisher / PHCbi / Eppendorf",
    "models": "ULTS / MDF / CryoCube",
    "hiddenCosts": "Elektr energiyasi, alarms, monitoring, backup power, compressor service va temperature mapping.",
    "purchasingStrategy": "Darhol sotib olishdan oldin utilization/ROI hisoblang; ko‘pincha core facility, servis yoki contract lab orqali boshlash oqilona.",
    "slug": "muzlatgich-ult-80-c"
  },
  {
    "id": "BIO-018",
    "number": 18,
    "name": "Liyofilizator (Freeze dryer)",
    "category": "Analitika",
    "model": "Christ Alpha 1-2 LDplus",
    "description": "Sovitib quritish orqali suvni sublimatsiya qiladi.",
    "purpose": "Oqsillar, vaksinalar, biologik preparatlar barqarorligini saqlash",
    "newPrice": "$5,000–150,000+",
    "brands": "Labconco / SP Scientific / Martin Christ",
    "models": "FreeZone / LyoStar / Alpha",
    "hiddenCosts": "Consumables, calibration, maintenance, spare parts, electricity va operator training.",
    "purchasingStrategy": "Darhol sotib olishdan oldin utilization/ROI hisoblang; ko‘pincha core facility, servis yoki contract lab orqali boshlash oqilona.",
    "slug": "liyofilizator-freeze-dryer"
  },
  {
    "id": "BIO-019",
    "number": 19,
    "name": "Homogenizator (ultratovush)",
    "category": "Molekulyar biologiya",
    "model": "Branson SFX550 Sonifier",
    "description": "Ultratovush to'lqinlari bilan hujayra pardalarini parchalaydi.",
    "purpose": "Hujayra lizisi, DNK/oqsil ekstraksiyasi",
    "newPrice": "$2,000–30,000",
    "brands": "Qsonica / Hielscher / Sonics",
    "models": "Q700 / UP series / VCX",
    "hiddenCosts": "Consumables, calibration, maintenance, spare parts, electricity va operator training.",
    "purchasingStrategy": "Darhol sotib olishdan oldin utilization/ROI hisoblang; ko‘pincha core facility, servis yoki contract lab orqali boshlash oqilona.",
    "slug": "homogenizator-ultratovush"
  },
  {
    "id": "BIO-020",
    "number": 20,
    "name": "Magnit aralashtirgich (qizdiruvchi plita)",
    "category": "Analitika",
    "model": "IKA C-MAG HS 7 digital",
    "description": "Magnit maydon yordamida suyuqlikni aralashtirib qizdiradi.",
    "purpose": "Reagentlar tayyorlash, eritmalar tayyorlash",
    "newPrice": "$150–1,500",
    "brands": "IKA / Corning / Thermo Scientific",
    "models": "IKA C-MAG HS 7 digital / Corning PC-420D / Thermo Cimarec+",
    "hiddenCosts": "Sarf materiallari, kalibrlash, servis kontrakti, dasturiy ta'minot litsenziyasi va operator o'qitish xarajatlari.",
    "purchasingStrategy": "Sotib olishdan oldin utilization/ROI hisoblang; ko'pincha core facility, servis yoki contract lab orqali boshlash oqilona.",
    "slug": "magnit-aralashtirgich-qizdiruvchi-plita"
  },
  {
    "id": "BIO-021",
    "number": 21,
    "name": "pH-metr",
    "category": "Analitika",
    "model": "Mettler Toledo Seven Excellence S470",
    "description": "Eritmalar vodorod ionlari konsentratsiyasini aniq o'lchaydi.",
    "purpose": "Buferlar, ozuqa muhitlari, namunalar pH ini nazorat qilish",
    "newPrice": "$300–2,500",
    "brands": "Mettler Toledo / Hanna Instruments / Thermo Fisher",
    "models": "Mettler Toledo Seven Excellence S470 / Hanna HI5222 / Thermo Orion Star A215",
    "hiddenCosts": "Sarf materiallari, kalibrlash, servis kontrakti, dasturiy ta'minot litsenziyasi va operator o'qitish xarajatlari.",
    "purchasingStrategy": "Sotib olishdan oldin utilization/ROI hisoblang; ko'pincha core facility, servis yoki contract lab orqali boshlash oqilona.",
    "slug": "ph-metr"
  },
  {
    "id": "BIO-022",
    "number": 22,
    "name": "Analitik tarozilar",
    "category": "Analitika",
    "model": "Sartorius Entris II BCE64i-1S",
    "description": "0,0001 g aniqlikdagi elektron tarozilar.",
    "purpose": "Reagent, namuna va ozuqa muhitlari og'irligini o'lchash",
    "newPrice": "$1,000–6,000",
    "brands": "Sartorius / Mettler Toledo / OHAUS",
    "models": "Sartorius Entris II BCE64i-1S / Mettler Toledo XPR / OHAUS Explorer",
    "hiddenCosts": "Sarf materiallari, kalibrlash, servis kontrakti, dasturiy ta'minot litsenziyasi va operator o'qitish xarajatlari.",
    "purchasingStrategy": "Sotib olishdan oldin utilization/ROI hisoblang; ko'pincha core facility, servis yoki contract lab orqali boshlash oqilona.",
    "slug": "analitik-tarozilar"
  },
  {
    "id": "BIO-023",
    "number": 23,
    "name": "Termostat (Issiq kamera)",
    "category": "Mikrobiologiya",
    "model": "Memmert IN260",
    "description": "Aniq harorat rejimini ushlab turuvchi kamera.",
    "purpose": "Mikrobiologik o'stirish, fermentatsiya, laboratoriya testlari",
    "newPrice": "$1,000–10,000",
    "brands": "Binder / Memmert / Thermo Fisher",
    "models": "ED / UN / ovens",
    "hiddenCosts": "Consumables, calibration, maintenance, spare parts, electricity va operator training.",
    "purchasingStrategy": "Darhol sotib olishdan oldin utilization/ROI hisoblang; ko‘pincha core facility, servis yoki contract lab orqali boshlash oqilona.",
    "slug": "termostat-issiq-kamera"
  },
  {
    "id": "BIO-024",
    "number": 24,
    "name": "Suyuq azot idishi (Devar idishi)",
    "category": "Sovutish va saqlash",
    "model": "Taylor-Wharton CP Series CP34",
    "description": "Kriogenikdagi (-196°C) biologik namunalarni saqlaydi.",
    "purpose": "Hujayra liniyalari va spermalarni uzoq muddatli saqlash",
    "newPrice": "$2,000–20,000",
    "brands": "Thermo Fisher / Worthington / MVE",
    "models": "CryoPlus / MVE",
    "hiddenCosts": "Consumables, calibration, maintenance, spare parts, electricity va operator training.",
    "purchasingStrategy": "Darhol sotib olishdan oldin utilization/ROI hisoblang; ko‘pincha core facility, servis yoki contract lab orqali boshlash oqilona.",
    "slug": "suyuq-azot-idishi-devar-idishi"
  },
  {
    "id": "BIO-025",
    "number": 25,
    "name": "Mikrosentrifuga",
    "category": "Sentrifugatsiya",
    "model": "Eppendorf MiniSpin plus",
    "description": "Kichik hacmdagi ependorf trubkalar uchun kompakt sentrifuga.",
    "purpose": "Tez fraktsiyalash, PCR tayyorlov, oqsil cho'ktirish",
    "newPrice": "$1,000–10,000",
    "brands": "Eppendorf / Thermo Fisher / Hettich",
    "models": "5424 R / Sorvall Micro / Mikro",
    "hiddenCosts": "Consumables, calibration, maintenance, spare parts, electricity va operator training.",
    "purchasingStrategy": "Darhol sotib olishdan oldin utilization/ROI hisoblang; ko‘pincha core facility, servis yoki contract lab orqali boshlash oqilona.",
    "slug": "mikrosentrifuga"
  },
  {
    "id": "BIO-026",
    "number": 26,
    "name": "Vorteks aralashtiruvchi",
    "category": "Namuna tayyorlash",
    "model": "Scientific Industries Vortex Genie 2",
    "description": "Orbital tebranish orqali tez aralashtirishni ta'minlaydi.",
    "purpose": "Namuna homogenizatsiyasi, reagentlar aralashtirish",
    "newPrice": "$150–800",
    "brands": "Scientific Industries / IKA / Corning",
    "models": "Scientific Industries Vortex Genie 2 / IKA MS 3 basic / Corning LSE",
    "hiddenCosts": "Sarf materiallari, kalibrlash, servis kontrakti, dasturiy ta'minot litsenziyasi va operator o'qitish xarajatlari.",
    "purchasingStrategy": "Sotib olishdan oldin utilization/ROI hisoblang; ko'pincha core facility, servis yoki contract lab orqali boshlash oqilona.",
    "slug": "vorteks-aralashtiruvchi"
  },
  {
    "id": "BIO-027",
    "number": 27,
    "name": "Dispenserli avtomatik pipetka",
    "category": "Avtomatlashtirish",
    "model": "Eppendorf Repeater M4",
    "description": "Ko'p marta dispenserlash uchun mo'ljallangan mexanik pipetka.",
    "purpose": "Planshetlarni to'ldirish, seriyali dispenserlash",
    "newPrice": "$400–1,200",
    "brands": "Eppendorf / BrandTech / Gilson",
    "models": "Eppendorf Repeater M4 / BrandTech HandyStep touch / Gilson Microman",
    "hiddenCosts": "Sarf materiallari, kalibrlash, servis kontrakti, dasturiy ta'minot litsenziyasi va operator o'qitish xarajatlari.",
    "purchasingStrategy": "Sotib olishdan oldin utilization/ROI hisoblang; ko'pincha core facility, servis yoki contract lab orqali boshlash oqilona.",
    "slug": "dispenserli-avtomatik-pipetka"
  },
  {
    "id": "BIO-028",
    "number": 28,
    "name": "Multikanalli pipetka",
    "category": "Namuna tayyorlash",
    "model": "Sartorius Picus2 8-kanal 300 µL",
    "description": "8 yoki 12 kanalga bir vaqtda suyuqlik uzatadi.",
    "purpose": "ELISA va PCR planshetlarini tez to'ldirish",
    "newPrice": "$500–2,500",
    "brands": "Sartorius / Eppendorf / Rainin",
    "models": "Sartorius Picus2 8-kanal / Eppendorf Xplorer plus / Rainin Pipet-Lite XLS+",
    "hiddenCosts": "Sarf materiallari, kalibrlash, servis kontrakti, dasturiy ta'minot litsenziyasi va operator o'qitish xarajatlari.",
    "purchasingStrategy": "Sotib olishdan oldin utilization/ROI hisoblang; ko'pincha core facility, servis yoki contract lab orqali boshlash oqilona.",
    "slug": "multikanalli-pipetka"
  },
  {
    "id": "BIO-029",
    "number": 29,
    "name": "Termotsikler (qo'lda PCR)",
    "category": "Molekulyar biologiya",
    "model": "Applied Biosystems Veriti 96",
    "description": "Harorat sikllarini nazorat qilib PCR amalga oshiradi.",
    "purpose": "End-point PCR amplifikatsiyasi",
    "newPrice": "$3,000–30,000",
    "brands": "Thermo Fisher Scientific / Bio-Rad / Eppendorf",
    "models": "Applied Biosystems Veriti / Bio-Rad T100 / Eppendorf Mastercycler",
    "hiddenCosts": "PCR plates/tubes, optical seals, calibration, reagents, software va servis.",
    "purchasingStrategy": "Darhol sotib olishdan oldin utilization/ROI hisoblang; ko‘pincha core facility, servis yoki contract lab orqali boshlash oqilona.",
    "slug": "termotsikler-qo-lda-pcr"
  },
  {
    "id": "BIO-030",
    "number": 30,
    "name": "Real-time PCR (qPCR) qurilmasi",
    "category": "Molekulyar biologiya",
    "model": "Roche LightCycler 480 II",
    "description": "Flyuorессentlik yordamida real vaqt rejimida DNK miqdorini o'lchaydi.",
    "purpose": "Gen ekspressiyasi, patogen aniqlash, miqdoriy tahlil",
    "newPrice": "$15,000–150,000",
    "brands": "Thermo Fisher Scientific / Bio-Rad / Roche",
    "models": "QuantStudio 5 / CFX96 Touch / LightCycler 96",
    "hiddenCosts": "PCR plates/tubes, optical seals, calibration, reagents, software va servis.",
    "purchasingStrategy": "Darhol sotib olishdan oldin utilization/ROI hisoblang; ko‘pincha core facility, servis yoki contract lab orqali boshlash oqilona.",
    "slug": "real-time-pcr-qpcr-qurilmasi"
  },
  {
    "id": "BIO-031",
    "number": 31,
    "name": "Kapillyar elektroforez",
    "category": "Molekulyar biologiya",
    "model": "Agilent 2100 Bioanalyzer",
    "description": "Kapillyarda yuqori aniqlikda biomolekulalarni ajratadi.",
    "purpose": "DNK/RNK sifati va miqdori, oqsil xarakteristikasi",
    "newPrice": "$20,000–45,000",
    "brands": "Agilent",
    "models": "Agilent 2100 Bioanalyzer / Agilent 4200 TapeStation (alternativ)",
    "hiddenCosts": "Sarf materiallari, kalibrlash, servis kontrakti, dasturiy ta'minot litsenziyasi va operator o'qitish xarajatlari.",
    "purchasingStrategy": "Sotib olishdan oldin utilization/ROI hisoblang; ko'pincha core facility, servis yoki contract lab orqali boshlash oqilona.",
    "slug": "kapillyar-elektroforez"
  },
  {
    "id": "BIO-032",
    "number": 32,
    "name": "Sekvenator (DNA Sequencer)",
    "category": "Molekulyar biologiya",
    "model": "Illumina MiSeq",
    "description": "Keyingi avlod sekvensiya texnologiyasi (NGS).",
    "purpose": "Genomik, transkriptomik tadqiqotlar, SNP tahlili",
    "newPrice": "$20,000–100,000",
    "brands": "Agilent / Bio-Rad",
    "models": "Fragment Analyzer 5200 / Experion",
    "hiddenCosts": "Consumables, calibration, maintenance, spare parts, electricity va operator training.",
    "purchasingStrategy": "Darhol sotib olishdan oldin utilization/ROI hisoblang; ko‘pincha core facility, servis yoki contract lab orqali boshlash oqilona.",
    "slug": "sekvenator-dna-sequencer"
  },
  {
    "id": "BIO-033",
    "number": 33,
    "name": "Xemiluminessent tahlilchi",
    "category": "Analitika",
    "model": "Roche Cobas e 801",
    "description": "Elektrokemiluminessent immunoanaliz qurilmasi.",
    "purpose": "Gormonlar, onkomarkerlar, infeksion kasallik markerlarini aniqlash",
    "newPrice": "$10,000–80,000",
    "brands": "Bio-Rad / Azure / Cytiva",
    "models": "ChemiDoc / Sapphire / Amersham",
    "hiddenCosts": "Consumables, calibration, maintenance, spare parts, electricity va operator training.",
    "purchasingStrategy": "Darhol sotib olishdan oldin utilization/ROI hisoblang; ko‘pincha core facility, servis yoki contract lab orqali boshlash oqilona.",
    "slug": "xemiluminessent-tahlilchi"
  },
  {
    "id": "BIO-034",
    "number": 34,
    "name": "Atom-absorbsion spektrometr (AAS)",
    "category": "Analitika",
    "model": "PerkinElmer PinAAcle 900T",
    "description": "Atomlarning nur yutilishini o'lchaydi.",
    "purpose": "Og'ir metallar (Pb, Cd, As, Hg) miqdorini aniqlash",
    "newPrice": "$20,000–50,000",
    "brands": "PerkinElmer / Agilent / Shimadzu",
    "models": "PerkinElmer PinAAcle 900T / Agilent 240FS AA / Shimadzu AA-7000",
    "hiddenCosts": "Sarf materiallari, kalibrlash, servis kontrakti, dasturiy ta'minot litsenziyasi va operator o'qitish xarajatlari.",
    "purchasingStrategy": "Sotib olishdan oldin utilization/ROI hisoblang; ko'pincha core facility, servis yoki contract lab orqali boshlash oqilona.",
    "slug": "atom-absorbsion-spektrometr-aas"
  },
  {
    "id": "BIO-035",
    "number": 35,
    "name": "ICP-MS (Induksion plazma spektrometr)",
    "category": "Analitika",
    "model": "Agilent 7900 ICP-MS",
    "description": "Plazma ionizatsiyasi va massa spektrometriyasini birlashtiradi.",
    "purpose": "Eser elementlar va og'ir metallarni ultra-sezgirlik bilan aniqlash",
    "newPrice": "$80,000–250,000",
    "brands": "Agilent / Thermo Fisher / PerkinElmer",
    "models": "Agilent 7900 ICP-MS / Thermo iCAP RQ / PerkinElmer NexION",
    "hiddenCosts": "Sarf materiallari, kalibrlash, servis kontrakti, dasturiy ta'minot litsenziyasi va operator o'qitish xarajatlari.",
    "purchasingStrategy": "Sotib olishdan oldin utilization/ROI hisoblang; ko'pincha core facility, servis yoki contract lab orqali boshlash oqilona.",
    "slug": "icp-ms-induksion-plazma-spektrometr"
  },
  {
    "id": "BIO-036",
    "number": 36,
    "name": "Titrator (Karl Fischer)",
    "category": "Analitika",
    "model": "Mettler Toledo V30S",
    "description": "Karl Fischer reaksiyasi asosida namlik aniqlanadi.",
    "purpose": "Oziq-ovqat va farmatsevtik mahsulotlardagi namlик miqdori",
    "newPrice": "$5,000–15,000",
    "brands": "Mettler Toledo / Metrohm",
    "models": "Mettler Toledo V30S / Metrohm 899 Coulometer",
    "hiddenCosts": "Sarf materiallari, kalibrlash, servis kontrakti, dasturiy ta'minot litsenziyasi va operator o'qitish xarajatlari.",
    "purchasingStrategy": "Sotib olishdan oldin utilization/ROI hisoblang; ko'pincha core facility, servis yoki contract lab orqali boshlash oqilona.",
    "slug": "titrator-karl-fischer"
  },
  {
    "id": "BIO-037",
    "number": 37,
    "name": "Viskozimetr",
    "category": "Analitika",
    "model": "Brookfield DV2T",
    "description": "Suyuqlik qovushqoqligini o'lchaydi.",
    "purpose": "Bijg'itilgan sut, moy, souslar va eritmalar xarakteristikasi",
    "newPrice": "$3,000–10,000",
    "brands": "Brookfield (AMETEK) / Anton Paar",
    "models": "Brookfield DV2T / Anton Paar Lovis 2000 ME",
    "hiddenCosts": "Sarf materiallari, kalibrlash, servis kontrakti, dasturiy ta'minot litsenziyasi va operator o'qitish xarajatlari.",
    "purchasingStrategy": "Sotib olishdan oldin utilization/ROI hisoblang; ko'pincha core facility, servis yoki contract lab orqali boshlash oqilona.",
    "slug": "viskozimetr"
  },
  {
    "id": "BIO-038",
    "number": 38,
    "name": "Refraktometr (raqamli)",
    "category": "Analitika",
    "model": "MISCO Palm Abbe Digital",
    "description": "Nur sinish indeksini o'lchab Brix yoki konsentratsiyani topadi.",
    "purpose": "Qand, spirt, tuz konsentratsiyasini aniqlash",
    "newPrice": "$1,500–4,000",
    "brands": "MISCO / Reichert / Atago",
    "models": "MISCO Palm Abbe Digital / Reichert AR200 / Atago PAL series",
    "hiddenCosts": "Sarf materiallari, kalibrlash, servis kontrakti, dasturiy ta'minot litsenziyasi va operator o'qitish xarajatlari.",
    "purchasingStrategy": "Sotib olishdan oldin utilization/ROI hisoblang; ko'pincha core facility, servis yoki contract lab orqali boshlash oqilona.",
    "slug": "refraktometr-raqamli"
  },
  {
    "id": "BIO-039",
    "number": 39,
    "name": "Lyuminestsent mikroskop",
    "category": "Mikroskopiya",
    "model": "Nikon Eclipse Ti2-E",
    "description": "Flyuoressent markerlar bilan bo'yalgan namunalarni ko'rsatadi.",
    "purpose": "Immunoflyuoressensiya, FISH, hujayra biologiyasi",
    "newPrice": "$10,000–100,000",
    "brands": "Leica / ZEISS / Olympus / Nikon",
    "models": "DMi8 / Axio Imager / BX53 / Eclipse",
    "hiddenCosts": "Objectives, filters/lasers, camera, software license, calibration va servis.",
    "purchasingStrategy": "Darhol sotib olishdan oldin utilization/ROI hisoblang; ko‘pincha core facility, servis yoki contract lab orqali boshlash oqilona.",
    "slug": "lyuminestsent-mikroskop"
  },
  {
    "id": "BIO-040",
    "number": 40,
    "name": "Elektron mikroskop (SEM)",
    "category": "Mikroskopiya",
    "model": "JEOL JSM-IT800",
    "description": "Elektron nur bilan yuqori ruxsatli yuzaki tasvir yaratadi.",
    "purpose": "Mikroblar morfologiyasi, materiallar strukturasi tahlili",
    "newPrice": "$150,000–500,000",
    "brands": "JEOL / Thermo Fisher / Zeiss",
    "models": "JEOL JSM-IT800 / Thermo Fisher Phenom / Zeiss EVO",
    "hiddenCosts": "Sarf materiallari, kalibrlash, servis kontrakti, dasturiy ta'minot litsenziyasi va operator o'qitish xarajatlari.",
    "purchasingStrategy": "Sotib olishdan oldin utilization/ROI hisoblang; ko'pincha core facility, servis yoki contract lab orqali boshlash oqilona.",
    "slug": "elektron-mikroskop-sem"
  },
  {
    "id": "BIO-041",
    "number": 41,
    "name": "Steril filtrlash tizimi",
    "category": "Mikrobiologiya",
    "model": "Millipore Stericup Quick Release 0.22µm",
    "description": "0,22 µm membrana orqali mikroblarni ajratadi.",
    "purpose": "Eritmalar, muhitlar, buferlarni steril filtrlash",
    "newPrice": "$500–10,000",
    "brands": "Merck / Sartorius / Pall",
    "models": "Stericup / filtration systems",
    "hiddenCosts": "Consumables, calibration, maintenance, spare parts, electricity va operator training.",
    "purchasingStrategy": "Darhol sotib olishdan oldin utilization/ROI hisoblang; ko‘pincha core facility, servis yoki contract lab orqali boshlash oqilona.",
    "slug": "steril-filtrlash-tizimi"
  },
  {
    "id": "BIO-042",
    "number": 42,
    "name": "Inkubator shaker (orbital)",
    "category": "Bioreaktorlar",
    "model": "Eppendorf Innova 44R",
    "description": "Harorat nazorati bilan orbital tebranish beruvchi inkubator.",
    "purpose": "Bakteriya o'stirish, fermentatsiya, hujayra o'stirish",
    "newPrice": "$3,000–20,000",
    "brands": "Eppendorf / INFORS HT / New Brunswick",
    "models": "Excella / Multitron / Innova",
    "hiddenCosts": "Consumables, calibration, maintenance, spare parts, electricity va operator training.",
    "purchasingStrategy": "Darhol sotib olishdan oldin utilization/ROI hisoblang; ko‘pincha core facility, servis yoki contract lab orqali boshlash oqilona.",
    "slug": "inkubator-shaker-orbital"
  },
  {
    "id": "BIO-043",
    "number": 43,
    "name": "Bioreaktор (fermentor)",
    "category": "Bioreaktorlar",
    "model": "Sartorius BIOSTAT B",
    "description": "Biotexnologik jarayonlar uchun nazorat qilinadigan reaktor.",
    "purpose": "Mikroorganizmlar, rekombinant oqsillar, bijg'ish jarayonlari",
    "newPrice": "$10,000–100,000",
    "brands": "Sartorius / Eppendorf / INFORS HT",
    "models": "BIOSTAT / DASGIP / Minifors",
    "hiddenCosts": "Sensors, probes, calibration, gas, media, single-use bags, cleaning/validation va spare parts.",
    "purchasingStrategy": "Darhol sotib olishdan oldin utilization/ROI hisoblang; ko‘pincha core facility, servis yoki contract lab orqali boshlash oqilona.",
    "slug": "bioreakt-fermentor"
  },
  {
    "id": "BIO-044",
    "number": 44,
    "name": "Dod (Toksikologik) tester",
    "category": "Analitika",
    "model": "HACH DR3900 Spektrofotometr",
    "description": "To'plam reagentlari asosida suv sifati parametrlarini o'lchaydi.",
    "purpose": "Suv tarkibidagi ifloslanish va zaharli moddalarni aniqlash",
    "newPrice": "$3,000–8,000",
    "brands": "HACH / Palintest",
    "models": "HACH DR3900 / Palintest Photometer 7500",
    "hiddenCosts": "Sarf materiallari, kalibrlash, servis kontrakti, dasturiy ta'minot litsenziyasi va operator o'qitish xarajatlari.",
    "purchasingStrategy": "Sotib olishdan oldin utilization/ROI hisoblang; ko'pincha core facility, servis yoki contract lab orqali boshlash oqilona.",
    "slug": "dod-toksikologik-tester"
  },
  {
    "id": "BIO-045",
    "number": 45,
    "name": "Mikroplanshet vasher (yuuvchi qurilma)",
    "category": "Analitika",
    "model": "BioTek ELx50",
    "description": "ELISA planshetlarini avtomatik ravishda yuvadi.",
    "purpose": "ELISA va boshqa immunotahlillar uchun tayyorlov",
    "newPrice": "$3,000–15,000",
    "brands": "BioTek / Thermo Fisher",
    "models": "405 TS / Wellwash",
    "hiddenCosts": "Consumables, calibration, maintenance, spare parts, electricity va operator training.",
    "purchasingStrategy": "Darhol sotib olishdan oldin utilization/ROI hisoblang; ko‘pincha core facility, servis yoki contract lab orqali boshlash oqilona.",
    "slug": "mikroplanshet-vasher-yuuvchi-qurilma"
  },
  {
    "id": "BIO-046",
    "number": 46,
    "name": "Gaz analiz qurilmasi (CO2/O2)",
    "category": "Hujayra kulturalari",
    "model": "Vaisala GMP252 CO2 Probe",
    "description": "Inkubator va fermentor muhitidagi gazlar darajasini nazorat qiladi.",
    "purpose": "Hujayra kulturasi va fermentatsion jarayonlar monitoringi",
    "newPrice": "$5,000–30,000",
    "brands": "Baker / STEMCELL Technologies / Don Whitley",
    "models": "Ruskinn / hypoxia systems",
    "hiddenCosts": "Consumables, calibration, maintenance, spare parts, electricity va operator training.",
    "purchasingStrategy": "Darhol sotib olishdan oldin utilization/ROI hisoblang; ko‘pincha core facility, servis yoki contract lab orqali boshlash oqilona.",
    "slug": "gaz-analiz-qurilmasi-co2-o2"
  },
  {
    "id": "BIO-047",
    "number": 47,
    "name": "Shpritsli nasos (syringe pump)",
    "category": "Avtomatlashtirish",
    "model": "Harvard Apparatus PHD ULTRA",
    "description": "Aniq tezlik va hajmda suyuqlik uzatuvchi nasos.",
    "purpose": "Mikrofluidika, farmakokinetik tajribalar, dozalash",
    "newPrice": "$2,000–6,000",
    "brands": "Harvard Apparatus / New Era Pump Systems",
    "models": "Harvard Apparatus PHD ULTRA / NE-1000",
    "hiddenCosts": "Sarf materiallari, kalibrlash, servis kontrakti, dasturiy ta'minot litsenziyasi va operator o'qitish xarajatlari.",
    "purchasingStrategy": "Sotib olishdan oldin utilization/ROI hisoblang; ko'pincha core facility, servis yoki contract lab orqali boshlash oqilona.",
    "slug": "shpritsli-nasos-syringe-pump"
  },
  {
    "id": "BIO-048",
    "number": 48,
    "name": "Peristaltik nasos",
    "category": "Avtomatlashtirish",
    "model": "Watson-Marlow 630Di",
    "description": "Steril naychalar orqali suyuqlikni agressif ta'sirsiz uzatadi.",
    "purpose": "Fermentor, bioreaktоr yoki kolonkaga suyuqlik uzatish",
    "newPrice": "$1,500–5,000",
    "brands": "Watson-Marlow / Cole-Parmer (Masterflex)",
    "models": "Watson-Marlow 630Di / Masterflex L/S",
    "hiddenCosts": "Sarf materiallari, kalibrlash, servis kontrakti, dasturiy ta'minot litsenziyasi va operator o'qitish xarajatlari.",
    "purchasingStrategy": "Sotib olishdan oldin utilization/ROI hisoblang; ko'pincha core facility, servis yoki contract lab orqali boshlash oqilona.",
    "slug": "peristaltik-nasos"
  },
  {
    "id": "BIO-049",
    "number": 49,
    "name": "Gelga aylantiruvchi sistema (gel documentation)",
    "category": "Analitika",
    "model": "Bio-Rad Gel Doc XR+",
    "description": "UV yorug'lik ostida gelni rasm qiladi va tahlil qiladi.",
    "purpose": "Agaroz gelda DNK/oqsil bandlarini ko'rish va tahlil qilish",
    "newPrice": "$2,000–15,000",
    "brands": "Bio-Rad / Azure / Analytik Jena",
    "models": "Gel Doc Go / Azure 200 / UVP systems",
    "hiddenCosts": "Consumables, calibration, maintenance, spare parts, electricity va operator training.",
    "purchasingStrategy": "Darhol sotib olishdan oldin utilization/ROI hisoblang; ko‘pincha core facility, servis yoki contract lab orqali boshlash oqilona.",
    "slug": "gelga-aylantiruvchi-sistema-gel-documentation"
  },
  {
    "id": "BIO-050",
    "number": 50,
    "name": "Lyofilizat qabul qurilmasi (SPME)",
    "category": "Namuna tayyorlash",
    "model": "Supelco SPME Fiber Assembly",
    "description": "Namunadan bug' fazasidagi komponentlarni adsorbsiyalaydi.",
    "purpose": "Qoldiq aromatlar, pestitsidlar GC tahlili uchun namuna tayyorlash",
    "newPrice": "$300–1,500 (fiber to'plami)",
    "brands": "Supelco (MilliporeSigma) / Restek",
    "models": "Supelco SPME Fiber Assembly / Restek SPME fiber",
    "hiddenCosts": "Sarf materiallari, kalibrlash, servis kontrakti, dasturiy ta'minot litsenziyasi va operator o'qitish xarajatlari.",
    "purchasingStrategy": "Sotib olishdan oldin utilization/ROI hisoblang; ko'pincha core facility, servis yoki contract lab orqali boshlash oqilona.",
    "slug": "lyofilizat-qabul-qurilmasi-spme"
  },
  {
    "id": "BIO-051",
    "number": 51,
    "name": "Suv distillyatori",
    "category": "Namuna tayyorlash",
    "model": "Milli-Q IQ 7000 (Merck)",
    "description": "Ultratoza suv (18.2 MΩ·cm) ishlab chiqaradi.",
    "purpose": "PCR, HPLC, hujayra kulturasi va buferlar uchun toza suv",
    "newPrice": "$3,000–30,000",
    "brands": "Merck / Sartorius / Thermo Fisher",
    "models": "Milli-Q / arium / Barnstead",
    "hiddenCosts": "Consumables, calibration, maintenance, spare parts, electricity va operator training.",
    "purchasingStrategy": "Darhol sotib olishdan oldin utilization/ROI hisoblang; ko‘pincha core facility, servis yoki contract lab orqali boshlash oqilona.",
    "slug": "suv-distillyatori"
  },
  {
    "id": "BIO-052",
    "number": 52,
    "name": "Termomixer (blok termostat)",
    "category": "Namuna tayyorlash",
    "model": "Eppendorf ThermoMixer C",
    "description": "Aralashtirishni isitish bilan birlashtirib qisqa trubkalarda inkubatsiya qiladi.",
    "purpose": "Ferment reaksiyalari, antikor inkubatsiyasi, digestion",
    "newPrice": "$2,500–6,000",
    "brands": "Eppendorf / Grant Bio",
    "models": "Eppendorf ThermoMixer C / Grant Bio PCMT",
    "hiddenCosts": "Sarf materiallari, kalibrlash, servis kontrakti, dasturiy ta'minot litsenziyasi va operator o'qitish xarajatlari.",
    "purchasingStrategy": "Sotib olishdan oldin utilization/ROI hisoblang; ko'pincha core facility, servis yoki contract lab orqali boshlash oqilona.",
    "slug": "termomixer-blok-termostat"
  },
  {
    "id": "BIO-053",
    "number": 53,
    "name": "Avtomatik kolonka (SPE)",
    "category": "Avtomatlashtirish",
    "model": "Waters Oasis HLB 3cc Cartridge",
    "description": "Qattiq faza ekstraksiyasi kolonkasi.",
    "purpose": "Murakkab matrikslardan maqsadli moddani tozalash, konsentrlash",
    "newPrice": "$15,000–50,000 (avtomatlashtirilgan tizim)",
    "brands": "Waters / Biotage",
    "models": "Waters Oasis HLB (kartrij) / Biotage Extrahera (avtomatlashtirilgan tizim)",
    "hiddenCosts": "Sarf materiallari, kalibrlash, servis kontrakti, dasturiy ta'minot litsenziyasi va operator o'qitish xarajatlari.",
    "purchasingStrategy": "Sotib olishdan oldin utilization/ROI hisoblang; ko'pincha core facility, servis yoki contract lab orqali boshlash oqilona.",
    "slug": "avtomatik-kolonka-spe"
  },
  {
    "id": "BIO-054",
    "number": 54,
    "name": "Protein elektroforez tizimi (SDS-PAGE)",
    "category": "Molekulyar biologiya",
    "model": "Bio-Rad Mini-PROTEAN Tetra Cell",
    "description": "Oqsillarni molekulyar massa bo'yicha ajratadi.",
    "purpose": "Oqsil profili, tozalik nazorati, Western blot tayyorlash",
    "newPrice": "$500–5,000",
    "brands": "Bio-Rad / Thermo Fisher",
    "models": "Mini-PROTEAN / SureLock",
    "hiddenCosts": "Consumables, calibration, maintenance, spare parts, electricity va operator training.",
    "purchasingStrategy": "Darhol sotib olishdan oldin utilization/ROI hisoblang; ko‘pincha core facility, servis yoki contract lab orqali boshlash oqilona.",
    "slug": "protein-elektroforez-tizimi-sds-page"
  },
  {
    "id": "BIO-055",
    "number": 55,
    "name": "Izoelektrik fokuslash (IEF) tizimi",
    "category": "Analitika",
    "model": "Bio-Rad Protean IEF Cell",
    "description": "Oqsillarni izoelektrik nuqtasi bo'yicha ajratadi.",
    "purpose": "2D-elektroforez, oqsil xarakteristikasi",
    "newPrice": "$8,000–20,000",
    "brands": "Bio-Rad",
    "models": "Bio-Rad Protean IEF Cell",
    "hiddenCosts": "Sarf materiallari, kalibrlash, servis kontrakti, dasturiy ta'minot litsenziyasi va operator o'qitish xarajatlari.",
    "purchasingStrategy": "Sotib olishdan oldin utilization/ROI hisoblang; ko'pincha core facility, servis yoki contract lab orqali boshlash oqilona.",
    "slug": "izoelektrik-fokuslash-ief-tizimi"
  },
  {
    "id": "BIO-056",
    "number": 56,
    "name": "Oqsil tozalash tizimi (FPLC)",
    "category": "Analitika",
    "model": "Cytiva AKTA Pure 25",
    "description": "Ko'p bosqichli xromatografiyani avtomatlashtiradi.",
    "purpose": "Rekombinant oqsillar, antitelolar tozalash",
    "newPrice": "$30,000–150,000",
    "brands": "Cytiva / Bio-Rad",
    "models": "ÄKTA / NGC",
    "hiddenCosts": "Consumables, calibration, maintenance, spare parts, electricity va operator training.",
    "purchasingStrategy": "Darhol sotib olishdan oldin utilization/ROI hisoblang; ko‘pincha core facility, servis yoki contract lab orqali boshlash oqilona.",
    "slug": "oqsil-tozalash-tizimi-fplc"
  },
  {
    "id": "BIO-057",
    "number": 57,
    "name": "Xemiluminessent deteksiya tizimi",
    "category": "Analitika",
    "model": "Amersham ImageQuant 800",
    "description": "Kimyoviy lyuminessensiya va flyuorессentlikni kuchaytiradi va qayd etadi.",
    "purpose": "Western blot, Dot blot tasvirlarini olish",
    "newPrice": "$10,000–80,000",
    "brands": "Bio-Rad / Azure / Cytiva",
    "models": "ChemiDoc / Sapphire / Amersham",
    "hiddenCosts": "Consumables, calibration, maintenance, spare parts, electricity va operator training.",
    "purchasingStrategy": "Darhol sotib olishdan oldin utilization/ROI hisoblang; ko‘pincha core facility, servis yoki contract lab orqali boshlash oqilona.",
    "slug": "xemiluminessent-deteksiya-tizimi"
  },
  {
    "id": "BIO-058",
    "number": 58,
    "name": "Yadroviy magnit rezonans (NMR)",
    "category": "Analitika",
    "model": "Bruker AVANCE NEO 400MHz",
    "description": "Magnit maydon va radio-to'lqinlar yordamida tuzilishni aniqlaydi.",
    "purpose": "Organik birikmalar tuzilishini aniqlash, sof modda tahlili",
    "newPrice": "$300,000–900,000+",
    "brands": "Bruker",
    "models": "Bruker AVANCE NEO 400MHz",
    "hiddenCosts": "Sarf materiallari, kalibrlash, servis kontrakti, dasturiy ta'minot litsenziyasi va operator o'qitish xarajatlari.",
    "purchasingStrategy": "Sotib olishdan oldin utilization/ROI hisoblang; ko'pincha core facility, servis yoki contract lab orqali boshlash oqilona.",
    "slug": "yadroviy-magnit-rezonans-nmr"
  },
  {
    "id": "BIO-059",
    "number": 59,
    "name": "Infra-qizil spektrometr (FTIR)",
    "category": "Analitika",
    "model": "Bruker ALPHA II",
    "description": "Infra-qizil nurni utkazib molekulyar tuzilishni aniqlaydi.",
    "purpose": "Oziq-ovqat qo'shimchalari, polimer, oqsil, yog' tarkibi tahlili",
    "newPrice": "$15,000–40,000",
    "brands": "Bruker / Agilent / Thermo Fisher",
    "models": "Bruker ALPHA II / Agilent Cary 630 / Thermo Nicolet",
    "hiddenCosts": "Sarf materiallari, kalibrlash, servis kontrakti, dasturiy ta'minot litsenziyasi va operator o'qitish xarajatlari.",
    "purchasingStrategy": "Sotib olishdan oldin utilization/ROI hisoblang; ko'pincha core facility, servis yoki contract lab orqali boshlash oqilona.",
    "slug": "infra-qizil-spektrometr-ftir"
  },
  {
    "id": "BIO-060",
    "number": 60,
    "name": "Ramanga spektroskopiyasi",
    "category": "Analitika",
    "model": "Renishaw inVia Raman Microscope",
    "description": "Ramanaga sochilish orqali kimyoviy tarkibni aniqlaydi.",
    "purpose": "Dori sifati, material tahlili, mikrobial identifikatsiya",
    "newPrice": "$80,000–250,000",
    "brands": "Renishaw / Horiba / Thermo Fisher",
    "models": "Renishaw inVia Raman Microscope / Horiba LabRAM",
    "hiddenCosts": "Sarf materiallari, kalibrlash, servis kontrakti, dasturiy ta'minot litsenziyasi va operator o'qitish xarajatlari.",
    "purchasingStrategy": "Sotib olishdan oldin utilization/ROI hisoblang; ko'pincha core facility, servis yoki contract lab orqali boshlash oqilona.",
    "slug": "ramanga-spektroskopiyasi"
  },
  {
    "id": "BIO-061",
    "number": 61,
    "name": "Mikroto'm (Tissue sectioner)",
    "category": "Analitika",
    "model": "Leica RM2255",
    "description": "To'qimalardan 2-10 mkm qalinlikdagi kesimlar tayyorlaydi.",
    "purpose": "Gistologik bo'yash, immunohistokimyo preparatlari",
    "newPrice": "$8,000–20,000",
    "brands": "Leica Biosystems / Thermo Fisher",
    "models": "Leica RM2255 / Thermo Fisher HM 325",
    "hiddenCosts": "Sarf materiallari, kalibrlash, servis kontrakti, dasturiy ta'minot litsenziyasi va operator o'qitish xarajatlari.",
    "purchasingStrategy": "Sotib olishdan oldin utilization/ROI hisoblang; ko'pincha core facility, servis yoki contract lab orqali boshlash oqilona.",
    "slug": "mikroto-m-tissue-sectioner"
  },
  {
    "id": "BIO-062",
    "number": 62,
    "name": "Kriostat",
    "category": "Sovutish va saqlash",
    "model": "Leica CM3050 S",
    "description": "Muzlatilgan to'qimalardan yanada nozik kesimlar oladi.",
    "purpose": "Tez diagnostika, qo'shimcha muzlatilgan to'qima kesim tahlili",
    "newPrice": "$25,000–45,000",
    "brands": "Leica Biosystems / Thermo Fisher",
    "models": "Leica CM3050 S / Thermo Fisher CryoStar NX70",
    "hiddenCosts": "Sarf materiallari, kalibrlash, servis kontrakti, dasturiy ta'minot litsenziyasi va operator o'qitish xarajatlari.",
    "purchasingStrategy": "Sotib olishdan oldin utilization/ROI hisoblang; ko'pincha core facility, servis yoki contract lab orqali boshlash oqilona.",
    "slug": "kriostat"
  },
  {
    "id": "BIO-063",
    "number": 63,
    "name": "Immuno-xistokimyo (IHC) stantsiyasi",
    "category": "Analitika",
    "model": "Leica BOND-III",
    "description": "Antikor asosida to'qimalarda maqsadli antigenlarni ko'rsatadi.",
    "purpose": "Onkologiya, patologiya diagnostikasi",
    "newPrice": "$80,000–200,000",
    "brands": "Leica Biosystems / Roche (Ventana) / Agilent (Dako)",
    "models": "Leica BOND-III / Ventana BenchMark ULTRA",
    "hiddenCosts": "Sarf materiallari, kalibrlash, servis kontrakti, dasturiy ta'minot litsenziyasi va operator o'qitish xarajatlari.",
    "purchasingStrategy": "Sotib olishdan oldin utilization/ROI hisoblang; ko'pincha core facility, servis yoki contract lab orqali boshlash oqilona.",
    "slug": "immuno-xistokimyo-ihc-stantsiyasi"
  },
  {
    "id": "BIO-064",
    "number": 64,
    "name": "Avtomatik bo'yash qurilmasi (stainer)",
    "category": "Avtomatlashtirish",
    "model": "Sakura Tissue-Tek Prisma Plus",
    "description": "Gistologik bo'yash jarayonini avtomatlashtiradi.",
    "purpose": "HE, PAS va boshqa bo'yash usullarini standartlashtirish",
    "newPrice": "$40,000–100,000",
    "brands": "Sakura Finetek / Leica Biosystems",
    "models": "Sakura Tissue-Tek Prisma Plus / Leica ST5020",
    "hiddenCosts": "Sarf materiallari, kalibrlash, servis kontrakti, dasturiy ta'minot litsenziyasi va operator o'qitish xarajatlari.",
    "purchasingStrategy": "Sotib olishdan oldin utilization/ROI hisoblang; ko'pincha core facility, servis yoki contract lab orqali boshlash oqilona.",
    "slug": "avtomatik-bo-yash-qurilmasi-stainer"
  },
  {
    "id": "BIO-065",
    "number": 65,
    "name": "Mikroinjeksiya tizimi",
    "category": "Hujayra kulturalari",
    "model": "Eppendorf TransferMan 4r",
    "description": "Mikromanipulatorlar bilan hujayra ichiga nanoinjeksiya qiladi.",
    "purpose": "In vitro urug'lantirish, gen transformatsiyasi",
    "newPrice": "$15,000–35,000",
    "brands": "Eppendorf / Sutter Instrument",
    "models": "Eppendorf TransferMan 4r / Sutter MP-285",
    "hiddenCosts": "Sarf materiallari, kalibrlash, servis kontrakti, dasturiy ta'minot litsenziyasi va operator o'qitish xarajatlari.",
    "purchasingStrategy": "Sotib olishdan oldin utilization/ROI hisoblang; ko'pincha core facility, servis yoki contract lab orqali boshlash oqilona.",
    "slug": "mikroinjeksiya-tizimi"
  },
  {
    "id": "BIO-066",
    "number": 66,
    "name": "Elektroporatsion sistema",
    "category": "Hujayra kulturalari",
    "model": "Bio-Rad Gene Pulser Xcell",
    "description": "Elektr impulsi bilan hujayra pardasi o'tkazuvchanligini oshiradi.",
    "purpose": "Plazmid, siRNA, oqsil hujayra ichiga kiritish",
    "newPrice": "$5,000–30,000",
    "brands": "Bio-Rad / Lonza / Thermo Fisher",
    "models": "Gene Pulser / Nucleofector / Neon",
    "hiddenCosts": "Consumables, calibration, maintenance, spare parts, electricity va operator training.",
    "purchasingStrategy": "Darhol sotib olishdan oldin utilization/ROI hisoblang; ko‘pincha core facility, servis yoki contract lab orqali boshlash oqilona.",
    "slug": "elektroporatsion-sistema"
  },
  {
    "id": "BIO-067",
    "number": 67,
    "name": "Bioprinter (3D biologik bosib chiqarish)",
    "category": "Hujayra kulturalari",
    "model": "CELLINK BIO X6",
    "description": "Tirik hujayralar va bioink bilan 3D to'qima yaratadi.",
    "purpose": "To'qima muhandisligi, dori sinovlari, sun'iy organlar",
    "newPrice": "$30,000–60,000",
    "brands": "CELLINK (BICO) / Allevi / RegenHU",
    "models": "CELLINK BIO X6 / Allevi 3",
    "hiddenCosts": "Sarf materiallari, kalibrlash, servis kontrakti, dasturiy ta'minot litsenziyasi va operator o'qitish xarajatlari.",
    "purchasingStrategy": "Sotib olishdan oldin utilization/ROI hisoblang; ko'pincha core facility, servis yoki contract lab orqali boshlash oqilona.",
    "slug": "bioprinter-3d-biologik-bosib-chiqarish"
  },
  {
    "id": "BIO-068",
    "number": 68,
    "name": "Mikrokapsulalash qurilmasi",
    "category": "Analitika",
    "model": "Buchi Nano Spray Dryer B-90 HP",
    "description": "Nano va mikro o'lchamli kapsulalar hosil qiladi.",
    "purpose": "Dori transporti, probiotiklar kapsulalash",
    "newPrice": "$50,000–90,000",
    "brands": "Buchi",
    "models": "Buchi Nano Spray Dryer B-90 HP",
    "hiddenCosts": "Sarf materiallari, kalibrlash, servis kontrakti, dasturiy ta'minot litsenziyasi va operator o'qitish xarajatlari.",
    "purchasingStrategy": "Sotib olishdan oldin utilization/ROI hisoblang; ko'pincha core facility, servis yoki contract lab orqali boshlash oqilona.",
    "slug": "mikrokapsulalash-qurilmasi"
  },
  {
    "id": "BIO-069",
    "number": 69,
    "name": "Dinamik yorug'lik sochilishi (DLS)",
    "category": "Analitika",
    "model": "Malvern Panalytical Zetasizer Ultra",
    "description": "Nanopartikulalar o'lchamini va zeta-potensialini o'lchaydi.",
    "purpose": "Nanodorolar, liposomalar, kolloidlar tahlili",
    "newPrice": "$50,000–90,000",
    "brands": "Malvern Panalytical",
    "models": "Malvern Panalytical Zetasizer Ultra",
    "hiddenCosts": "Sarf materiallari, kalibrlash, servis kontrakti, dasturiy ta'minot litsenziyasi va operator o'qitish xarajatlari.",
    "purchasingStrategy": "Sotib olishdan oldin utilization/ROI hisoblang; ko'pincha core facility, servis yoki contract lab orqali boshlash oqilona.",
    "slug": "dinamik-yorug-lik-sochilishi-dls"
  },
  {
    "id": "BIO-070",
    "number": 70,
    "name": "Qo'lda yadro aniqlash tizimi (Lateral Flow)",
    "category": "Analitika",
    "model": "SD Biosensor Standard F (multiplex)",
    "description": "Lateral oqim immunoassay orqali tezkor aniqlash.",
    "purpose": "Maydonda tezkor diagnostika (COVID-19, gripp, ABO va boshq.)",
    "newPrice": "$3,000–10,000",
    "brands": "SD Biosensor / Qiagen (ESEQuant)",
    "models": "SD Biosensor Standard F",
    "hiddenCosts": "Sarf materiallari, kalibrlash, servis kontrakti, dasturiy ta'minot litsenziyasi va operator o'qitish xarajatlari.",
    "purchasingStrategy": "Sotib olishdan oldin utilization/ROI hisoblang; ko'pincha core facility, servis yoki contract lab orqali boshlash oqilona.",
    "slug": "qo-lda-yadro-aniqlash-tizimi-lateral-flow"
  },
  {
    "id": "BIO-071",
    "number": 71,
    "name": "MALDI-TOF massa spektrometr",
    "category": "Mikrobiologiya",
    "model": "Bruker Microflex LT/SH",
    "description": "Matritsada lazer desorbsiyasi bilan ionlash va massa o'lchash.",
    "purpose": "Mikrob identifikatsiyasi, oqsil tuzilishi tahlili",
    "newPrice": "$150,000–300,000+",
    "brands": "Bruker / bioMérieux",
    "models": "MALDI Biotyper / VITEK MS",
    "hiddenCosts": "Consumables, calibration, maintenance, spare parts, electricity va operator training.",
    "purchasingStrategy": "Darhol sotib olishdan oldin utilization/ROI hisoblang; ko‘pincha core facility, servis yoki contract lab orqali boshlash oqilona.",
    "slug": "maldi-tof-massa-spektrometr"
  },
  {
    "id": "BIO-072",
    "number": 72,
    "name": "Bioimpedans tahlilchi",
    "category": "Analitika",
    "model": "Impedimed SFB7",
    "description": "Elektr o'tkazuvchanlik orqali biologik parametrlarni o'lchaydi.",
    "purpose": "Hujayra kulturasi tirikligini, fermentatsiya holatini kuzatish",
    "newPrice": "$8,000–20,000",
    "brands": "ImpediMed",
    "models": "Impedimed SFB7",
    "hiddenCosts": "Sarf materiallari, kalibrlash, servis kontrakti, dasturiy ta'minot litsenziyasi va operator o'qitish xarajatlari.",
    "purchasingStrategy": "Sotib olishdan oldin utilization/ROI hisoblang; ko'pincha core facility, servis yoki contract lab orqali boshlash oqilona.",
    "slug": "bioimpedans-tahlilchi"
  },
  {
    "id": "BIO-073",
    "number": 73,
    "name": "Termal tahlil qurilmasi (DSC)",
    "category": "Analitika",
    "model": "TA Instruments DSC 250",
    "description": "Moddalar issiqlik sig'imi va fazaviy o'tishlarini tahlil qiladi.",
    "purpose": "Lipidlar, oqsillar denaturatsiya tahlili, oziq-ovqat formülasi",
    "newPrice": "$40,000–70,000",
    "brands": "TA Instruments / PerkinElmer / Netzsch",
    "models": "TA Instruments DSC 250 / PerkinElmer DSC 8500",
    "hiddenCosts": "Sarf materiallari, kalibrlash, servis kontrakti, dasturiy ta'minot litsenziyasi va operator o'qitish xarajatlari.",
    "purchasingStrategy": "Sotib olishdan oldin utilization/ROI hisoblang; ko'pincha core facility, servis yoki contract lab orqali boshlash oqilona.",
    "slug": "termal-tahlil-qurilmasi-dsc"
  },
  {
    "id": "BIO-074",
    "number": 74,
    "name": "Rotary evaporator (rotovap)",
    "category": "Namuna tayyorlash",
    "model": "Buchi R-300",
    "description": "Vakuum va aylanish yordamida past haroratda bug'lantiradi.",
    "purpose": "Erituvchilarni ajratish, ekstraktlarni konsentrlash",
    "newPrice": "$6,000–15,000",
    "brands": "Buchi / IKA / Heidolph",
    "models": "Buchi R-300 / IKA RV 10 / Heidolph Hei-VAP",
    "hiddenCosts": "Sarf materiallari, kalibrlash, servis kontrakti, dasturiy ta'minot litsenziyasi va operator o'qitish xarajatlari.",
    "purchasingStrategy": "Sotib olishdan oldin utilization/ROI hisoblang; ko'pincha core facility, servis yoki contract lab orqali boshlash oqilona.",
    "slug": "rotary-evaporator-rotovap"
  },
  {
    "id": "BIO-075",
    "number": 75,
    "name": "Sonikator (bath type)",
    "category": "Namuna tayyorlash",
    "model": "Elmasonic S60H",
    "description": "Ultratovush vanna orqali namunalarni tozalaydi yoki eritadi.",
    "purpose": "Kolonka tozalash, membrana eritmasi, liposoma tayyorlash",
    "newPrice": "$2,000–30,000",
    "brands": "Qsonica / Hielscher / Sonics",
    "models": "Q700 / UP series / VCX",
    "hiddenCosts": "Consumables, calibration, maintenance, spare parts, electricity va operator training.",
    "purchasingStrategy": "Darhol sotib olishdan oldin utilization/ROI hisoblang; ko‘pincha core facility, servis yoki contract lab orqali boshlash oqilona.",
    "slug": "sonikator-bath-type"
  },
  {
    "id": "BIO-076",
    "number": 76,
    "name": "Muhit tayyorlash stantsiyasi",
    "category": "Mikrobiologiya",
    "model": "Integra MEDIACLAVE 30",
    "description": "Mikrobiologik muhitlarni sterillash va tarqatishni avtomatlashtiradi.",
    "purpose": "Agarlı va suyuq muhitlar ommaviy tayyorlash",
    "newPrice": "$15,000–30,000",
    "brands": "Integra Biosciences / Getinge",
    "models": "Integra MEDIACLAVE 30",
    "hiddenCosts": "Sarf materiallari, kalibrlash, servis kontrakti, dasturiy ta'minot litsenziyasi va operator o'qitish xarajatlari.",
    "purchasingStrategy": "Sotib olishdan oldin utilization/ROI hisoblang; ko'pincha core facility, servis yoki contract lab orqali boshlash oqilona.",
    "slug": "muhit-tayyorlash-stantsiyasi"
  },
  {
    "id": "BIO-077",
    "number": 77,
    "name": "Koloniyalar sanash qurilmasi",
    "category": "Mikrobiologiya",
    "model": "Interscience Scan 500",
    "description": "Petri kosachasidagi koloniyalarni avtomatik sanaydi.",
    "purpose": "Mikrobiologik nazorat: oziq-ovqat, suv sifati",
    "newPrice": "$500–8,000",
    "brands": "IUL / Stuart / Synbiosis",
    "models": "SphereFlash / colony counters",
    "hiddenCosts": "Consumables, calibration, maintenance, spare parts, electricity va operator training.",
    "purchasingStrategy": "Darhol sotib olishdan oldin utilization/ROI hisoblang; ko‘pincha core facility, servis yoki contract lab orqali boshlash oqilona.",
    "slug": "koloniyalar-sanash-qurilmasi"
  },
  {
    "id": "BIO-078",
    "number": 78,
    "name": "Stomacher (Homogenizator qopchali)",
    "category": "Molekulyar biologiya",
    "model": "Seward Stomacher 400 Circulator",
    "description": "Mahsulot namunalarini steril paketda siqib homogenizatsiya qiladi.",
    "purpose": "Oziq-ovqat namunalarini tez va steril tayyorlash",
    "newPrice": "$2,000–50,000",
    "brands": "IKA / Bertin / Polytron",
    "models": "T 25 / Precellys / PT",
    "hiddenCosts": "Consumables, calibration, maintenance, spare parts, electricity va operator training.",
    "purchasingStrategy": "Darhol sotib olishdan oldin utilization/ROI hisoblang; ko‘pincha core facility, servis yoki contract lab orqali boshlash oqilona.",
    "slug": "stomacher-homogenizator-qopchali"
  },
  {
    "id": "BIO-079",
    "number": 79,
    "name": "Ferment faolligini o'lchash stantsiyasi",
    "category": "Analitika",
    "model": "Molecular Devices SpectraMax i3x",
    "description": "Ko'plab o'lchash rejimlarini qamrovchi ko'p rejimli planshet o'quvchisi.",
    "purpose": "Ferment kinetikasi, sellyuloza va proteaza faolligini o'lchash",
    "newPrice": "$30,000–60,000",
    "brands": "Molecular Devices / BioTek (Agilent) / Tecan",
    "models": "Molecular Devices SpectraMax i3x / BioTek Synergy H1",
    "hiddenCosts": "Sarf materiallari, kalibrlash, servis kontrakti, dasturiy ta'minot litsenziyasi va operator o'qitish xarajatlari.",
    "purchasingStrategy": "Sotib olishdan oldin utilization/ROI hisoblang; ko'pincha core facility, servis yoki contract lab orqali boshlash oqilona.",
    "slug": "ferment-faolligini-o-lchash-stantsiyasi"
  },
  {
    "id": "BIO-080",
    "number": 80,
    "name": "Kapillyar elektroforez sistema (CE)",
    "category": "Molekulyar biologiya",
    "model": "Beckman Coulter PA 800 Plus",
    "description": "Kapillyarda yuqori ruxsatli elektroforetik ajratish.",
    "purpose": "Monoklonal antitelolar sifati, protein va glikoprotein tahlili",
    "newPrice": "$50,000–150,000",
    "brands": "Beckman Coulter / Thermo Fisher (ABI)",
    "models": "Beckman Coulter PA 800 Plus / ABI 3500 Genetic Analyzer",
    "hiddenCosts": "Sarf materiallari, kalibrlash, servis kontrakti, dasturiy ta'minot litsenziyasi va operator o'qitish xarajatlari.",
    "purchasingStrategy": "Sotib olishdan oldin utilization/ROI hisoblang; ko'pincha core facility, servis yoki contract lab orqali boshlash oqilona.",
    "slug": "kapillyar-elektroforez-sistema-ce"
  },
  {
    "id": "BIO-081",
    "number": 81,
    "name": "Biosensor (SPR tizimi)",
    "category": "Analitika",
    "model": "Cytiva Biacore T200",
    "description": "Yuzaviy plazmon rezonans orqali molekulyar o'zaro ta'sirni kuzatadi.",
    "purpose": "Antigen-antikor, retseptor-ligand bog'lanish kinetikasi",
    "newPrice": "$150,000–300,000",
    "brands": "Cytiva (GE Healthcare)",
    "models": "Cytiva Biacore T200",
    "hiddenCosts": "Sarf materiallari, kalibrlash, servis kontrakti, dasturiy ta'minot litsenziyasi va operator o'qitish xarajatlari.",
    "purchasingStrategy": "Sotib olishdan oldin utilization/ROI hisoblang; ko'pincha core facility, servis yoki contract lab orqali boshlash oqilona.",
    "slug": "biosensor-spr-tizimi"
  },
  {
    "id": "BIO-082",
    "number": 82,
    "name": "Mikrofluidik chip tizimi",
    "category": "Molekulyar biologiya",
    "model": "Fluidigm Biomark HD",
    "description": "Nano-litr hajmda parallel PCR va gen ekspressiyasini bajaradi.",
    "purpose": "Bir hujayra tahlili, NGS kutubxona tayyorlash",
    "newPrice": "$150,000–250,000",
    "brands": "Standard BioTools (avvalgi Fluidigm)",
    "models": "Fluidigm Biomark HD",
    "hiddenCosts": "Sarf materiallari, kalibrlash, servis kontrakti, dasturiy ta'minot litsenziyasi va operator o'qitish xarajatlari.",
    "purchasingStrategy": "Sotib olishdan oldin utilization/ROI hisoblang; ko'pincha core facility, servis yoki contract lab orqali boshlash oqilona.",
    "slug": "mikrofluidik-chip-tizimi"
  },
  {
    "id": "BIO-083",
    "number": 83,
    "name": "Kislorod o'lchagich (Dissolved O2)",
    "category": "Bioreaktorlar",
    "model": "Mettler Toledo InPro 6800i",
    "description": "Fermentor va bioreaktorlarda eritilgan kislorod darajasini kuzatadi.",
    "purpose": "Aerob fermentatsiya jarayonini boshqarish",
    "newPrice": "$2,000–8,000 (sensor/monitor tizimi)",
    "brands": "Mettler Toledo / Hamilton",
    "models": "Mettler Toledo InPro 6800i",
    "hiddenCosts": "Sarf materiallari, kalibrlash, servis kontrakti, dasturiy ta'minot litsenziyasi va operator o'qitish xarajatlari.",
    "purchasingStrategy": "Sotib olishdan oldin utilization/ROI hisoblang; ko'pincha core facility, servis yoki contract lab orqali boshlash oqilona.",
    "slug": "kislorod-o-lchagich-dissolved-o2"
  },
  {
    "id": "BIO-084",
    "number": 84,
    "name": "Kriokonservatsiya tizimi",
    "category": "Sovutish va saqlash",
    "model": "Planer Kryo 560-16",
    "description": "Hujayra va to'qimalarni nazorat qilinadigan tezlikda muzlatadi.",
    "purpose": "Bank hujayralari, embriologiya, mikrob to'plamlari saqlash",
    "newPrice": "$5,000–30,000",
    "brands": "Thermo Fisher / custom cryogenic suppliers",
    "models": "cryogenic workstations",
    "hiddenCosts": "Consumables, calibration, maintenance, spare parts, electricity va operator training.",
    "purchasingStrategy": "Darhol sotib olishdan oldin utilization/ROI hisoblang; ko‘pincha core facility, servis yoki contract lab orqali boshlash oqilona.",
    "slug": "kriokonservatsiya-tizimi"
  },
  {
    "id": "BIO-085",
    "number": 85,
    "name": "Termogravimetrik tahlilchi (TGA)",
    "category": "Analitika",
    "model": "TA Instruments TGA 550",
    "description": "Isitish jarayonida massa yo'qolishini o'lchaydi.",
    "purpose": "Namlik, kullik, organik komponent tahlili",
    "newPrice": "$40,000–70,000",
    "brands": "TA Instruments / PerkinElmer / Netzsch",
    "models": "TA Instruments TGA 550",
    "hiddenCosts": "Sarf materiallari, kalibrlash, servis kontrakti, dasturiy ta'minot litsenziyasi va operator o'qitish xarajatlari.",
    "purchasingStrategy": "Sotib olishdan oldin utilization/ROI hisoblang; ko'pincha core facility, servis yoki contract lab orqali boshlash oqilona.",
    "slug": "termogravimetrik-tahlilchi-tga"
  },
  {
    "id": "BIO-086",
    "number": 86,
    "name": "Elektrokimyoviy analizator",
    "category": "Analitika",
    "model": "Metrohm 910 PSTAT mini",
    "description": "Sikllik voltammetriya va impedans spektroskopiyasini bajaradi.",
    "purpose": "Biosensor ishlab chiqish, korroziya tadqiqotlari",
    "newPrice": "$8,000–20,000",
    "brands": "Metrohm Autolab / Gamry Instruments",
    "models": "Metrohm 910 PSTAT mini / Gamry Interface 1010E",
    "hiddenCosts": "Sarf materiallari, kalibrlash, servis kontrakti, dasturiy ta'minot litsenziyasi va operator o'qitish xarajatlari.",
    "purchasingStrategy": "Sotib olishdan oldin utilization/ROI hisoblang; ko'pincha core facility, servis yoki contract lab orqali boshlash oqilona.",
    "slug": "elektrokimyoviy-analizator"
  },
  {
    "id": "BIO-087",
    "number": 87,
    "name": "Kombinatorial kimyo roboti (liquid handler)",
    "category": "Avtomatlashtirish",
    "model": "Hamilton STAR",
    "description": "Ko'p kanalda parallel suyuqlik manipulyatsiyasini avtomatlashtiradi.",
    "purpose": "HTS (High-Throughput Screening), dori kashfiyoti",
    "newPrice": "$20,000–300,000+",
    "brands": "Hamilton / Tecan / Beckman Coulter",
    "models": "STAR / Fluent / Biomek",
    "hiddenCosts": "Consumables, calibration, maintenance, spare parts, electricity va operator training.",
    "purchasingStrategy": "Darhol sotib olishdan oldin utilization/ROI hisoblang; ko‘pincha core facility, servis yoki contract lab orqali boshlash oqilona.",
    "slug": "kombinatorial-kimyo-roboti-liquid-handler"
  },
  {
    "id": "BIO-088",
    "number": 88,
    "name": "Koloriimetrik analizator (suv sifati)",
    "category": "Analitika",
    "model": "HACH DR6000",
    "description": "Spektrofotometrik asosda suv kimyosi parametrlarini o'lchaydi.",
    "purpose": "Nitrat, fosfat, ammiak, xlor darajasi nazorati",
    "newPrice": "$8,000–15,000",
    "brands": "HACH",
    "models": "HACH DR6000",
    "hiddenCosts": "Sarf materiallari, kalibrlash, servis kontrakti, dasturiy ta'minot litsenziyasi va operator o'qitish xarajatlari.",
    "purchasingStrategy": "Sotib olishdan oldin utilization/ROI hisoblang; ko'pincha core facility, servis yoki contract lab orqali boshlash oqilona.",
    "slug": "koloriimetrik-analizator-suv-sifati"
  },
  {
    "id": "BIO-089",
    "number": 89,
    "name": "Qo'l ushlaydigan spektrometr (Raman)",
    "category": "Analitika",
    "model": "Metrohm Mira M-3",
    "description": "Portativ Raman spektrometr.",
    "purpose": "Maydonda dori, oziq-ovqat qo'shimchalari autentifikatsiyasi",
    "newPrice": "$30,000–50,000",
    "brands": "Metrohm / Thermo Fisher (TruScan)",
    "models": "Metrohm Mira M-3 / Thermo Fisher TruScan RM",
    "hiddenCosts": "Sarf materiallari, kalibrlash, servis kontrakti, dasturiy ta'minot litsenziyasi va operator o'qitish xarajatlari.",
    "purchasingStrategy": "Sotib olishdan oldin utilization/ROI hisoblang; ko'pincha core facility, servis yoki contract lab orqali boshlash oqilona.",
    "slug": "qo-l-ushlaydigan-spektrometr-raman"
  },
  {
    "id": "BIO-090",
    "number": 90,
    "name": "Antibiotik sezuvchanlik tizimi (AST)",
    "category": "Mikrobiologiya",
    "model": "bioMérieux VITEK 2 XL",
    "description": "Mikroorganizmlarni identifikatsiya va antibiotiklarga sezuvchanligini avtomatik aniqlaydi.",
    "purpose": "Klinik mikrobiologiya, infeksiyaga qarshi terapiya tanlash",
    "newPrice": "$10,000–100,000+",
    "brands": "bioMérieux / BD / Bruker",
    "models": "VITEK 2 / Phoenix / MALDI systems",
    "hiddenCosts": "Consumables, calibration, maintenance, spare parts, electricity va operator training.",
    "purchasingStrategy": "Darhol sotib olishdan oldin utilization/ROI hisoblang; ko‘pincha core facility, servis yoki contract lab orqali boshlash oqilona.",
    "slug": "antibiotik-sezuvchanlik-tizimi-ast"
  },
  {
    "id": "BIO-091",
    "number": 91,
    "name": "qPCR uchun digital PCR (ddPCR)",
    "category": "Molekulyar biologiya",
    "model": "Bio-Rad QX200 Droplet Digital PCR",
    "description": "Namunani minglab mikrokapsulacha tomchilarga ajratib absolyut miqdor aniqlaydi.",
    "purpose": "Noyob mutatsiyalar, virus yuki, GMO miqdori aniq hisoblash",
    "newPrice": "$35,000–200,000+",
    "brands": "Bio-Rad / QIAGEN / Stilla",
    "models": "QX200 / QIAcuity / Naica",
    "hiddenCosts": "PCR plates/tubes, optical seals, calibration, reagents, software va servis.",
    "purchasingStrategy": "Darhol sotib olishdan oldin utilization/ROI hisoblang; ko‘pincha core facility, servis yoki contract lab orqali boshlash oqilona.",
    "slug": "qpcr-uchun-digital-pcr-ddpcr"
  },
  {
    "id": "BIO-092",
    "number": 92,
    "name": "CRISPR ish stantsiyasi",
    "category": "Molekulyar biologiya",
    "model": "Integrated DNA Technologies (IDT) gRNA dizayn + Cas9 RNP",
    "description": "CRISPR-Cas9 gen muharriri uchun komponent va protokollar to'plami.",
    "purpose": "Gen knockin/knockout, terapevtik gen muharriri tadqiqotlari",
    "newPrice": "$500–5,000 (loyiha uchun reagent/xizmat narxi)",
    "brands": "Integrated DNA Technologies (IDT) / Synthego",
    "models": "IDT Alt-R CRISPR-Cas9 System",
    "hiddenCosts": "Sarf materiallari, kalibrlash, servis kontrakti, dasturiy ta'minot litsenziyasi va operator o'qitish xarajatlari.",
    "purchasingStrategy": "Sotib olishdan oldin utilization/ROI hisoblang; ko'pincha core facility, servis yoki contract lab orqali boshlash oqilona.",
    "slug": "crispr-ish-stantsiyasi"
  },
  {
    "id": "BIO-093",
    "number": 93,
    "name": "Elektr impulsi generatori (Electroporator)",
    "category": "Molekulyar biologiya",
    "model": "Lonza 4D-Nucleofector X Unit",
    "description": "Nukleofektion texnologiyasi bilan hujayra transfeksiyasini amalga oshiradi.",
    "purpose": "Qiyin transfeksiyaga beriladigan hujayra liniyalari uchun",
    "newPrice": "$20,000–80,000",
    "brands": "Lonza",
    "models": "4D-Nucleofector",
    "hiddenCosts": "Consumables, calibration, maintenance, spare parts, electricity va operator training.",
    "purchasingStrategy": "Darhol sotib olishdan oldin utilization/ROI hisoblang; ko‘pincha core facility, servis yoki contract lab orqali boshlash oqilona.",
    "slug": "elektr-impulsi-generatori-electroporator"
  },
  {
    "id": "BIO-094",
    "number": 94,
    "name": "Hujayra sanaygich (automated)",
    "category": "Hujayra kulturalari",
    "model": "Bio-Rad TC20 Automated Cell Counter",
    "description": "Trypan ko'ki yordamida tirik va o'lik hujayralarni sanaydi.",
    "purpose": "Hujayra kulturasi tizlanishi, tiriklik foizini aniqlash",
    "newPrice": "$5,000–30,000",
    "brands": "Thermo Fisher / Bio-Rad / Nexcelom",
    "models": "Countess 3 / TC20 / Cellometer",
    "hiddenCosts": "Consumables, calibration, maintenance, spare parts, electricity va operator training.",
    "purchasingStrategy": "Darhol sotib olishdan oldin utilization/ROI hisoblang; ko‘pincha core facility, servis yoki contract lab orqali boshlash oqilona.",
    "slug": "hujayra-sanaygich-automated"
  },
  {
    "id": "BIO-095",
    "number": 95,
    "name": "Xromatografik kolonka sistema (Ion exchange)",
    "category": "Analitika",
    "model": "Bio-Rad NGC Chromatography System",
    "description": "Ion almashinuv kolonkalarida oqsillarni tozalaydi.",
    "purpose": "Rekombinant oqsil tozalash, antitela ishlab chiqarish",
    "newPrice": "$20,000–100,000",
    "brands": "Thermo Fisher / Metrohm / Shimadzu",
    "models": "Dionex ICS / IC systems",
    "hiddenCosts": "Columns, solvents, gases, source/ion optics maintenance, calibration va service contract.",
    "purchasingStrategy": "Darhol sotib olishdan oldin utilization/ROI hisoblang; ko‘pincha core facility, servis yoki contract lab orqali boshlash oqilona.",
    "slug": "xromatografik-kolonka-sistema-ion-exchange"
  },
  {
    "id": "BIO-096",
    "number": 96,
    "name": "Avtomatik gradient mikser",
    "category": "Sentrifugatsiya",
    "model": "Gradient Master (BioComp Instruments)",
    "description": "Sukroza yoki fikoll gradientlarini aniq hosil qiladi.",
    "purpose": "Ultrasentrifuga gradientli ajratish uchun tayyorlash",
    "newPrice": "$15,000–30,000",
    "brands": "BioComp Instruments",
    "models": "Gradient Master",
    "hiddenCosts": "Sarf materiallari, kalibrlash, servis kontrakti, dasturiy ta'minot litsenziyasi va operator o'qitish xarajatlari.",
    "purchasingStrategy": "Sotib olishdan oldin utilization/ROI hisoblang; ko'pincha core facility, servis yoki contract lab orqali boshlash oqilona.",
    "slug": "avtomatik-gradient-mikser"
  },
  {
    "id": "BIO-097",
    "number": 97,
    "name": "Preparativ ultrasentrifuga",
    "category": "Sentrifugatsiya",
    "model": "Beckman Coulter Optima XPN-90",
    "description": "90,000 RPM gacha yuqori tezlikdagi sentrifuga.",
    "purpose": "Viruslar, ribosomalar, membrana fraksiyalarini ajratish",
    "newPrice": "$50,000–150,000+",
    "brands": "Beckman Coulter / Thermo Fisher",
    "models": "Optima / Sorvall WX",
    "hiddenCosts": "Consumables, calibration, maintenance, spare parts, electricity va operator training.",
    "purchasingStrategy": "Darhol sotib olishdan oldin utilization/ROI hisoblang; ko‘pincha core facility, servis yoki contract lab orqali boshlash oqilona.",
    "slug": "preparativ-ultrasentrifuga"
  },
  {
    "id": "BIO-098",
    "number": 98,
    "name": "Bioinformatik ish stantsiyasi",
    "category": "Molekulyar biologiya",
    "model": "Lenovo ThinkStation P620 + CLC Genomics Workbench",
    "description": "NGS ma'lumotlari tahlili uchun maxsus yuqori unumdor kompyuter.",
    "purpose": "Genomik ma'lumotlar tahlili, variant chaqirish, transkriptomika",
    "newPrice": "$5,000–15,000 (workstation) + $3,000–10,000/yil (dasturiy litsenziya)",
    "brands": "Lenovo / Dell (workstation) + QIAGEN (CLC)",
    "models": "Lenovo ThinkStation P620 + CLC Genomics Workbench",
    "hiddenCosts": "Sarf materiallari, kalibrlash, servis kontrakti, dasturiy ta'minot litsenziyasi va operator o'qitish xarajatlari.",
    "purchasingStrategy": "Sotib olishdan oldin utilization/ROI hisoblang; ko'pincha core facility, servis yoki contract lab orqali boshlash oqilona.",
    "slug": "bioinformatik-ish-stantsiyasi"
  },
  {
    "id": "BIO-099",
    "number": 99,
    "name": "Ksenobiotik metabolizm tizimi (S9 fraksiya)",
    "category": "Molekulyar biologiya",
    "model": "XenoTech Human Liver S9 Kit",
    "description": "Jigar fermentlari yordamida dori metabolizmi modellanadi.",
    "purpose": "Farmakologik xavfsizlik va toksikologik tadqiqotlar",
    "newPrice": "$500–2,000 (kit narxi)",
    "brands": "XenoTech (Sekisui)",
    "models": "XenoTech Human Liver S9 Kit",
    "hiddenCosts": "Sarf materiallari, kalibrlash, servis kontrakti, dasturiy ta'minot litsenziyasi va operator o'qitish xarajatlari.",
    "purchasingStrategy": "Sotib olishdan oldin utilization/ROI hisoblang; ko'pincha core facility, servis yoki contract lab orqali boshlash oqilona.",
    "slug": "ksenobiotik-metabolizm-tizimi-s9-fraksiya"
  },
  {
    "id": "BIO-100",
    "number": 100,
    "name": "Biofilm o'rganish reaktori",
    "category": "Mikrobiologiya",
    "model": "BioSurface Technologies CDC Biofilm Reactor",
    "description": "Kontrolь sharoitida biofilm hosil bo'lishini o'rganadi.",
    "purpose": "Mikroblarning antibiotik qarshiligini va dezinfeksiyaga chidamliligini tadqiq qilish",
    "newPrice": "$3,000–8,000",
    "brands": "BioSurface Technologies Corporation",
    "models": "BioSurface Technologies CDC Biofilm Reactor",
    "hiddenCosts": "Sarf materiallari, kalibrlash, servis kontrakti, dasturiy ta'minot litsenziyasi va operator o'qitish xarajatlari.",
    "purchasingStrategy": "Sotib olishdan oldin utilization/ROI hisoblang; ko'pincha core facility, servis yoki contract lab orqali boshlash oqilona.",
    "slug": "biofilm-o-rganish-reaktori"
  }
];
