// AUTO-GENERATED by scripts/data/importLearningData.mjs from user-provided sources and canonical equipment records.
// Data policy: model-specific controls, limits and parameters are not invented.

export type OfficialSource = { label: string; url?: string; note: string };

export type LearningContent = {
  number: number; title: string; originalName: string; manufacturer: string; model: string; sourceKind: "learning";
  whatIs: string; whatItDoes: string; learningOutcomes: string; principle: string; mainParts: string; samplePreparation: string; workflow: string;
  resultInterpretation: string; commonMistakes: string; safety: string; maintenance: string; calibrationTroubleshooting: string; practice: string; sources: OfficialSource[];
};

export type PurchaseContent = {
  number: number; title: string; searchName: string; model: string; sourceKind: "purchase";
  price: string; priceEvidence: string; source: string; priceStatus: string; whereToBuy: string; purchaseRule: string;
  availabilityUz: string; importInfo: string; delivery: string; service: string; spares: string; tco: string; redFlags: string; finalStatus: string;
};

export async function loadLearningContent(number: number): Promise<LearningContent | undefined> {
  switch (true) {
    case number >= 1 && number <= 25: {
      const module = await import("./learningDataBlock1");
      return module.default[number];
    }
    case number >= 26 && number <= 50: {
      const module = await import("./learningDataBlock2");
      return module.default[number];
    }
    case number >= 51 && number <= 75: {
      const module = await import("./learningDataBlock3");
      return module.default[number];
    }
    case number >= 76 && number <= 100: {
      const module = await import("./learningDataBlock4");
      return module.default[number];
    }
    default:
      return undefined;
  }
}

export async function loadPurchaseContent(number: number): Promise<PurchaseContent | undefined> {
  switch (true) {
    case number >= 1 && number <= 25: {
      const module = await import("./purchaseDataBlock1");
      return module.default[number];
    }
    case number >= 26 && number <= 50: {
      const module = await import("./purchaseDataBlock2");
      return module.default[number];
    }
    case number >= 51 && number <= 75: {
      const module = await import("./purchaseDataBlock3");
      return module.default[number];
    }
    case number >= 76 && number <= 100: {
      const module = await import("./purchaseDataBlock4");
      return module.default[number];
    }
    default:
      return undefined;
  }
}
