import type { PurchaseContent } from "./learningData";

const purchaseBlock2: Record<number, PurchaseContent> = {
    "26": {
    "number": 26,
    "title": "Vorteks aralashtiruvchi",
    "searchName": "Vorteks aralashtiruvchi",
    "model": "Scientific Industries Vortex Genie 2",
    "sourceKind": "purchase",
    "price": "$5,000–$15,000",
    "priceEvidence": "",
    "source": "",
    "priceStatus": "",
    "whereToBuy": "1. Ishlab chiqaruvchining rasmiy kanali.\n2. Authorized distributor/integrator.\n3. O‘zbekistondagi laboratoriya uskunalari yetkazib beruvchisi.\n4. Used/refurbished — faqat servis tarixi va texnik tekshiruv hujjatlari bilan.",
    "purchaseRule": "",
    "availabilityUz": "Aynan `Scientific Industries Vortex Genie 2` uchun O‘zbekistondagi tayyor ombor mavjudligi ushbu bosqichda qat'iy tasdiqlanmagan. Mahalliy distributor/integratorga model raqami bilan RFQ yuborish kerak.",
    "importInfo": "Agar local stock bo‘lmasa, import qilinadi. RFQda:\n- aniq model/catalog raqami;\n- konfiguratsiya;\n- ishlab chiqarilgan mamlakat;\n- HS code;\n- eksport qadoqlashi;\n- kafolat;\n- sertifikat/hujjatlar;\n- Incoterms\nalohida so‘raladi.",
    "delivery": "Transport narxi o‘lcham, og‘irlik, qadoqlash, kelib chiqish mamlakati va maxsus tashish talablariga bog‘liq. **EXW/FCA/DAP/DDP** shartlaridan qaysi biri ekanini quote'da aniq ko‘rsatish kerak.",
    "service": "- O‘zbekistonda authorized service bormi?\n- Kafolatni kim bajaradi?\n- Preventive maintenance davriyligi qanday?\n- Kalibrlash/verification kerakmi?\n- Servis muhandisi kelish muddati qancha?\n\n**Status:** aynan `Scientific Industries Vortex Genie 2` uchun O‘zbekistondagi servis holati yozma tasdiq talab qiladi.",
    "spares": "Xarid bilan birga modelga mos **wear parts, service kit, sensor/probe/filter/tubing va boshqa sarf qismlar** ro‘yxati, narxi va yetkazish muddati so‘raladi.",
    "tco": "**TCO =** xarid + import/bojxona/QQS + transport + o‘rnatish + kalibrlash + servis + ehtiyot qismlar + sarf materiallari + elektr/suv/gaz + dasturiy litsenziya + operator o‘qitish.\n\n**Hozirgi TCO:** RFQ va yillik foydalanish hajmisiz yakuniy hisoblanmagan.",
    "redFlags": "",
    "finalStatus": "**Narx:** $5,000–$15,000\n**O‘zbekiston:** aynan model bo‘yicha RFQ kerak\n**Import:** local stockga qarab\n**Yetkazib berish:** konfiguratsiyaga bog‘liq\n**Servis:** yozma tasdiq kerak\n**Ehtiyot qismlar:** alohida BOM/quote kerak\n**TCO:** RFQdan keyin hisoblanadi\n\n---"
  },
    "27": {
    "number": 27,
    "title": "Dispenserli avtomatik pipetka",
    "searchName": "Dispenserli avtomatik pipetka",
    "model": "Eppendorf Repeater M4",
    "sourceKind": "purchase",
    "price": "$2,000–$8,000",
    "priceEvidence": "",
    "source": "",
    "priceStatus": "",
    "whereToBuy": "1. Ishlab chiqaruvchining rasmiy kanali.\n2. Authorized distributor/integrator.\n3. O‘zbekistondagi laboratoriya uskunalari yetkazib beruvchisi.\n4. Used/refurbished — faqat servis tarixi va texnik tekshiruv hujjatlari bilan.",
    "purchaseRule": "",
    "availabilityUz": "Aynan `Eppendorf Repeater M4` uchun O‘zbekistondagi tayyor ombor mavjudligi ushbu bosqichda qat'iy tasdiqlanmagan. Mahalliy distributor/integratorga model raqami bilan RFQ yuborish kerak.",
    "importInfo": "Agar local stock bo‘lmasa, import qilinadi. RFQda:\n- aniq model/catalog raqami;\n- konfiguratsiya;\n- ishlab chiqarilgan mamlakat;\n- HS code;\n- eksport qadoqlashi;\n- kafolat;\n- sertifikat/hujjatlar;\n- Incoterms\nalohida so‘raladi.",
    "delivery": "Transport narxi o‘lcham, og‘irlik, qadoqlash, kelib chiqish mamlakati va maxsus tashish talablariga bog‘liq. **EXW/FCA/DAP/DDP** shartlaridan qaysi biri ekanini quote'da aniq ko‘rsatish kerak.",
    "service": "- O‘zbekistonda authorized service bormi?\n- Kafolatni kim bajaradi?\n- Preventive maintenance davriyligi qanday?\n- Kalibrlash/verification kerakmi?\n- Servis muhandisi kelish muddati qancha?\n\n**Status:** aynan `Eppendorf Repeater M4` uchun O‘zbekistondagi servis holati yozma tasdiq talab qiladi.",
    "spares": "Xarid bilan birga modelga mos **wear parts, service kit, sensor/probe/filter/tubing va boshqa sarf qismlar** ro‘yxati, narxi va yetkazish muddati so‘raladi.",
    "tco": "**TCO =** xarid + import/bojxona/QQS + transport + o‘rnatish + kalibrlash + servis + ehtiyot qismlar + sarf materiallari + elektr/suv/gaz + dasturiy litsenziya + operator o‘qitish.\n\n**Hozirgi TCO:** RFQ va yillik foydalanish hajmisiz yakuniy hisoblanmagan.",
    "redFlags": "",
    "finalStatus": "**Narx:** $2,000–$8,000\n**O‘zbekiston:** aynan model bo‘yicha RFQ kerak\n**Import:** local stockga qarab\n**Yetkazib berish:** konfiguratsiyaga bog‘liq\n**Servis:** yozma tasdiq kerak\n**Ehtiyot qismlar:** alohida BOM/quote kerak\n**TCO:** RFQdan keyin hisoblanadi\n\n---"
  },
    "28": {
    "number": 28,
    "title": "Multikanalli pipetka",
    "searchName": "Multikanalli pipetka",
    "model": "Sartorius Picus2 8-kanal 300 µL",
    "sourceKind": "purchase",
    "price": "$10,000–$25,000",
    "priceEvidence": "",
    "source": "",
    "priceStatus": "",
    "whereToBuy": "1. Ishlab chiqaruvchining rasmiy kanali.\n2. Authorized distributor/integrator.\n3. O‘zbekistondagi laboratoriya uskunalari yetkazib beruvchisi.\n4. Used/refurbished — faqat servis tarixi va texnik tekshiruv hujjatlari bilan.",
    "purchaseRule": "",
    "availabilityUz": "Aynan `Sartorius Picus2 8-kanal 300 µL` uchun O‘zbekistondagi tayyor ombor mavjudligi ushbu bosqichda qat'iy tasdiqlanmagan. Mahalliy distributor/integratorga model raqami bilan RFQ yuborish kerak.",
    "importInfo": "Agar local stock bo‘lmasa, import qilinadi. RFQda:\n- aniq model/catalog raqami;\n- konfiguratsiya;\n- ishlab chiqarilgan mamlakat;\n- HS code;\n- eksport qadoqlashi;\n- kafolat;\n- sertifikat/hujjatlar;\n- Incoterms\nalohida so‘raladi.",
    "delivery": "Transport narxi o‘lcham, og‘irlik, qadoqlash, kelib chiqish mamlakati va maxsus tashish talablariga bog‘liq. **EXW/FCA/DAP/DDP** shartlaridan qaysi biri ekanini quote'da aniq ko‘rsatish kerak.",
    "service": "- O‘zbekistonda authorized service bormi?\n- Kafolatni kim bajaradi?\n- Preventive maintenance davriyligi qanday?\n- Kalibrlash/verification kerakmi?\n- Servis muhandisi kelish muddati qancha?\n\n**Status:** aynan `Sartorius Picus2 8-kanal 300 µL` uchun O‘zbekistondagi servis holati yozma tasdiq talab qiladi.",
    "spares": "Xarid bilan birga modelga mos **wear parts, service kit, sensor/probe/filter/tubing va boshqa sarf qismlar** ro‘yxati, narxi va yetkazish muddati so‘raladi.",
    "tco": "**TCO =** xarid + import/bojxona/QQS + transport + o‘rnatish + kalibrlash + servis + ehtiyot qismlar + sarf materiallari + elektr/suv/gaz + dasturiy litsenziya + operator o‘qitish.\n\n**Hozirgi TCO:** RFQ va yillik foydalanish hajmisiz yakuniy hisoblanmagan.",
    "redFlags": "",
    "finalStatus": "**Narx:** $10,000–$25,000\n**O‘zbekiston:** aynan model bo‘yicha RFQ kerak\n**Import:** local stockga qarab\n**Yetkazib berish:** konfiguratsiyaga bog‘liq\n**Servis:** yozma tasdiq kerak\n**Ehtiyot qismlar:** alohida BOM/quote kerak\n**TCO:** RFQdan keyin hisoblanadi\n\n---"
  },
    "29": {
    "number": 29,
    "title": "Termotsikler (qo'lda PCR)",
    "searchName": "Termotsikler (qo'lda PCR)",
    "model": "Applied Biosystems Veriti 96",
    "sourceKind": "purchase",
    "price": "$8,000–$25,000",
    "priceEvidence": "",
    "source": "",
    "priceStatus": "",
    "whereToBuy": "1. Ishlab chiqaruvchining rasmiy kanali.\n2. Authorized distributor/integrator.\n3. O‘zbekistondagi laboratoriya uskunalari yetkazib beruvchisi.\n4. Used/refurbished — faqat servis tarixi va texnik tekshiruv hujjatlari bilan.",
    "purchaseRule": "",
    "availabilityUz": "Aynan `Applied Biosystems Veriti 96` uchun O‘zbekistondagi tayyor ombor mavjudligi ushbu bosqichda qat'iy tasdiqlanmagan. Mahalliy distributor/integratorga model raqami bilan RFQ yuborish kerak.",
    "importInfo": "Agar local stock bo‘lmasa, import qilinadi. RFQda:\n- aniq model/catalog raqami;\n- konfiguratsiya;\n- ishlab chiqarilgan mamlakat;\n- HS code;\n- eksport qadoqlashi;\n- kafolat;\n- sertifikat/hujjatlar;\n- Incoterms\nalohida so‘raladi.",
    "delivery": "Transport narxi o‘lcham, og‘irlik, qadoqlash, kelib chiqish mamlakati va maxsus tashish talablariga bog‘liq. **EXW/FCA/DAP/DDP** shartlaridan qaysi biri ekanini quote'da aniq ko‘rsatish kerak.",
    "service": "- O‘zbekistonda authorized service bormi?\n- Kafolatni kim bajaradi?\n- Preventive maintenance davriyligi qanday?\n- Kalibrlash/verification kerakmi?\n- Servis muhandisi kelish muddati qancha?\n\n**Status:** aynan `Applied Biosystems Veriti 96` uchun O‘zbekistondagi servis holati yozma tasdiq talab qiladi.",
    "spares": "Xarid bilan birga modelga mos **wear parts, service kit, sensor/probe/filter/tubing va boshqa sarf qismlar** ro‘yxati, narxi va yetkazish muddati so‘raladi.",
    "tco": "**TCO =** xarid + import/bojxona/QQS + transport + o‘rnatish + kalibrlash + servis + ehtiyot qismlar + sarf materiallari + elektr/suv/gaz + dasturiy litsenziya + operator o‘qitish.\n\n**Hozirgi TCO:** RFQ va yillik foydalanish hajmisiz yakuniy hisoblanmagan.",
    "redFlags": "",
    "finalStatus": "**Narx:** $8,000–$25,000\n**O‘zbekiston:** aynan model bo‘yicha RFQ kerak\n**Import:** local stockga qarab\n**Yetkazib berish:** konfiguratsiyaga bog‘liq\n**Servis:** yozma tasdiq kerak\n**Ehtiyot qismlar:** alohida BOM/quote kerak\n**TCO:** RFQdan keyin hisoblanadi\n\n---"
  },
    "30": {
    "number": 30,
    "title": "Real-time PCR (qPCR) qurilmasi",
    "searchName": "Real-time PCR (qPCR) qurilmasi",
    "model": "Roche LightCycler 480 II",
    "sourceKind": "purchase",
    "price": "$1,500–$6,000",
    "priceEvidence": "",
    "source": "",
    "priceStatus": "",
    "whereToBuy": "1. Ishlab chiqaruvchining rasmiy kanali.\n2. Authorized distributor/integrator.\n3. O‘zbekistondagi laboratoriya uskunalari yetkazib beruvchisi.\n4. Used/refurbished — faqat servis tarixi va texnik tekshiruv hujjatlari bilan.",
    "purchaseRule": "",
    "availabilityUz": "Aynan `Roche LightCycler 480 II` uchun O‘zbekistondagi tayyor ombor mavjudligi ushbu bosqichda qat'iy tasdiqlanmagan. Mahalliy distributor/integratorga model raqami bilan RFQ yuborish kerak.",
    "importInfo": "Agar local stock bo‘lmasa, import qilinadi. RFQda:\n- aniq model/catalog raqami;\n- konfiguratsiya;\n- ishlab chiqarilgan mamlakat;\n- HS code;\n- eksport qadoqlashi;\n- kafolat;\n- sertifikat/hujjatlar;\n- Incoterms\nalohida so‘raladi.",
    "delivery": "Transport narxi o‘lcham, og‘irlik, qadoqlash, kelib chiqish mamlakati va maxsus tashish talablariga bog‘liq. **EXW/FCA/DAP/DDP** shartlaridan qaysi biri ekanini quote'da aniq ko‘rsatish kerak.",
    "service": "- O‘zbekistonda authorized service bormi?\n- Kafolatni kim bajaradi?\n- Preventive maintenance davriyligi qanday?\n- Kalibrlash/verification kerakmi?\n- Servis muhandisi kelish muddati qancha?\n\n**Status:** aynan `Roche LightCycler 480 II` uchun O‘zbekistondagi servis holati yozma tasdiq talab qiladi.",
    "spares": "Xarid bilan birga modelga mos **wear parts, service kit, sensor/probe/filter/tubing va boshqa sarf qismlar** ro‘yxati, narxi va yetkazish muddati so‘raladi.",
    "tco": "**TCO =** xarid + import/bojxona/QQS + transport + o‘rnatish + kalibrlash + servis + ehtiyot qismlar + sarf materiallari + elektr/suv/gaz + dasturiy litsenziya + operator o‘qitish.\n\n**Hozirgi TCO:** RFQ va yillik foydalanish hajmisiz yakuniy hisoblanmagan.",
    "redFlags": "",
    "finalStatus": "**Narx:** $1,500–$6,000\n**O‘zbekiston:** aynan model bo‘yicha RFQ kerak\n**Import:** local stockga qarab\n**Yetkazib berish:** konfiguratsiyaga bog‘liq\n**Servis:** yozma tasdiq kerak\n**Ehtiyot qismlar:** alohida BOM/quote kerak\n**TCO:** RFQdan keyin hisoblanadi\n\n---"
  },
    "31": {
    "number": 31,
    "title": "Mikrofluidik avtomatlashtirilgan elektroforez / Bioanalyzer",
    "searchName": "Mikrofluidik avtomatlashtirilgan elektroforez / Bioanalyzer",
    "model": "Agilent 2100 Bioanalyzer",
    "sourceKind": "purchase",
    "price": "$1,500–$8,000",
    "priceEvidence": "",
    "source": "",
    "priceStatus": "",
    "whereToBuy": "1. Ishlab chiqaruvchining rasmiy kanali.\n2. Authorized distributor/integrator.\n3. O‘zbekistondagi laboratoriya uskunalari yetkazib beruvchisi.\n4. Used/refurbished — faqat servis tarixi va texnik tekshiruv hujjatlari bilan.",
    "purchaseRule": "",
    "availabilityUz": "Aynan `Agilent 2100 Bioanalyzer` uchun O‘zbekistondagi tayyor ombor mavjudligi ushbu bosqichda qat'iy tasdiqlanmagan. Mahalliy distributor/integratorga model raqami bilan RFQ yuborish kerak.",
    "importInfo": "Agar local stock bo‘lmasa, import qilinadi. RFQda:\n- aniq model/catalog raqami;\n- konfiguratsiya;\n- ishlab chiqarilgan mamlakat;\n- HS code;\n- eksport qadoqlashi;\n- kafolat;\n- sertifikat/hujjatlar;\n- Incoterms\nalohida so‘raladi.",
    "delivery": "Transport narxi o‘lcham, og‘irlik, qadoqlash, kelib chiqish mamlakati va maxsus tashish talablariga bog‘liq. **EXW/FCA/DAP/DDP** shartlaridan qaysi biri ekanini quote'da aniq ko‘rsatish kerak.",
    "service": "- O‘zbekistonda authorized service bormi?\n- Kafolatni kim bajaradi?\n- Preventive maintenance davriyligi qanday?\n- Kalibrlash/verification kerakmi?\n- Servis muhandisi kelish muddati qancha?\n\n**Status:** aynan `Agilent 2100 Bioanalyzer` uchun O‘zbekistondagi servis holati yozma tasdiq talab qiladi.",
    "spares": "Xarid bilan birga modelga mos **wear parts, service kit, sensor/probe/filter/tubing va boshqa sarf qismlar** ro‘yxati, narxi va yetkazish muddati so‘raladi.",
    "tco": "**TCO =** xarid + import/bojxona/QQS + transport + o‘rnatish + kalibrlash + servis + ehtiyot qismlar + sarf materiallari + elektr/suv/gaz + dasturiy litsenziya + operator o‘qitish.\n\n**Hozirgi TCO:** RFQ va yillik foydalanish hajmisiz yakuniy hisoblanmagan.",
    "redFlags": "",
    "finalStatus": "**Narx:** $1,500–$8,000\n**O‘zbekiston:** aynan model bo‘yicha RFQ kerak\n**Import:** local stockga qarab\n**Yetkazib berish:** konfiguratsiyaga bog‘liq\n**Servis:** yozma tasdiq kerak\n**Ehtiyot qismlar:** alohida BOM/quote kerak\n**TCO:** RFQdan keyin hisoblanadi\n\n---"
  },
    "32": {
    "number": 32,
    "title": "Sekvenator (DNA Sequencer)",
    "searchName": "Sekvenator (DNA Sequencer)",
    "model": "Illumina MiSeq",
    "sourceKind": "purchase",
    "price": "$3,000–$12,000",
    "priceEvidence": "",
    "source": "",
    "priceStatus": "",
    "whereToBuy": "1. Ishlab chiqaruvchining rasmiy kanali.\n2. Authorized distributor/integrator.\n3. O‘zbekistondagi laboratoriya uskunalari yetkazib beruvchisi.\n4. Used/refurbished — faqat servis tarixi va texnik tekshiruv hujjatlari bilan.",
    "purchaseRule": "",
    "availabilityUz": "Aynan `Illumina MiSeq` uchun O‘zbekistondagi tayyor ombor mavjudligi ushbu bosqichda qat'iy tasdiqlanmagan. Mahalliy distributor/integratorga model raqami bilan RFQ yuborish kerak.",
    "importInfo": "Agar local stock bo‘lmasa, import qilinadi. RFQda:\n- aniq model/catalog raqami;\n- konfiguratsiya;\n- ishlab chiqarilgan mamlakat;\n- HS code;\n- eksport qadoqlashi;\n- kafolat;\n- sertifikat/hujjatlar;\n- Incoterms\nalohida so‘raladi.",
    "delivery": "Transport narxi o‘lcham, og‘irlik, qadoqlash, kelib chiqish mamlakati va maxsus tashish talablariga bog‘liq. **EXW/FCA/DAP/DDP** shartlaridan qaysi biri ekanini quote'da aniq ko‘rsatish kerak.",
    "service": "- O‘zbekistonda authorized service bormi?\n- Kafolatni kim bajaradi?\n- Preventive maintenance davriyligi qanday?\n- Kalibrlash/verification kerakmi?\n- Servis muhandisi kelish muddati qancha?\n\n**Status:** aynan `Illumina MiSeq` uchun O‘zbekistondagi servis holati yozma tasdiq talab qiladi.",
    "spares": "Xarid bilan birga modelga mos **wear parts, service kit, sensor/probe/filter/tubing va boshqa sarf qismlar** ro‘yxati, narxi va yetkazish muddati so‘raladi.",
    "tco": "**TCO =** xarid + import/bojxona/QQS + transport + o‘rnatish + kalibrlash + servis + ehtiyot qismlar + sarf materiallari + elektr/suv/gaz + dasturiy litsenziya + operator o‘qitish.\n\n**Hozirgi TCO:** RFQ va yillik foydalanish hajmisiz yakuniy hisoblanmagan.",
    "redFlags": "",
    "finalStatus": "**Narx:** $3,000–$12,000\n**O‘zbekiston:** aynan model bo‘yicha RFQ kerak\n**Import:** local stockga qarab\n**Yetkazib berish:** konfiguratsiyaga bog‘liq\n**Servis:** yozma tasdiq kerak\n**Ehtiyot qismlar:** alohida BOM/quote kerak\n**TCO:** RFQdan keyin hisoblanadi\n\n---"
  },
    "33": {
    "number": 33,
    "title": "Elektrochemiluminessent immunoassay analizatori",
    "searchName": "Elektrochemiluminessent immunoassay analizatori",
    "model": "Roche Cobas e 801",
    "sourceKind": "purchase",
    "price": "$2,000–$10,000",
    "priceEvidence": "",
    "source": "",
    "priceStatus": "",
    "whereToBuy": "1. Ishlab chiqaruvchining rasmiy kanali.\n2. Authorized distributor/integrator.\n3. O‘zbekistondagi laboratoriya uskunalari yetkazib beruvchisi.\n4. Used/refurbished — faqat servis tarixi va texnik tekshiruv hujjatlari bilan.",
    "purchaseRule": "",
    "availabilityUz": "Aynan `Roche Cobas e 801` uchun O‘zbekistondagi tayyor ombor mavjudligi ushbu bosqichda qat'iy tasdiqlanmagan. Mahalliy distributor/integratorga model raqami bilan RFQ yuborish kerak.",
    "importInfo": "Agar local stock bo‘lmasa, import qilinadi. RFQda:\n- aniq model/catalog raqami;\n- konfiguratsiya;\n- ishlab chiqarilgan mamlakat;\n- HS code;\n- eksport qadoqlashi;\n- kafolat;\n- sertifikat/hujjatlar;\n- Incoterms\nalohida so‘raladi.",
    "delivery": "Transport narxi o‘lcham, og‘irlik, qadoqlash, kelib chiqish mamlakati va maxsus tashish talablariga bog‘liq. **EXW/FCA/DAP/DDP** shartlaridan qaysi biri ekanini quote'da aniq ko‘rsatish kerak.",
    "service": "- O‘zbekistonda authorized service bormi?\n- Kafolatni kim bajaradi?\n- Preventive maintenance davriyligi qanday?\n- Kalibrlash/verification kerakmi?\n- Servis muhandisi kelish muddati qancha?\n\n**Status:** aynan `Roche Cobas e 801` uchun O‘zbekistondagi servis holati yozma tasdiq talab qiladi.",
    "spares": "Xarid bilan birga modelga mos **wear parts, service kit, sensor/probe/filter/tubing va boshqa sarf qismlar** ro‘yxati, narxi va yetkazish muddati so‘raladi.",
    "tco": "**TCO =** xarid + import/bojxona/QQS + transport + o‘rnatish + kalibrlash + servis + ehtiyot qismlar + sarf materiallari + elektr/suv/gaz + dasturiy litsenziya + operator o‘qitish.\n\n**Hozirgi TCO:** RFQ va yillik foydalanish hajmisiz yakuniy hisoblanmagan.",
    "redFlags": "",
    "finalStatus": "**Narx:** $2,000–$10,000\n**O‘zbekiston:** aynan model bo‘yicha RFQ kerak\n**Import:** local stockga qarab\n**Yetkazib berish:** konfiguratsiyaga bog‘liq\n**Servis:** yozma tasdiq kerak\n**Ehtiyot qismlar:** alohida BOM/quote kerak\n**TCO:** RFQdan keyin hisoblanadi\n\n---"
  },
    "34": {
    "number": 34,
    "title": "Atom-absorbsion spektrometr (AAS)",
    "searchName": "Atom-absorbsion spektrometr (AAS)",
    "model": "PerkinElmer PinAAcle 900T",
    "sourceKind": "purchase",
    "price": "$1,500–$8,000",
    "priceEvidence": "",
    "source": "",
    "priceStatus": "",
    "whereToBuy": "1. Ishlab chiqaruvchining rasmiy kanali.\n2. Authorized distributor/integrator.\n3. O‘zbekistondagi laboratoriya uskunalari yetkazib beruvchisi.\n4. Used/refurbished — faqat servis tarixi va texnik tekshiruv hujjatlari bilan.",
    "purchaseRule": "",
    "availabilityUz": "Aynan `PerkinElmer PinAAcle 900T` uchun O‘zbekistondagi tayyor ombor mavjudligi ushbu bosqichda qat'iy tasdiqlanmagan. Mahalliy distributor/integratorga model raqami bilan RFQ yuborish kerak.",
    "importInfo": "Agar local stock bo‘lmasa, import qilinadi. RFQda:\n- aniq model/catalog raqami;\n- konfiguratsiya;\n- ishlab chiqarilgan mamlakat;\n- HS code;\n- eksport qadoqlashi;\n- kafolat;\n- sertifikat/hujjatlar;\n- Incoterms\nalohida so‘raladi.",
    "delivery": "Transport narxi o‘lcham, og‘irlik, qadoqlash, kelib chiqish mamlakati va maxsus tashish talablariga bog‘liq. **EXW/FCA/DAP/DDP** shartlaridan qaysi biri ekanini quote'da aniq ko‘rsatish kerak.",
    "service": "- O‘zbekistonda authorized service bormi?\n- Kafolatni kim bajaradi?\n- Preventive maintenance davriyligi qanday?\n- Kalibrlash/verification kerakmi?\n- Servis muhandisi kelish muddati qancha?\n\n**Status:** aynan `PerkinElmer PinAAcle 900T` uchun O‘zbekistondagi servis holati yozma tasdiq talab qiladi.",
    "spares": "Xarid bilan birga modelga mos **wear parts, service kit, sensor/probe/filter/tubing va boshqa sarf qismlar** ro‘yxati, narxi va yetkazish muddati so‘raladi.",
    "tco": "**TCO =** xarid + import/bojxona/QQS + transport + o‘rnatish + kalibrlash + servis + ehtiyot qismlar + sarf materiallari + elektr/suv/gaz + dasturiy litsenziya + operator o‘qitish.\n\n**Hozirgi TCO:** RFQ va yillik foydalanish hajmisiz yakuniy hisoblanmagan.",
    "redFlags": "",
    "finalStatus": "**Narx:** $1,500–$8,000\n**O‘zbekiston:** aynan model bo‘yicha RFQ kerak\n**Import:** local stockga qarab\n**Yetkazib berish:** konfiguratsiyaga bog‘liq\n**Servis:** yozma tasdiq kerak\n**Ehtiyot qismlar:** alohida BOM/quote kerak\n**TCO:** RFQdan keyin hisoblanadi\n\n---"
  },
    "35": {
    "number": 35,
    "title": "ICP-MS (Induksion plazma spektrometr)",
    "searchName": "ICP-MS (Induksion plazma spektrometr)",
    "model": "Agilent 7900 ICP-MS",
    "sourceKind": "purchase",
    "price": "$2,000–$12,000",
    "priceEvidence": "",
    "source": "",
    "priceStatus": "",
    "whereToBuy": "1. Ishlab chiqaruvchining rasmiy kanali.\n2. Authorized distributor/integrator.\n3. O‘zbekistondagi laboratoriya uskunalari yetkazib beruvchisi.\n4. Used/refurbished — faqat servis tarixi va texnik tekshiruv hujjatlari bilan.",
    "purchaseRule": "",
    "availabilityUz": "Aynan `Agilent 7900 ICP-MS` uchun O‘zbekistondagi tayyor ombor mavjudligi ushbu bosqichda qat'iy tasdiqlanmagan. Mahalliy distributor/integratorga model raqami bilan RFQ yuborish kerak.",
    "importInfo": "Agar local stock bo‘lmasa, import qilinadi. RFQda:\n- aniq model/catalog raqami;\n- konfiguratsiya;\n- ishlab chiqarilgan mamlakat;\n- HS code;\n- eksport qadoqlashi;\n- kafolat;\n- sertifikat/hujjatlar;\n- Incoterms\nalohida so‘raladi.",
    "delivery": "Transport narxi o‘lcham, og‘irlik, qadoqlash, kelib chiqish mamlakati va maxsus tashish talablariga bog‘liq. **EXW/FCA/DAP/DDP** shartlaridan qaysi biri ekanini quote'da aniq ko‘rsatish kerak.",
    "service": "- O‘zbekistonda authorized service bormi?\n- Kafolatni kim bajaradi?\n- Preventive maintenance davriyligi qanday?\n- Kalibrlash/verification kerakmi?\n- Servis muhandisi kelish muddati qancha?\n\n**Status:** aynan `Agilent 7900 ICP-MS` uchun O‘zbekistondagi servis holati yozma tasdiq talab qiladi.",
    "spares": "Xarid bilan birga modelga mos **wear parts, service kit, sensor/probe/filter/tubing va boshqa sarf qismlar** ro‘yxati, narxi va yetkazish muddati so‘raladi.",
    "tco": "**TCO =** xarid + import/bojxona/QQS + transport + o‘rnatish + kalibrlash + servis + ehtiyot qismlar + sarf materiallari + elektr/suv/gaz + dasturiy litsenziya + operator o‘qitish.\n\n**Hozirgi TCO:** RFQ va yillik foydalanish hajmisiz yakuniy hisoblanmagan.",
    "redFlags": "",
    "finalStatus": "**Narx:** $2,000–$12,000\n**O‘zbekiston:** aynan model bo‘yicha RFQ kerak\n**Import:** local stockga qarab\n**Yetkazib berish:** konfiguratsiyaga bog‘liq\n**Servis:** yozma tasdiq kerak\n**Ehtiyot qismlar:** alohida BOM/quote kerak\n**TCO:** RFQdan keyin hisoblanadi\n\n---"
  },
    "36": {
    "number": 36,
    "title": "Titrator (Karl Fischer)",
    "searchName": "Titrator (Karl Fischer)",
    "model": "Mettler Toledo V30S",
    "sourceKind": "purchase",
    "price": "$5,000–$30,000",
    "priceEvidence": "",
    "source": "",
    "priceStatus": "",
    "whereToBuy": "1. Ishlab chiqaruvchining rasmiy kanali.\n2. Authorized distributor/integrator.\n3. O‘zbekistondagi laboratoriya uskunalari yetkazib beruvchisi.\n4. Used/refurbished — faqat servis tarixi va texnik tekshiruv hujjatlari bilan.",
    "purchaseRule": "",
    "availabilityUz": "Aynan `Mettler Toledo V30S` uchun O‘zbekistondagi tayyor ombor mavjudligi ushbu bosqichda qat'iy tasdiqlanmagan. Mahalliy distributor/integratorga model raqami bilan RFQ yuborish kerak.",
    "importInfo": "Agar local stock bo‘lmasa, import qilinadi. RFQda:\n- aniq model/catalog raqami;\n- konfiguratsiya;\n- ishlab chiqarilgan mamlakat;\n- HS code;\n- eksport qadoqlashi;\n- kafolat;\n- sertifikat/hujjatlar;\n- Incoterms\nalohida so‘raladi.",
    "delivery": "Transport narxi o‘lcham, og‘irlik, qadoqlash, kelib chiqish mamlakati va maxsus tashish talablariga bog‘liq. **EXW/FCA/DAP/DDP** shartlaridan qaysi biri ekanini quote'da aniq ko‘rsatish kerak.",
    "service": "- O‘zbekistonda authorized service bormi?\n- Kafolatni kim bajaradi?\n- Preventive maintenance davriyligi qanday?\n- Kalibrlash/verification kerakmi?\n- Servis muhandisi kelish muddati qancha?\n\n**Status:** aynan `Mettler Toledo V30S` uchun O‘zbekistondagi servis holati yozma tasdiq talab qiladi.",
    "spares": "Xarid bilan birga modelga mos **wear parts, service kit, sensor/probe/filter/tubing va boshqa sarf qismlar** ro‘yxati, narxi va yetkazish muddati so‘raladi.",
    "tco": "**TCO =** xarid + import/bojxona/QQS + transport + o‘rnatish + kalibrlash + servis + ehtiyot qismlar + sarf materiallari + elektr/suv/gaz + dasturiy litsenziya + operator o‘qitish.\n\n**Hozirgi TCO:** RFQ va yillik foydalanish hajmisiz yakuniy hisoblanmagan.",
    "redFlags": "",
    "finalStatus": "**Narx:** $5,000–$30,000\n**O‘zbekiston:** aynan model bo‘yicha RFQ kerak\n**Import:** local stockga qarab\n**Yetkazib berish:** konfiguratsiyaga bog‘liq\n**Servis:** yozma tasdiq kerak\n**Ehtiyot qismlar:** alohida BOM/quote kerak\n**TCO:** RFQdan keyin hisoblanadi\n\n---"
  },
    "37": {
    "number": 37,
    "title": "Viskozimetr",
    "searchName": "Viskozimetr",
    "model": "Brookfield DV2T",
    "sourceKind": "purchase",
    "price": "$10,000–$60,000+",
    "priceEvidence": "",
    "source": "",
    "priceStatus": "",
    "whereToBuy": "1. Ishlab chiqaruvchining rasmiy kanali.\n2. Authorized distributor/integrator.\n3. O‘zbekistondagi laboratoriya uskunalari yetkazib beruvchisi.\n4. Used/refurbished — faqat servis tarixi va texnik tekshiruv hujjatlari bilan.",
    "purchaseRule": "",
    "availabilityUz": "Aynan `Brookfield DV2T` uchun O‘zbekistondagi tayyor ombor mavjudligi ushbu bosqichda qat'iy tasdiqlanmagan. Mahalliy distributor/integratorga model raqami bilan RFQ yuborish kerak.",
    "importInfo": "Agar local stock bo‘lmasa, import qilinadi. RFQda:\n- aniq model/catalog raqami;\n- konfiguratsiya;\n- ishlab chiqarilgan mamlakat;\n- HS code;\n- eksport qadoqlashi;\n- kafolat;\n- sertifikat/hujjatlar;\n- Incoterms\nalohida so‘raladi.",
    "delivery": "Transport narxi o‘lcham, og‘irlik, qadoqlash, kelib chiqish mamlakati va maxsus tashish talablariga bog‘liq. **EXW/FCA/DAP/DDP** shartlaridan qaysi biri ekanini quote'da aniq ko‘rsatish kerak.",
    "service": "- O‘zbekistonda authorized service bormi?\n- Kafolatni kim bajaradi?\n- Preventive maintenance davriyligi qanday?\n- Kalibrlash/verification kerakmi?\n- Servis muhandisi kelish muddati qancha?\n\n**Status:** aynan `Brookfield DV2T` uchun O‘zbekistondagi servis holati yozma tasdiq talab qiladi.",
    "spares": "Xarid bilan birga modelga mos **wear parts, service kit, sensor/probe/filter/tubing va boshqa sarf qismlar** ro‘yxati, narxi va yetkazish muddati so‘raladi.",
    "tco": "**TCO =** xarid + import/bojxona/QQS + transport + o‘rnatish + kalibrlash + servis + ehtiyot qismlar + sarf materiallari + elektr/suv/gaz + dasturiy litsenziya + operator o‘qitish.\n\n**Hozirgi TCO:** RFQ va yillik foydalanish hajmisiz yakuniy hisoblanmagan.",
    "redFlags": "",
    "finalStatus": "**Narx:** $10,000–$60,000+\n**O‘zbekiston:** aynan model bo‘yicha RFQ kerak\n**Import:** local stockga qarab\n**Yetkazib berish:** konfiguratsiyaga bog‘liq\n**Servis:** yozma tasdiq kerak\n**Ehtiyot qismlar:** alohida BOM/quote kerak\n**TCO:** RFQdan keyin hisoblanadi\n\n---"
  },
    "38": {
    "number": 38,
    "title": "Refraktometr (raqamli)",
    "searchName": "Refraktometr (raqamli)",
    "model": "MISCO Palm Abbe Digital",
    "sourceKind": "purchase",
    "price": "$5,000–$20,000",
    "priceEvidence": "",
    "source": "",
    "priceStatus": "",
    "whereToBuy": "1. Ishlab chiqaruvchining rasmiy kanali.\n2. Authorized distributor/integrator.\n3. O‘zbekistondagi laboratoriya uskunalari yetkazib beruvchisi.\n4. Used/refurbished — faqat servis tarixi va texnik tekshiruv hujjatlari bilan.",
    "purchaseRule": "",
    "availabilityUz": "Aynan `MISCO Palm Abbe Digital` uchun O‘zbekistondagi tayyor ombor mavjudligi ushbu bosqichda qat'iy tasdiqlanmagan. Mahalliy distributor/integratorga model raqami bilan RFQ yuborish kerak.",
    "importInfo": "Agar local stock bo‘lmasa, import qilinadi. RFQda:\n- aniq model/catalog raqami;\n- konfiguratsiya;\n- ishlab chiqarilgan mamlakat;\n- HS code;\n- eksport qadoqlashi;\n- kafolat;\n- sertifikat/hujjatlar;\n- Incoterms\nalohida so‘raladi.",
    "delivery": "Transport narxi o‘lcham, og‘irlik, qadoqlash, kelib chiqish mamlakati va maxsus tashish talablariga bog‘liq. **EXW/FCA/DAP/DDP** shartlaridan qaysi biri ekanini quote'da aniq ko‘rsatish kerak.",
    "service": "- O‘zbekistonda authorized service bormi?\n- Kafolatni kim bajaradi?\n- Preventive maintenance davriyligi qanday?\n- Kalibrlash/verification kerakmi?\n- Servis muhandisi kelish muddati qancha?\n\n**Status:** aynan `MISCO Palm Abbe Digital` uchun O‘zbekistondagi servis holati yozma tasdiq talab qiladi.",
    "spares": "Xarid bilan birga modelga mos **wear parts, service kit, sensor/probe/filter/tubing va boshqa sarf qismlar** ro‘yxati, narxi va yetkazish muddati so‘raladi.",
    "tco": "**TCO =** xarid + import/bojxona/QQS + transport + o‘rnatish + kalibrlash + servis + ehtiyot qismlar + sarf materiallari + elektr/suv/gaz + dasturiy litsenziya + operator o‘qitish.\n\n**Hozirgi TCO:** RFQ va yillik foydalanish hajmisiz yakuniy hisoblanmagan.",
    "redFlags": "",
    "finalStatus": "**Narx:** $5,000–$20,000\n**O‘zbekiston:** aynan model bo‘yicha RFQ kerak\n**Import:** local stockga qarab\n**Yetkazib berish:** konfiguratsiyaga bog‘liq\n**Servis:** yozma tasdiq kerak\n**Ehtiyot qismlar:** alohida BOM/quote kerak\n**TCO:** RFQdan keyin hisoblanadi\n\n---"
  },
    "39": {
    "number": 39,
    "title": "Lyuminestsent mikroskop",
    "searchName": "Lyuminestsent mikroskop",
    "model": "Nikon Eclipse Ti2-E",
    "sourceKind": "purchase",
    "price": "$1,000–$7,000",
    "priceEvidence": "",
    "source": "",
    "priceStatus": "",
    "whereToBuy": "1. Ishlab chiqaruvchining rasmiy kanali.\n2. Authorized distributor/integrator.\n3. O‘zbekistondagi laboratoriya uskunalari yetkazib beruvchisi.\n4. Used/refurbished — faqat servis tarixi va texnik tekshiruv hujjatlari bilan.",
    "purchaseRule": "",
    "availabilityUz": "Aynan `Nikon Eclipse Ti2-E` uchun O‘zbekistondagi tayyor ombor mavjudligi ushbu bosqichda qat'iy tasdiqlanmagan. Mahalliy distributor/integratorga model raqami bilan RFQ yuborish kerak.",
    "importInfo": "Agar local stock bo‘lmasa, import qilinadi. RFQda:\n- aniq model/catalog raqami;\n- konfiguratsiya;\n- ishlab chiqarilgan mamlakat;\n- HS code;\n- eksport qadoqlashi;\n- kafolat;\n- sertifikat/hujjatlar;\n- Incoterms\nalohida so‘raladi.",
    "delivery": "Transport narxi o‘lcham, og‘irlik, qadoqlash, kelib chiqish mamlakati va maxsus tashish talablariga bog‘liq. **EXW/FCA/DAP/DDP** shartlaridan qaysi biri ekanini quote'da aniq ko‘rsatish kerak.",
    "service": "- O‘zbekistonda authorized service bormi?\n- Kafolatni kim bajaradi?\n- Preventive maintenance davriyligi qanday?\n- Kalibrlash/verification kerakmi?\n- Servis muhandisi kelish muddati qancha?\n\n**Status:** aynan `Nikon Eclipse Ti2-E` uchun O‘zbekistondagi servis holati yozma tasdiq talab qiladi.",
    "spares": "Xarid bilan birga modelga mos **wear parts, service kit, sensor/probe/filter/tubing va boshqa sarf qismlar** ro‘yxati, narxi va yetkazish muddati so‘raladi.",
    "tco": "**TCO =** xarid + import/bojxona/QQS + transport + o‘rnatish + kalibrlash + servis + ehtiyot qismlar + sarf materiallari + elektr/suv/gaz + dasturiy litsenziya + operator o‘qitish.\n\n**Hozirgi TCO:** RFQ va yillik foydalanish hajmisiz yakuniy hisoblanmagan.",
    "redFlags": "",
    "finalStatus": "**Narx:** $1,000–$7,000\n**O‘zbekiston:** aynan model bo‘yicha RFQ kerak\n**Import:** local stockga qarab\n**Yetkazib berish:** konfiguratsiyaga bog‘liq\n**Servis:** yozma tasdiq kerak\n**Ehtiyot qismlar:** alohida BOM/quote kerak\n**TCO:** RFQdan keyin hisoblanadi\n\n---"
  },
    "40": {
    "number": 40,
    "title": "Elektron mikroskop (SEM)",
    "searchName": "Elektron mikroskop (SEM)",
    "model": "JEOL JSM-IT800",
    "sourceKind": "purchase",
    "price": "$2,000–$15,000",
    "priceEvidence": "",
    "source": "",
    "priceStatus": "",
    "whereToBuy": "1. Ishlab chiqaruvchining rasmiy kanali.\n2. Authorized distributor/integrator.\n3. O‘zbekistondagi laboratoriya uskunalari yetkazib beruvchisi.\n4. Used/refurbished — faqat servis tarixi va texnik tekshiruv hujjatlari bilan.",
    "purchaseRule": "",
    "availabilityUz": "Aynan `JEOL JSM-IT800` uchun O‘zbekistondagi tayyor ombor mavjudligi ushbu bosqichda qat'iy tasdiqlanmagan. Mahalliy distributor/integratorga model raqami bilan RFQ yuborish kerak.",
    "importInfo": "Agar local stock bo‘lmasa, import qilinadi. RFQda:\n- aniq model/catalog raqami;\n- konfiguratsiya;\n- ishlab chiqarilgan mamlakat;\n- HS code;\n- eksport qadoqlashi;\n- kafolat;\n- sertifikat/hujjatlar;\n- Incoterms\nalohida so‘raladi.",
    "delivery": "Transport narxi o‘lcham, og‘irlik, qadoqlash, kelib chiqish mamlakati va maxsus tashish talablariga bog‘liq. **EXW/FCA/DAP/DDP** shartlaridan qaysi biri ekanini quote'da aniq ko‘rsatish kerak.",
    "service": "- O‘zbekistonda authorized service bormi?\n- Kafolatni kim bajaradi?\n- Preventive maintenance davriyligi qanday?\n- Kalibrlash/verification kerakmi?\n- Servis muhandisi kelish muddati qancha?\n\n**Status:** aynan `JEOL JSM-IT800` uchun O‘zbekistondagi servis holati yozma tasdiq talab qiladi.",
    "spares": "Xarid bilan birga modelga mos **wear parts, service kit, sensor/probe/filter/tubing va boshqa sarf qismlar** ro‘yxati, narxi va yetkazish muddati so‘raladi.",
    "tco": "**TCO =** xarid + import/bojxona/QQS + transport + o‘rnatish + kalibrlash + servis + ehtiyot qismlar + sarf materiallari + elektr/suv/gaz + dasturiy litsenziya + operator o‘qitish.\n\n**Hozirgi TCO:** RFQ va yillik foydalanish hajmisiz yakuniy hisoblanmagan.",
    "redFlags": "",
    "finalStatus": "**Narx:** $2,000–$15,000\n**O‘zbekiston:** aynan model bo‘yicha RFQ kerak\n**Import:** local stockga qarab\n**Yetkazib berish:** konfiguratsiyaga bog‘liq\n**Servis:** yozma tasdiq kerak\n**Ehtiyot qismlar:** alohida BOM/quote kerak\n**TCO:** RFQdan keyin hisoblanadi\n\n---"
  },
    "41": {
    "number": 41,
    "title": "Steril filtrlash tizimi",
    "searchName": "Steril filtrlash tizimi",
    "model": "Millipore Stericup Quick Release 0.22µm",
    "sourceKind": "purchase",
    "price": "$1,500–$8,000",
    "priceEvidence": "",
    "source": "",
    "priceStatus": "",
    "whereToBuy": "1. Ishlab chiqaruvchining rasmiy kanali.\n2. Authorized distributor/integrator.\n3. O‘zbekistondagi laboratoriya uskunalari yetkazib beruvchisi.\n4. Used/refurbished — faqat servis tarixi va texnik tekshiruv hujjatlari bilan.",
    "purchaseRule": "",
    "availabilityUz": "Aynan `Millipore Stericup Quick Release 0.22µm` uchun O‘zbekistondagi tayyor ombor mavjudligi ushbu bosqichda qat'iy tasdiqlanmagan. Mahalliy distributor/integratorga model raqami bilan RFQ yuborish kerak.",
    "importInfo": "Agar local stock bo‘lmasa, import qilinadi. RFQda:\n- aniq model/catalog raqami;\n- konfiguratsiya;\n- ishlab chiqarilgan mamlakat;\n- HS code;\n- eksport qadoqlashi;\n- kafolat;\n- sertifikat/hujjatlar;\n- Incoterms\nalohida so‘raladi.",
    "delivery": "Transport narxi o‘lcham, og‘irlik, qadoqlash, kelib chiqish mamlakati va maxsus tashish talablariga bog‘liq. **EXW/FCA/DAP/DDP** shartlaridan qaysi biri ekanini quote'da aniq ko‘rsatish kerak.",
    "service": "- O‘zbekistonda authorized service bormi?\n- Kafolatni kim bajaradi?\n- Preventive maintenance davriyligi qanday?\n- Kalibrlash/verification kerakmi?\n- Servis muhandisi kelish muddati qancha?\n\n**Status:** aynan `Millipore Stericup Quick Release 0.22µm` uchun O‘zbekistondagi servis holati yozma tasdiq talab qiladi.",
    "spares": "Xarid bilan birga modelga mos **wear parts, service kit, sensor/probe/filter/tubing va boshqa sarf qismlar** ro‘yxati, narxi va yetkazish muddati so‘raladi.",
    "tco": "**TCO =** xarid + import/bojxona/QQS + transport + o‘rnatish + kalibrlash + servis + ehtiyot qismlar + sarf materiallari + elektr/suv/gaz + dasturiy litsenziya + operator o‘qitish.\n\n**Hozirgi TCO:** RFQ va yillik foydalanish hajmisiz yakuniy hisoblanmagan.",
    "redFlags": "",
    "finalStatus": "**Narx:** $1,500–$8,000\n**O‘zbekiston:** aynan model bo‘yicha RFQ kerak\n**Import:** local stockga qarab\n**Yetkazib berish:** konfiguratsiyaga bog‘liq\n**Servis:** yozma tasdiq kerak\n**Ehtiyot qismlar:** alohida BOM/quote kerak\n**TCO:** RFQdan keyin hisoblanadi\n\n---"
  },
    "42": {
    "number": 42,
    "title": "Inkubator shaker (orbital)",
    "searchName": "Inkubator shaker (orbital)",
    "model": "Eppendorf Innova 44R",
    "sourceKind": "purchase",
    "price": "$2,000–$10,000",
    "priceEvidence": "",
    "source": "",
    "priceStatus": "",
    "whereToBuy": "1. Ishlab chiqaruvchining rasmiy kanali.\n2. Authorized distributor/integrator.\n3. O‘zbekistondagi laboratoriya uskunalari yetkazib beruvchisi.\n4. Used/refurbished — faqat servis tarixi va texnik tekshiruv hujjatlari bilan.",
    "purchaseRule": "",
    "availabilityUz": "Aynan `Eppendorf Innova 44R` uchun O‘zbekistondagi tayyor ombor mavjudligi ushbu bosqichda qat'iy tasdiqlanmagan. Mahalliy distributor/integratorga model raqami bilan RFQ yuborish kerak.",
    "importInfo": "Agar local stock bo‘lmasa, import qilinadi. RFQda:\n- aniq model/catalog raqami;\n- konfiguratsiya;\n- ishlab chiqarilgan mamlakat;\n- HS code;\n- eksport qadoqlashi;\n- kafolat;\n- sertifikat/hujjatlar;\n- Incoterms\nalohida so‘raladi.",
    "delivery": "Transport narxi o‘lcham, og‘irlik, qadoqlash, kelib chiqish mamlakati va maxsus tashish talablariga bog‘liq. **EXW/FCA/DAP/DDP** shartlaridan qaysi biri ekanini quote'da aniq ko‘rsatish kerak.",
    "service": "- O‘zbekistonda authorized service bormi?\n- Kafolatni kim bajaradi?\n- Preventive maintenance davriyligi qanday?\n- Kalibrlash/verification kerakmi?\n- Servis muhandisi kelish muddati qancha?\n\n**Status:** aynan `Eppendorf Innova 44R` uchun O‘zbekistondagi servis holati yozma tasdiq talab qiladi.",
    "spares": "Xarid bilan birga modelga mos **wear parts, service kit, sensor/probe/filter/tubing va boshqa sarf qismlar** ro‘yxati, narxi va yetkazish muddati so‘raladi.",
    "tco": "**TCO =** xarid + import/bojxona/QQS + transport + o‘rnatish + kalibrlash + servis + ehtiyot qismlar + sarf materiallari + elektr/suv/gaz + dasturiy litsenziya + operator o‘qitish.\n\n**Hozirgi TCO:** RFQ va yillik foydalanish hajmisiz yakuniy hisoblanmagan.",
    "redFlags": "",
    "finalStatus": "**Narx:** $2,000–$10,000\n**O‘zbekiston:** aynan model bo‘yicha RFQ kerak\n**Import:** local stockga qarab\n**Yetkazib berish:** konfiguratsiyaga bog‘liq\n**Servis:** yozma tasdiq kerak\n**Ehtiyot qismlar:** alohida BOM/quote kerak\n**TCO:** RFQdan keyin hisoblanadi\n\n---"
  },
    "43": {
    "number": 43,
    "title": "Bioreaktор (fermentor)",
    "searchName": "Bioreaktор (fermentor)",
    "model": "Sartorius BIOSTAT B",
    "sourceKind": "purchase",
    "price": "$500–$5,000",
    "priceEvidence": "",
    "source": "",
    "priceStatus": "",
    "whereToBuy": "1. Ishlab chiqaruvchining rasmiy kanali.\n2. Authorized distributor/integrator.\n3. O‘zbekistondagi laboratoriya uskunalari yetkazib beruvchisi.\n4. Used/refurbished — faqat servis tarixi va texnik tekshiruv hujjatlari bilan.",
    "purchaseRule": "",
    "availabilityUz": "Aynan `Sartorius BIOSTAT B` uchun O‘zbekistondagi tayyor ombor mavjudligi ushbu bosqichda qat'iy tasdiqlanmagan. Mahalliy distributor/integratorga model raqami bilan RFQ yuborish kerak.",
    "importInfo": "Agar local stock bo‘lmasa, import qilinadi. RFQda:\n- aniq model/catalog raqami;\n- konfiguratsiya;\n- ishlab chiqarilgan mamlakat;\n- HS code;\n- eksport qadoqlashi;\n- kafolat;\n- sertifikat/hujjatlar;\n- Incoterms\nalohida so‘raladi.",
    "delivery": "Transport narxi o‘lcham, og‘irlik, qadoqlash, kelib chiqish mamlakati va maxsus tashish talablariga bog‘liq. **EXW/FCA/DAP/DDP** shartlaridan qaysi biri ekanini quote'da aniq ko‘rsatish kerak.",
    "service": "- O‘zbekistonda authorized service bormi?\n- Kafolatni kim bajaradi?\n- Preventive maintenance davriyligi qanday?\n- Kalibrlash/verification kerakmi?\n- Servis muhandisi kelish muddati qancha?\n\n**Status:** aynan `Sartorius BIOSTAT B` uchun O‘zbekistondagi servis holati yozma tasdiq talab qiladi.",
    "spares": "Xarid bilan birga modelga mos **wear parts, service kit, sensor/probe/filter/tubing va boshqa sarf qismlar** ro‘yxati, narxi va yetkazish muddati so‘raladi.",
    "tco": "**TCO =** xarid + import/bojxona/QQS + transport + o‘rnatish + kalibrlash + servis + ehtiyot qismlar + sarf materiallari + elektr/suv/gaz + dasturiy litsenziya + operator o‘qitish.\n\n**Hozirgi TCO:** RFQ va yillik foydalanish hajmisiz yakuniy hisoblanmagan.",
    "redFlags": "",
    "finalStatus": "**Narx:** $500–$5,000\n**O‘zbekiston:** aynan model bo‘yicha RFQ kerak\n**Import:** local stockga qarab\n**Yetkazib berish:** konfiguratsiyaga bog‘liq\n**Servis:** yozma tasdiq kerak\n**Ehtiyot qismlar:** alohida BOM/quote kerak\n**TCO:** RFQdan keyin hisoblanadi\n\n---"
  },
    "44": {
    "number": 44,
    "title": "UV-Vis spektrofotometr (suv tahlili)",
    "searchName": "UV-Vis spektrofotometr (suv tahlili)",
    "model": "HACH DR3900 Spektrofotometr",
    "sourceKind": "purchase",
    "price": "$300–$3,000",
    "priceEvidence": "",
    "source": "",
    "priceStatus": "",
    "whereToBuy": "1. Ishlab chiqaruvchining rasmiy kanali.\n2. Authorized distributor/integrator.\n3. O‘zbekistondagi laboratoriya uskunalari yetkazib beruvchisi.\n4. Used/refurbished — faqat servis tarixi va texnik tekshiruv hujjatlari bilan.",
    "purchaseRule": "",
    "availabilityUz": "Aynan `HACH DR3900 Spektrofotometr` uchun O‘zbekistondagi tayyor ombor mavjudligi ushbu bosqichda qat'iy tasdiqlanmagan. Mahalliy distributor/integratorga model raqami bilan RFQ yuborish kerak.",
    "importInfo": "Agar local stock bo‘lmasa, import qilinadi. RFQda:\n- aniq model/catalog raqami;\n- konfiguratsiya;\n- ishlab chiqarilgan mamlakat;\n- HS code;\n- eksport qadoqlashi;\n- kafolat;\n- sertifikat/hujjatlar;\n- Incoterms\nalohida so‘raladi.",
    "delivery": "Transport narxi o‘lcham, og‘irlik, qadoqlash, kelib chiqish mamlakati va maxsus tashish talablariga bog‘liq. **EXW/FCA/DAP/DDP** shartlaridan qaysi biri ekanini quote'da aniq ko‘rsatish kerak.",
    "service": "- O‘zbekistonda authorized service bormi?\n- Kafolatni kim bajaradi?\n- Preventive maintenance davriyligi qanday?\n- Kalibrlash/verification kerakmi?\n- Servis muhandisi kelish muddati qancha?\n\n**Status:** aynan `HACH DR3900 Spektrofotometr` uchun O‘zbekistondagi servis holati yozma tasdiq talab qiladi.",
    "spares": "Xarid bilan birga modelga mos **wear parts, service kit, sensor/probe/filter/tubing va boshqa sarf qismlar** ro‘yxati, narxi va yetkazish muddati so‘raladi.",
    "tco": "**TCO =** xarid + import/bojxona/QQS + transport + o‘rnatish + kalibrlash + servis + ehtiyot qismlar + sarf materiallari + elektr/suv/gaz + dasturiy litsenziya + operator o‘qitish.\n\n**Hozirgi TCO:** RFQ va yillik foydalanish hajmisiz yakuniy hisoblanmagan.",
    "redFlags": "",
    "finalStatus": "**Narx:** $300–$3,000\n**O‘zbekiston:** aynan model bo‘yicha RFQ kerak\n**Import:** local stockga qarab\n**Yetkazib berish:** konfiguratsiyaga bog‘liq\n**Servis:** yozma tasdiq kerak\n**Ehtiyot qismlar:** alohida BOM/quote kerak\n**TCO:** RFQdan keyin hisoblanadi\n\n---"
  },
    "45": {
    "number": 45,
    "title": "Mikroplanshet vasher (yuuvchi qurilma)",
    "searchName": "Mikroplanshet vasher (yuuvchi qurilma)",
    "model": "BioTek ELx50",
    "sourceKind": "purchase",
    "price": "$500–$5,000",
    "priceEvidence": "",
    "source": "",
    "priceStatus": "",
    "whereToBuy": "1. Ishlab chiqaruvchining rasmiy kanali.\n2. Authorized distributor/integrator.\n3. O‘zbekistondagi laboratoriya uskunalari yetkazib beruvchisi.\n4. Used/refurbished — faqat servis tarixi va texnik tekshiruv hujjatlari bilan.",
    "purchaseRule": "",
    "availabilityUz": "Aynan `BioTek ELx50` uchun O‘zbekistondagi tayyor ombor mavjudligi ushbu bosqichda qat'iy tasdiqlanmagan. Mahalliy distributor/integratorga model raqami bilan RFQ yuborish kerak.",
    "importInfo": "Agar local stock bo‘lmasa, import qilinadi. RFQda:\n- aniq model/catalog raqami;\n- konfiguratsiya;\n- ishlab chiqarilgan mamlakat;\n- HS code;\n- eksport qadoqlashi;\n- kafolat;\n- sertifikat/hujjatlar;\n- Incoterms\nalohida so‘raladi.",
    "delivery": "Transport narxi o‘lcham, og‘irlik, qadoqlash, kelib chiqish mamlakati va maxsus tashish talablariga bog‘liq. **EXW/FCA/DAP/DDP** shartlaridan qaysi biri ekanini quote'da aniq ko‘rsatish kerak.",
    "service": "- O‘zbekistonda authorized service bormi?\n- Kafolatni kim bajaradi?\n- Preventive maintenance davriyligi qanday?\n- Kalibrlash/verification kerakmi?\n- Servis muhandisi kelish muddati qancha?\n\n**Status:** aynan `BioTek ELx50` uchun O‘zbekistondagi servis holati yozma tasdiq talab qiladi.",
    "spares": "Xarid bilan birga modelga mos **wear parts, service kit, sensor/probe/filter/tubing va boshqa sarf qismlar** ro‘yxati, narxi va yetkazish muddati so‘raladi.",
    "tco": "**TCO =** xarid + import/bojxona/QQS + transport + o‘rnatish + kalibrlash + servis + ehtiyot qismlar + sarf materiallari + elektr/suv/gaz + dasturiy litsenziya + operator o‘qitish.\n\n**Hozirgi TCO:** RFQ va yillik foydalanish hajmisiz yakuniy hisoblanmagan.",
    "redFlags": "",
    "finalStatus": "**Narx:** $500–$5,000\n**O‘zbekiston:** aynan model bo‘yicha RFQ kerak\n**Import:** local stockga qarab\n**Yetkazib berish:** konfiguratsiyaga bog‘liq\n**Servis:** yozma tasdiq kerak\n**Ehtiyot qismlar:** alohida BOM/quote kerak\n**TCO:** RFQdan keyin hisoblanadi\n\n---"
  },
    "46": {
    "number": 46,
    "title": "CO₂ o‘lchash probi",
    "searchName": "CO₂ o‘lchash probi",
    "model": "Vaisala GMP252 CO2 Probe",
    "sourceKind": "purchase",
    "price": "$1,500–$10,000",
    "priceEvidence": "",
    "source": "",
    "priceStatus": "",
    "whereToBuy": "1. Ishlab chiqaruvchining rasmiy kanali.\n2. Authorized distributor/integrator.\n3. O‘zbekistondagi laboratoriya uskunalari yetkazib beruvchisi.\n4. Used/refurbished — faqat servis tarixi va texnik tekshiruv hujjatlari bilan.",
    "purchaseRule": "",
    "availabilityUz": "Aynan `Vaisala GMP252 CO2 Probe` uchun O‘zbekistondagi tayyor ombor mavjudligi ushbu bosqichda qat'iy tasdiqlanmagan. Mahalliy distributor/integratorga model raqami bilan RFQ yuborish kerak.",
    "importInfo": "Agar local stock bo‘lmasa, import qilinadi. RFQda:\n- aniq model/catalog raqami;\n- konfiguratsiya;\n- ishlab chiqarilgan mamlakat;\n- HS code;\n- eksport qadoqlashi;\n- kafolat;\n- sertifikat/hujjatlar;\n- Incoterms\nalohida so‘raladi.",
    "delivery": "Transport narxi o‘lcham, og‘irlik, qadoqlash, kelib chiqish mamlakati va maxsus tashish talablariga bog‘liq. **EXW/FCA/DAP/DDP** shartlaridan qaysi biri ekanini quote'da aniq ko‘rsatish kerak.",
    "service": "- O‘zbekistonda authorized service bormi?\n- Kafolatni kim bajaradi?\n- Preventive maintenance davriyligi qanday?\n- Kalibrlash/verification kerakmi?\n- Servis muhandisi kelish muddati qancha?\n\n**Status:** aynan `Vaisala GMP252 CO2 Probe` uchun O‘zbekistondagi servis holati yozma tasdiq talab qiladi.",
    "spares": "Xarid bilan birga modelga mos **wear parts, service kit, sensor/probe/filter/tubing va boshqa sarf qismlar** ro‘yxati, narxi va yetkazish muddati so‘raladi.",
    "tco": "**TCO =** xarid + import/bojxona/QQS + transport + o‘rnatish + kalibrlash + servis + ehtiyot qismlar + sarf materiallari + elektr/suv/gaz + dasturiy litsenziya + operator o‘qitish.\n\n**Hozirgi TCO:** RFQ va yillik foydalanish hajmisiz yakuniy hisoblanmagan.",
    "redFlags": "",
    "finalStatus": "**Narx:** $1,500–$10,000\n**O‘zbekiston:** aynan model bo‘yicha RFQ kerak\n**Import:** local stockga qarab\n**Yetkazib berish:** konfiguratsiyaga bog‘liq\n**Servis:** yozma tasdiq kerak\n**Ehtiyot qismlar:** alohida BOM/quote kerak\n**TCO:** RFQdan keyin hisoblanadi\n\n---"
  },
    "47": {
    "number": 47,
    "title": "Shpritsli nasos (syringe pump)",
    "searchName": "Shpritsli nasos (syringe pump)",
    "model": "Harvard Apparatus PHD ULTRA",
    "sourceKind": "purchase",
    "price": "$1,000–$8,000",
    "priceEvidence": "",
    "source": "",
    "priceStatus": "",
    "whereToBuy": "1. Ishlab chiqaruvchining rasmiy kanali.\n2. Authorized distributor/integrator.\n3. O‘zbekistondagi laboratoriya uskunalari yetkazib beruvchisi.\n4. Used/refurbished — faqat servis tarixi va texnik tekshiruv hujjatlari bilan.",
    "purchaseRule": "",
    "availabilityUz": "Aynan `Harvard Apparatus PHD ULTRA` uchun O‘zbekistondagi tayyor ombor mavjudligi ushbu bosqichda qat'iy tasdiqlanmagan. Mahalliy distributor/integratorga model raqami bilan RFQ yuborish kerak.",
    "importInfo": "Agar local stock bo‘lmasa, import qilinadi. RFQda:\n- aniq model/catalog raqami;\n- konfiguratsiya;\n- ishlab chiqarilgan mamlakat;\n- HS code;\n- eksport qadoqlashi;\n- kafolat;\n- sertifikat/hujjatlar;\n- Incoterms\nalohida so‘raladi.",
    "delivery": "Transport narxi o‘lcham, og‘irlik, qadoqlash, kelib chiqish mamlakati va maxsus tashish talablariga bog‘liq. **EXW/FCA/DAP/DDP** shartlaridan qaysi biri ekanini quote'da aniq ko‘rsatish kerak.",
    "service": "- O‘zbekistonda authorized service bormi?\n- Kafolatni kim bajaradi?\n- Preventive maintenance davriyligi qanday?\n- Kalibrlash/verification kerakmi?\n- Servis muhandisi kelish muddati qancha?\n\n**Status:** aynan `Harvard Apparatus PHD ULTRA` uchun O‘zbekistondagi servis holati yozma tasdiq talab qiladi.",
    "spares": "Xarid bilan birga modelga mos **wear parts, service kit, sensor/probe/filter/tubing va boshqa sarf qismlar** ro‘yxati, narxi va yetkazish muddati so‘raladi.",
    "tco": "**TCO =** xarid + import/bojxona/QQS + transport + o‘rnatish + kalibrlash + servis + ehtiyot qismlar + sarf materiallari + elektr/suv/gaz + dasturiy litsenziya + operator o‘qitish.\n\n**Hozirgi TCO:** RFQ va yillik foydalanish hajmisiz yakuniy hisoblanmagan.",
    "redFlags": "",
    "finalStatus": "**Narx:** $1,000–$8,000\n**O‘zbekiston:** aynan model bo‘yicha RFQ kerak\n**Import:** local stockga qarab\n**Yetkazib berish:** konfiguratsiyaga bog‘liq\n**Servis:** yozma tasdiq kerak\n**Ehtiyot qismlar:** alohida BOM/quote kerak\n**TCO:** RFQdan keyin hisoblanadi\n\n---"
  },
    "48": {
    "number": 48,
    "title": "Peristaltik nasos",
    "searchName": "Peristaltik nasos",
    "model": "Watson-Marlow 630Di",
    "sourceKind": "purchase",
    "price": "$1,000–$10,000",
    "priceEvidence": "",
    "source": "",
    "priceStatus": "",
    "whereToBuy": "1. Ishlab chiqaruvchining rasmiy kanali.\n2. Authorized distributor/integrator.\n3. O‘zbekistondagi laboratoriya uskunalari yetkazib beruvchisi.\n4. Used/refurbished — faqat servis tarixi va texnik tekshiruv hujjatlari bilan.",
    "purchaseRule": "",
    "availabilityUz": "Aynan `Watson-Marlow 630Di` uchun O‘zbekistondagi tayyor ombor mavjudligi ushbu bosqichda qat'iy tasdiqlanmagan. Mahalliy distributor/integratorga model raqami bilan RFQ yuborish kerak.",
    "importInfo": "Agar local stock bo‘lmasa, import qilinadi. RFQda:\n- aniq model/catalog raqami;\n- konfiguratsiya;\n- ishlab chiqarilgan mamlakat;\n- HS code;\n- eksport qadoqlashi;\n- kafolat;\n- sertifikat/hujjatlar;\n- Incoterms\nalohida so‘raladi.",
    "delivery": "Transport narxi o‘lcham, og‘irlik, qadoqlash, kelib chiqish mamlakati va maxsus tashish talablariga bog‘liq. **EXW/FCA/DAP/DDP** shartlaridan qaysi biri ekanini quote'da aniq ko‘rsatish kerak.",
    "service": "- O‘zbekistonda authorized service bormi?\n- Kafolatni kim bajaradi?\n- Preventive maintenance davriyligi qanday?\n- Kalibrlash/verification kerakmi?\n- Servis muhandisi kelish muddati qancha?\n\n**Status:** aynan `Watson-Marlow 630Di` uchun O‘zbekistondagi servis holati yozma tasdiq talab qiladi.",
    "spares": "Xarid bilan birga modelga mos **wear parts, service kit, sensor/probe/filter/tubing va boshqa sarf qismlar** ro‘yxati, narxi va yetkazish muddati so‘raladi.",
    "tco": "**TCO =** xarid + import/bojxona/QQS + transport + o‘rnatish + kalibrlash + servis + ehtiyot qismlar + sarf materiallari + elektr/suv/gaz + dasturiy litsenziya + operator o‘qitish.\n\n**Hozirgi TCO:** RFQ va yillik foydalanish hajmisiz yakuniy hisoblanmagan.",
    "redFlags": "",
    "finalStatus": "**Narx:** $1,000–$10,000\n**O‘zbekiston:** aynan model bo‘yicha RFQ kerak\n**Import:** local stockga qarab\n**Yetkazib berish:** konfiguratsiyaga bog‘liq\n**Servis:** yozma tasdiq kerak\n**Ehtiyot qismlar:** alohida BOM/quote kerak\n**TCO:** RFQdan keyin hisoblanadi\n\n---"
  },
    "49": {
    "number": 49,
    "title": "Gelga aylantiruvchi sistema (gel documentation)",
    "searchName": "Gelga aylantiruvchi sistema (gel documentation)",
    "model": "Bio-Rad Gel Doc XR+",
    "sourceKind": "purchase",
    "price": "$1,000–$7,000",
    "priceEvidence": "",
    "source": "",
    "priceStatus": "",
    "whereToBuy": "1. Ishlab chiqaruvchining rasmiy kanali.\n2. Authorized distributor/integrator.\n3. O‘zbekistondagi laboratoriya uskunalari yetkazib beruvchisi.\n4. Used/refurbished — faqat servis tarixi va texnik tekshiruv hujjatlari bilan.",
    "purchaseRule": "",
    "availabilityUz": "Aynan `Bio-Rad Gel Doc XR+` uchun O‘zbekistondagi tayyor ombor mavjudligi ushbu bosqichda qat'iy tasdiqlanmagan. Mahalliy distributor/integratorga model raqami bilan RFQ yuborish kerak.",
    "importInfo": "Agar local stock bo‘lmasa, import qilinadi. RFQda:\n- aniq model/catalog raqami;\n- konfiguratsiya;\n- ishlab chiqarilgan mamlakat;\n- HS code;\n- eksport qadoqlashi;\n- kafolat;\n- sertifikat/hujjatlar;\n- Incoterms\nalohida so‘raladi.",
    "delivery": "Transport narxi o‘lcham, og‘irlik, qadoqlash, kelib chiqish mamlakati va maxsus tashish talablariga bog‘liq. **EXW/FCA/DAP/DDP** shartlaridan qaysi biri ekanini quote'da aniq ko‘rsatish kerak.",
    "service": "- O‘zbekistonda authorized service bormi?\n- Kafolatni kim bajaradi?\n- Preventive maintenance davriyligi qanday?\n- Kalibrlash/verification kerakmi?\n- Servis muhandisi kelish muddati qancha?\n\n**Status:** aynan `Bio-Rad Gel Doc XR+` uchun O‘zbekistondagi servis holati yozma tasdiq talab qiladi.",
    "spares": "Xarid bilan birga modelga mos **wear parts, service kit, sensor/probe/filter/tubing va boshqa sarf qismlar** ro‘yxati, narxi va yetkazish muddati so‘raladi.",
    "tco": "**TCO =** xarid + import/bojxona/QQS + transport + o‘rnatish + kalibrlash + servis + ehtiyot qismlar + sarf materiallari + elektr/suv/gaz + dasturiy litsenziya + operator o‘qitish.\n\n**Hozirgi TCO:** RFQ va yillik foydalanish hajmisiz yakuniy hisoblanmagan.",
    "redFlags": "",
    "finalStatus": "**Narx:** $1,000–$7,000\n**O‘zbekiston:** aynan model bo‘yicha RFQ kerak\n**Import:** local stockga qarab\n**Yetkazib berish:** konfiguratsiyaga bog‘liq\n**Servis:** yozma tasdiq kerak\n**Ehtiyot qismlar:** alohida BOM/quote kerak\n**TCO:** RFQdan keyin hisoblanadi\n\n---"
  },
    "50": {
    "number": 50,
    "title": "SPME fiber assembly — sarf materiali",
    "searchName": "SPME fiber assembly — sarf materiali",
    "model": "Supelco SPME Fiber Assembly",
    "sourceKind": "purchase",
    "price": "$1,500–$12,000",
    "priceEvidence": "",
    "source": "",
    "priceStatus": "",
    "whereToBuy": "1. Ishlab chiqaruvchining rasmiy kanali.\n2. Authorized distributor/integrator.\n3. O‘zbekistondagi laboratoriya uskunalari yetkazib beruvchisi.\n4. Used/refurbished — faqat servis tarixi va texnik tekshiruv hujjatlari bilan.",
    "purchaseRule": "",
    "availabilityUz": "Aynan `Supelco SPME Fiber Assembly` uchun O‘zbekistondagi tayyor ombor mavjudligi ushbu bosqichda qat'iy tasdiqlanmagan. Mahalliy distributor/integratorga model raqami bilan RFQ yuborish kerak.",
    "importInfo": "Agar local stock bo‘lmasa, import qilinadi. RFQda:\n- aniq model/catalog raqami;\n- konfiguratsiya;\n- ishlab chiqarilgan mamlakat;\n- HS code;\n- eksport qadoqlashi;\n- kafolat;\n- sertifikat/hujjatlar;\n- Incoterms\nalohida so‘raladi.",
    "delivery": "Transport narxi o‘lcham, og‘irlik, qadoqlash, kelib chiqish mamlakati va maxsus tashish talablariga bog‘liq. **EXW/FCA/DAP/DDP** shartlaridan qaysi biri ekanini quote'da aniq ko‘rsatish kerak.",
    "service": "- O‘zbekistonda authorized service bormi?\n- Kafolatni kim bajaradi?\n- Preventive maintenance davriyligi qanday?\n- Kalibrlash/verification kerakmi?\n- Servis muhandisi kelish muddati qancha?\n\n**Status:** aynan `Supelco SPME Fiber Assembly` uchun O‘zbekistondagi servis holati yozma tasdiq talab qiladi.",
    "spares": "Xarid bilan birga modelga mos **wear parts, service kit, sensor/probe/filter/tubing va boshqa sarf qismlar** ro‘yxati, narxi va yetkazish muddati so‘raladi.",
    "tco": "**TCO =** xarid + import/bojxona/QQS + transport + o‘rnatish + kalibrlash + servis + ehtiyot qismlar + sarf materiallari + elektr/suv/gaz + dasturiy litsenziya + operator o‘qitish.\n\n**Hozirgi TCO:** RFQ va yillik foydalanish hajmisiz yakuniy hisoblanmagan.",
    "redFlags": "",
    "finalStatus": "**Narx:** $1,500–$12,000\n**O‘zbekiston:** aynan model bo‘yicha RFQ kerak\n**Import:** local stockga qarab\n**Yetkazib berish:** konfiguratsiyaga bog‘liq\n**Servis:** yozma tasdiq kerak\n**Ehtiyot qismlar:** alohida BOM/quote kerak\n**TCO:** RFQdan keyin hisoblanadi\n\n---\n\n# 26–50 BLOK YAKUNI\n\n**Tayyor:** 50 / 100\n\n**Keyingi blok:** II-C — 51–75-qurilmalar.\n\n> Eslatma: xarid bazasida tasdiqlanmagan aniq narxni “rasmiy narx” sifatida yozishdan ko‘ra, RFQ talab qilinishini ko‘rsatish xavfsizroq. Bu keyingi TCO hisoblarini ham ishonchliroq qiladi."
  }
};

export default purchaseBlock2;
