import type { PurchaseContent } from "./learningData";

const purchaseBlock3: Record<number, PurchaseContent> = {
    "51": {
    "number": 51,
    "title": "Ultrapure suv tozalash tizimi",
    "searchName": "Ultrapure suv tozalash tizimi",
    "model": "Milli-Q IQ 7000 (Merck)",
    "sourceKind": "purchase",
    "price": "$2,000–$12,000",
    "priceEvidence": "",
    "source": "",
    "priceStatus": "",
    "whereToBuy": "1. Ishlab chiqaruvchining rasmiy savdo kanali.\n2. Authorized distributor/integrator.\n3. O‘zbekistondagi laboratoriya uskunalari yetkazib beruvchisi.\n4. Used/refurbished — faqat texnik tekshiruv, servis tarixi va calibration hujjati bilan.",
    "purchaseRule": "",
    "availabilityUz": "Aynan `Milli-Q IQ 7000 (Merck)` uchun tayyor local stock holati ushbu bosqichda qat'iy tasdiqlanmagan. Mahalliy distributor/integratorga **model + konfiguratsiya** bilan RFQ yuborish kerak.",
    "importInfo": "Local stock bo‘lmasa, import qilinadi. RFQda model/catalog raqami, konfiguratsiya, ishlab chiqarilgan mamlakat, HS code, eksport qadoqlashi, kafolat, sertifikatlar va Incoterms alohida so‘raladi.",
    "delivery": "Transport narxi o‘lcham, og‘irlik, qadoqlash, kelib chiqish mamlakati va maxsus tashish talablariga bog‘liq. **EXW/FCA/DAP/DDP** shartlari quote'da aniq ko‘rsatilishi kerak.",
    "service": "- O‘zbekistonda authorized service bormi?\n- Kafolatni kim bajaradi?\n- Preventive maintenance davriyligi qanday?\n- Kalibrlash/verification talab qilinadimi?\n- Servis muhandisi kelish muddati qancha?\n\n**Status:** aynan `Milli-Q IQ 7000 (Merck)` uchun O‘zbekistondagi servis holati yozma tasdiqlanishi kerak.",
    "spares": "Xarid bilan birga modelga mos **wear parts, service kit, sensor/probe/filter/tubing va boshqa sarf qismlar** ro‘yxati, narxi va lead time'i olinadi.",
    "tco": "**TCO =** xarid + import/bojxona/QQS + transport + o‘rnatish + kalibrlash + servis + ehtiyot qismlar + sarf materiallari + elektr/suv/gaz + dasturiy litsenziyalar + operator o‘qitish.\n\n**Hozirgi TCO:** RFQ va yillik foydalanish hajmisiz yakuniy hisoblanmagan.",
    "redFlags": "",
    "finalStatus": "**Narx:** $2,000–$12,000\n**O‘zbekiston:** aynan model bo‘yicha RFQ kerak\n**Import:** local stockga qarab\n**Yetkazib berish:** konfiguratsiyaga bog‘liq\n**Servis:** yozma tasdiq kerak\n**Ehtiyot qismlar:** alohida BOM/quote kerak\n**TCO:** RFQdan keyin hisoblanadi\n\n---"
  },
    "52": {
    "number": 52,
    "title": "Termomixer (blok termostat)",
    "searchName": "Termomixer (blok termostat)",
    "model": "Eppendorf ThermoMixer C",
    "sourceKind": "purchase",
    "price": "$1,000–$8,000",
    "priceEvidence": "",
    "source": "",
    "priceStatus": "",
    "whereToBuy": "1. Ishlab chiqaruvchining rasmiy savdo kanali.\n2. Authorized distributor/integrator.\n3. O‘zbekistondagi laboratoriya uskunalari yetkazib beruvchisi.\n4. Used/refurbished — faqat texnik tekshiruv, servis tarixi va calibration hujjati bilan.",
    "purchaseRule": "",
    "availabilityUz": "Aynan `Eppendorf ThermoMixer C` uchun tayyor local stock holati ushbu bosqichda qat'iy tasdiqlanmagan. Mahalliy distributor/integratorga **model + konfiguratsiya** bilan RFQ yuborish kerak.",
    "importInfo": "Local stock bo‘lmasa, import qilinadi. RFQda model/catalog raqami, konfiguratsiya, ishlab chiqarilgan mamlakat, HS code, eksport qadoqlashi, kafolat, sertifikatlar va Incoterms alohida so‘raladi.",
    "delivery": "Transport narxi o‘lcham, og‘irlik, qadoqlash, kelib chiqish mamlakati va maxsus tashish talablariga bog‘liq. **EXW/FCA/DAP/DDP** shartlari quote'da aniq ko‘rsatilishi kerak.",
    "service": "- O‘zbekistonda authorized service bormi?\n- Kafolatni kim bajaradi?\n- Preventive maintenance davriyligi qanday?\n- Kalibrlash/verification talab qilinadimi?\n- Servis muhandisi kelish muddati qancha?\n\n**Status:** aynan `Eppendorf ThermoMixer C` uchun O‘zbekistondagi servis holati yozma tasdiqlanishi kerak.",
    "spares": "Xarid bilan birga modelga mos **wear parts, service kit, sensor/probe/filter/tubing va boshqa sarf qismlar** ro‘yxati, narxi va lead time'i olinadi.",
    "tco": "**TCO =** xarid + import/bojxona/QQS + transport + o‘rnatish + kalibrlash + servis + ehtiyot qismlar + sarf materiallari + elektr/suv/gaz + dasturiy litsenziyalar + operator o‘qitish.\n\n**Hozirgi TCO:** RFQ va yillik foydalanish hajmisiz yakuniy hisoblanmagan.",
    "redFlags": "",
    "finalStatus": "**Narx:** $1,000–$8,000\n**O‘zbekiston:** aynan model bo‘yicha RFQ kerak\n**Import:** local stockga qarab\n**Yetkazib berish:** konfiguratsiyaga bog‘liq\n**Servis:** yozma tasdiq kerak\n**Ehtiyot qismlar:** alohida BOM/quote kerak\n**TCO:** RFQdan keyin hisoblanadi\n\n---"
  },
    "53": {
    "number": 53,
    "title": "SPE kartriji (Oasis HLB) — sarf materiali",
    "searchName": "SPE kartriji (Oasis HLB) — sarf materiali",
    "model": "Waters Oasis HLB 3cc Cartridge",
    "sourceKind": "purchase",
    "price": "$2,000–$15,000",
    "priceEvidence": "",
    "source": "",
    "priceStatus": "",
    "whereToBuy": "1. Ishlab chiqaruvchining rasmiy savdo kanali.\n2. Authorized distributor/integrator.\n3. O‘zbekistondagi laboratoriya uskunalari yetkazib beruvchisi.\n4. Used/refurbished — faqat texnik tekshiruv, servis tarixi va calibration hujjati bilan.",
    "purchaseRule": "",
    "availabilityUz": "Aynan `Waters Oasis HLB 3cc Cartridge` uchun tayyor local stock holati ushbu bosqichda qat'iy tasdiqlanmagan. Mahalliy distributor/integratorga **model + konfiguratsiya** bilan RFQ yuborish kerak.",
    "importInfo": "Local stock bo‘lmasa, import qilinadi. RFQda model/catalog raqami, konfiguratsiya, ishlab chiqarilgan mamlakat, HS code, eksport qadoqlashi, kafolat, sertifikatlar va Incoterms alohida so‘raladi.",
    "delivery": "Transport narxi o‘lcham, og‘irlik, qadoqlash, kelib chiqish mamlakati va maxsus tashish talablariga bog‘liq. **EXW/FCA/DAP/DDP** shartlari quote'da aniq ko‘rsatilishi kerak.",
    "service": "- O‘zbekistonda authorized service bormi?\n- Kafolatni kim bajaradi?\n- Preventive maintenance davriyligi qanday?\n- Kalibrlash/verification talab qilinadimi?\n- Servis muhandisi kelish muddati qancha?\n\n**Status:** aynan `Waters Oasis HLB 3cc Cartridge` uchun O‘zbekistondagi servis holati yozma tasdiqlanishi kerak.",
    "spares": "Xarid bilan birga modelga mos **wear parts, service kit, sensor/probe/filter/tubing va boshqa sarf qismlar** ro‘yxati, narxi va lead time'i olinadi.",
    "tco": "**TCO =** xarid + import/bojxona/QQS + transport + o‘rnatish + kalibrlash + servis + ehtiyot qismlar + sarf materiallari + elektr/suv/gaz + dasturiy litsenziyalar + operator o‘qitish.\n\n**Hozirgi TCO:** RFQ va yillik foydalanish hajmisiz yakuniy hisoblanmagan.",
    "redFlags": "",
    "finalStatus": "**Narx:** $2,000–$15,000\n**O‘zbekiston:** aynan model bo‘yicha RFQ kerak\n**Import:** local stockga qarab\n**Yetkazib berish:** konfiguratsiyaga bog‘liq\n**Servis:** yozma tasdiq kerak\n**Ehtiyot qismlar:** alohida BOM/quote kerak\n**TCO:** RFQdan keyin hisoblanadi\n\n---"
  },
    "54": {
    "number": 54,
    "title": "Protein elektroforez tizimi (SDS-PAGE)",
    "searchName": "Protein elektroforez tizimi (SDS-PAGE)",
    "model": "Bio-Rad Mini-PROTEAN Tetra Cell",
    "sourceKind": "purchase",
    "price": "$1,500–$12,000",
    "priceEvidence": "",
    "source": "",
    "priceStatus": "",
    "whereToBuy": "1. Ishlab chiqaruvchining rasmiy savdo kanali.\n2. Authorized distributor/integrator.\n3. O‘zbekistondagi laboratoriya uskunalari yetkazib beruvchisi.\n4. Used/refurbished — faqat texnik tekshiruv, servis tarixi va calibration hujjati bilan.",
    "purchaseRule": "",
    "availabilityUz": "Aynan `Bio-Rad Mini-PROTEAN Tetra Cell` uchun tayyor local stock holati ushbu bosqichda qat'iy tasdiqlanmagan. Mahalliy distributor/integratorga **model + konfiguratsiya** bilan RFQ yuborish kerak.",
    "importInfo": "Local stock bo‘lmasa, import qilinadi. RFQda model/catalog raqami, konfiguratsiya, ishlab chiqarilgan mamlakat, HS code, eksport qadoqlashi, kafolat, sertifikatlar va Incoterms alohida so‘raladi.",
    "delivery": "Transport narxi o‘lcham, og‘irlik, qadoqlash, kelib chiqish mamlakati va maxsus tashish talablariga bog‘liq. **EXW/FCA/DAP/DDP** shartlari quote'da aniq ko‘rsatilishi kerak.",
    "service": "- O‘zbekistonda authorized service bormi?\n- Kafolatni kim bajaradi?\n- Preventive maintenance davriyligi qanday?\n- Kalibrlash/verification talab qilinadimi?\n- Servis muhandisi kelish muddati qancha?\n\n**Status:** aynan `Bio-Rad Mini-PROTEAN Tetra Cell` uchun O‘zbekistondagi servis holati yozma tasdiqlanishi kerak.",
    "spares": "Xarid bilan birga modelga mos **wear parts, service kit, sensor/probe/filter/tubing va boshqa sarf qismlar** ro‘yxati, narxi va lead time'i olinadi.",
    "tco": "**TCO =** xarid + import/bojxona/QQS + transport + o‘rnatish + kalibrlash + servis + ehtiyot qismlar + sarf materiallari + elektr/suv/gaz + dasturiy litsenziyalar + operator o‘qitish.\n\n**Hozirgi TCO:** RFQ va yillik foydalanish hajmisiz yakuniy hisoblanmagan.",
    "redFlags": "",
    "finalStatus": "**Narx:** $1,500–$12,000\n**O‘zbekiston:** aynan model bo‘yicha RFQ kerak\n**Import:** local stockga qarab\n**Yetkazib berish:** konfiguratsiyaga bog‘liq\n**Servis:** yozma tasdiq kerak\n**Ehtiyot qismlar:** alohida BOM/quote kerak\n**TCO:** RFQdan keyin hisoblanadi\n\n---"
  },
    "55": {
    "number": 55,
    "title": "Izoelektrik fokuslash (IEF) tizimi",
    "searchName": "Izoelektrik fokuslash (IEF) tizimi",
    "model": "Bio-Rad Protean IEF Cell",
    "sourceKind": "purchase",
    "price": "$3,000–$20,000",
    "priceEvidence": "",
    "source": "",
    "priceStatus": "",
    "whereToBuy": "1. Ishlab chiqaruvchining rasmiy savdo kanali.\n2. Authorized distributor/integrator.\n3. O‘zbekistondagi laboratoriya uskunalari yetkazib beruvchisi.\n4. Used/refurbished — faqat texnik tekshiruv, servis tarixi va calibration hujjati bilan.",
    "purchaseRule": "",
    "availabilityUz": "Aynan `Bio-Rad Protean IEF Cell` uchun tayyor local stock holati ushbu bosqichda qat'iy tasdiqlanmagan. Mahalliy distributor/integratorga **model + konfiguratsiya** bilan RFQ yuborish kerak.",
    "importInfo": "Local stock bo‘lmasa, import qilinadi. RFQda model/catalog raqami, konfiguratsiya, ishlab chiqarilgan mamlakat, HS code, eksport qadoqlashi, kafolat, sertifikatlar va Incoterms alohida so‘raladi.",
    "delivery": "Transport narxi o‘lcham, og‘irlik, qadoqlash, kelib chiqish mamlakati va maxsus tashish talablariga bog‘liq. **EXW/FCA/DAP/DDP** shartlari quote'da aniq ko‘rsatilishi kerak.",
    "service": "- O‘zbekistonda authorized service bormi?\n- Kafolatni kim bajaradi?\n- Preventive maintenance davriyligi qanday?\n- Kalibrlash/verification talab qilinadimi?\n- Servis muhandisi kelish muddati qancha?\n\n**Status:** aynan `Bio-Rad Protean IEF Cell` uchun O‘zbekistondagi servis holati yozma tasdiqlanishi kerak.",
    "spares": "Xarid bilan birga modelga mos **wear parts, service kit, sensor/probe/filter/tubing va boshqa sarf qismlar** ro‘yxati, narxi va lead time'i olinadi.",
    "tco": "**TCO =** xarid + import/bojxona/QQS + transport + o‘rnatish + kalibrlash + servis + ehtiyot qismlar + sarf materiallari + elektr/suv/gaz + dasturiy litsenziyalar + operator o‘qitish.\n\n**Hozirgi TCO:** RFQ va yillik foydalanish hajmisiz yakuniy hisoblanmagan.",
    "redFlags": "",
    "finalStatus": "**Narx:** $3,000–$20,000\n**O‘zbekiston:** aynan model bo‘yicha RFQ kerak\n**Import:** local stockga qarab\n**Yetkazib berish:** konfiguratsiyaga bog‘liq\n**Servis:** yozma tasdiq kerak\n**Ehtiyot qismlar:** alohida BOM/quote kerak\n**TCO:** RFQdan keyin hisoblanadi\n\n---"
  },
    "56": {
    "number": 56,
    "title": "Oqsil tozalash tizimi (FPLC)",
    "searchName": "Oqsil tozalash tizimi (FPLC)",
    "model": "Cytiva AKTA Pure 25",
    "sourceKind": "purchase",
    "price": "$2,000–$15,000",
    "priceEvidence": "",
    "source": "",
    "priceStatus": "",
    "whereToBuy": "1. Ishlab chiqaruvchining rasmiy savdo kanali.\n2. Authorized distributor/integrator.\n3. O‘zbekistondagi laboratoriya uskunalari yetkazib beruvchisi.\n4. Used/refurbished — faqat texnik tekshiruv, servis tarixi va calibration hujjati bilan.",
    "purchaseRule": "",
    "availabilityUz": "Aynan `Cytiva AKTA Pure 25` uchun tayyor local stock holati ushbu bosqichda qat'iy tasdiqlanmagan. Mahalliy distributor/integratorga **model + konfiguratsiya** bilan RFQ yuborish kerak.",
    "importInfo": "Local stock bo‘lmasa, import qilinadi. RFQda model/catalog raqami, konfiguratsiya, ishlab chiqarilgan mamlakat, HS code, eksport qadoqlashi, kafolat, sertifikatlar va Incoterms alohida so‘raladi.",
    "delivery": "Transport narxi o‘lcham, og‘irlik, qadoqlash, kelib chiqish mamlakati va maxsus tashish talablariga bog‘liq. **EXW/FCA/DAP/DDP** shartlari quote'da aniq ko‘rsatilishi kerak.",
    "service": "- O‘zbekistonda authorized service bormi?\n- Kafolatni kim bajaradi?\n- Preventive maintenance davriyligi qanday?\n- Kalibrlash/verification talab qilinadimi?\n- Servis muhandisi kelish muddati qancha?\n\n**Status:** aynan `Cytiva AKTA Pure 25` uchun O‘zbekistondagi servis holati yozma tasdiqlanishi kerak.",
    "spares": "Xarid bilan birga modelga mos **wear parts, service kit, sensor/probe/filter/tubing va boshqa sarf qismlar** ro‘yxati, narxi va lead time'i olinadi.",
    "tco": "**TCO =** xarid + import/bojxona/QQS + transport + o‘rnatish + kalibrlash + servis + ehtiyot qismlar + sarf materiallari + elektr/suv/gaz + dasturiy litsenziyalar + operator o‘qitish.\n\n**Hozirgi TCO:** RFQ va yillik foydalanish hajmisiz yakuniy hisoblanmagan.",
    "redFlags": "",
    "finalStatus": "**Narx:** $2,000–$15,000\n**O‘zbekiston:** aynan model bo‘yicha RFQ kerak\n**Import:** local stockga qarab\n**Yetkazib berish:** konfiguratsiyaga bog‘liq\n**Servis:** yozma tasdiq kerak\n**Ehtiyot qismlar:** alohida BOM/quote kerak\n**TCO:** RFQdan keyin hisoblanadi\n\n---"
  },
    "57": {
    "number": 57,
    "title": "Kimyoluminessent/fluorescent gel va blot imaging tizimi",
    "searchName": "Kimyoluminessent/fluorescent gel va blot imaging tizimi",
    "model": "Amersham ImageQuant 800",
    "sourceKind": "purchase",
    "price": "$1,000–$8,000",
    "priceEvidence": "",
    "source": "",
    "priceStatus": "",
    "whereToBuy": "1. Ishlab chiqaruvchining rasmiy savdo kanali.\n2. Authorized distributor/integrator.\n3. O‘zbekistondagi laboratoriya uskunalari yetkazib beruvchisi.\n4. Used/refurbished — faqat texnik tekshiruv, servis tarixi va calibration hujjati bilan.",
    "purchaseRule": "",
    "availabilityUz": "Aynan `Amersham ImageQuant 800` uchun tayyor local stock holati ushbu bosqichda qat'iy tasdiqlanmagan. Mahalliy distributor/integratorga **model + konfiguratsiya** bilan RFQ yuborish kerak.",
    "importInfo": "Local stock bo‘lmasa, import qilinadi. RFQda model/catalog raqami, konfiguratsiya, ishlab chiqarilgan mamlakat, HS code, eksport qadoqlashi, kafolat, sertifikatlar va Incoterms alohida so‘raladi.",
    "delivery": "Transport narxi o‘lcham, og‘irlik, qadoqlash, kelib chiqish mamlakati va maxsus tashish talablariga bog‘liq. **EXW/FCA/DAP/DDP** shartlari quote'da aniq ko‘rsatilishi kerak.",
    "service": "- O‘zbekistonda authorized service bormi?\n- Kafolatni kim bajaradi?\n- Preventive maintenance davriyligi qanday?\n- Kalibrlash/verification talab qilinadimi?\n- Servis muhandisi kelish muddati qancha?\n\n**Status:** aynan `Amersham ImageQuant 800` uchun O‘zbekistondagi servis holati yozma tasdiqlanishi kerak.",
    "spares": "Xarid bilan birga modelga mos **wear parts, service kit, sensor/probe/filter/tubing va boshqa sarf qismlar** ro‘yxati, narxi va lead time'i olinadi.",
    "tco": "**TCO =** xarid + import/bojxona/QQS + transport + o‘rnatish + kalibrlash + servis + ehtiyot qismlar + sarf materiallari + elektr/suv/gaz + dasturiy litsenziyalar + operator o‘qitish.\n\n**Hozirgi TCO:** RFQ va yillik foydalanish hajmisiz yakuniy hisoblanmagan.",
    "redFlags": "",
    "finalStatus": "**Narx:** $1,000–$8,000\n**O‘zbekiston:** aynan model bo‘yicha RFQ kerak\n**Import:** local stockga qarab\n**Yetkazib berish:** konfiguratsiyaga bog‘liq\n**Servis:** yozma tasdiq kerak\n**Ehtiyot qismlar:** alohida BOM/quote kerak\n**TCO:** RFQdan keyin hisoblanadi\n\n---"
  },
    "58": {
    "number": 58,
    "title": "Yadroviy magnit rezonans (NMR)",
    "searchName": "Yadroviy magnit rezonans (NMR)",
    "model": "Bruker AVANCE NEO 400MHz",
    "sourceKind": "purchase",
    "price": "$1,500–$10,000",
    "priceEvidence": "",
    "source": "",
    "priceStatus": "",
    "whereToBuy": "1. Ishlab chiqaruvchining rasmiy savdo kanali.\n2. Authorized distributor/integrator.\n3. O‘zbekistondagi laboratoriya uskunalari yetkazib beruvchisi.\n4. Used/refurbished — faqat texnik tekshiruv, servis tarixi va calibration hujjati bilan.",
    "purchaseRule": "",
    "availabilityUz": "Aynan `Bruker AVANCE NEO 400MHz` uchun tayyor local stock holati ushbu bosqichda qat'iy tasdiqlanmagan. Mahalliy distributor/integratorga **model + konfiguratsiya** bilan RFQ yuborish kerak.",
    "importInfo": "Local stock bo‘lmasa, import qilinadi. RFQda model/catalog raqami, konfiguratsiya, ishlab chiqarilgan mamlakat, HS code, eksport qadoqlashi, kafolat, sertifikatlar va Incoterms alohida so‘raladi.",
    "delivery": "Transport narxi o‘lcham, og‘irlik, qadoqlash, kelib chiqish mamlakati va maxsus tashish talablariga bog‘liq. **EXW/FCA/DAP/DDP** shartlari quote'da aniq ko‘rsatilishi kerak.",
    "service": "- O‘zbekistonda authorized service bormi?\n- Kafolatni kim bajaradi?\n- Preventive maintenance davriyligi qanday?\n- Kalibrlash/verification talab qilinadimi?\n- Servis muhandisi kelish muddati qancha?\n\n**Status:** aynan `Bruker AVANCE NEO 400MHz` uchun O‘zbekistondagi servis holati yozma tasdiqlanishi kerak.",
    "spares": "Xarid bilan birga modelga mos **wear parts, service kit, sensor/probe/filter/tubing va boshqa sarf qismlar** ro‘yxati, narxi va lead time'i olinadi.",
    "tco": "**TCO =** xarid + import/bojxona/QQS + transport + o‘rnatish + kalibrlash + servis + ehtiyot qismlar + sarf materiallari + elektr/suv/gaz + dasturiy litsenziyalar + operator o‘qitish.\n\n**Hozirgi TCO:** RFQ va yillik foydalanish hajmisiz yakuniy hisoblanmagan.",
    "redFlags": "",
    "finalStatus": "**Narx:** $1,500–$10,000\n**O‘zbekiston:** aynan model bo‘yicha RFQ kerak\n**Import:** local stockga qarab\n**Yetkazib berish:** konfiguratsiyaga bog‘liq\n**Servis:** yozma tasdiq kerak\n**Ehtiyot qismlar:** alohida BOM/quote kerak\n**TCO:** RFQdan keyin hisoblanadi\n\n---"
  },
    "59": {
    "number": 59,
    "title": "Infra-qizil spektrometr (FTIR)",
    "searchName": "Infra-qizil spektrometr (FTIR)",
    "model": "Bruker ALPHA II",
    "sourceKind": "purchase",
    "price": "$1,000–$8,000",
    "priceEvidence": "",
    "source": "",
    "priceStatus": "",
    "whereToBuy": "1. Ishlab chiqaruvchining rasmiy savdo kanali.\n2. Authorized distributor/integrator.\n3. O‘zbekistondagi laboratoriya uskunalari yetkazib beruvchisi.\n4. Used/refurbished — faqat texnik tekshiruv, servis tarixi va calibration hujjati bilan.",
    "purchaseRule": "",
    "availabilityUz": "Aynan `Bruker ALPHA II` uchun tayyor local stock holati ushbu bosqichda qat'iy tasdiqlanmagan. Mahalliy distributor/integratorga **model + konfiguratsiya** bilan RFQ yuborish kerak.",
    "importInfo": "Local stock bo‘lmasa, import qilinadi. RFQda model/catalog raqami, konfiguratsiya, ishlab chiqarilgan mamlakat, HS code, eksport qadoqlashi, kafolat, sertifikatlar va Incoterms alohida so‘raladi.",
    "delivery": "Transport narxi o‘lcham, og‘irlik, qadoqlash, kelib chiqish mamlakati va maxsus tashish talablariga bog‘liq. **EXW/FCA/DAP/DDP** shartlari quote'da aniq ko‘rsatilishi kerak.",
    "service": "- O‘zbekistonda authorized service bormi?\n- Kafolatni kim bajaradi?\n- Preventive maintenance davriyligi qanday?\n- Kalibrlash/verification talab qilinadimi?\n- Servis muhandisi kelish muddati qancha?\n\n**Status:** aynan `Bruker ALPHA II` uchun O‘zbekistondagi servis holati yozma tasdiqlanishi kerak.",
    "spares": "Xarid bilan birga modelga mos **wear parts, service kit, sensor/probe/filter/tubing va boshqa sarf qismlar** ro‘yxati, narxi va lead time'i olinadi.",
    "tco": "**TCO =** xarid + import/bojxona/QQS + transport + o‘rnatish + kalibrlash + servis + ehtiyot qismlar + sarf materiallari + elektr/suv/gaz + dasturiy litsenziyalar + operator o‘qitish.\n\n**Hozirgi TCO:** RFQ va yillik foydalanish hajmisiz yakuniy hisoblanmagan.",
    "redFlags": "",
    "finalStatus": "**Narx:** $1,000–$8,000\n**O‘zbekiston:** aynan model bo‘yicha RFQ kerak\n**Import:** local stockga qarab\n**Yetkazib berish:** konfiguratsiyaga bog‘liq\n**Servis:** yozma tasdiq kerak\n**Ehtiyot qismlar:** alohida BOM/quote kerak\n**TCO:** RFQdan keyin hisoblanadi\n\n---"
  },
    "60": {
    "number": 60,
    "title": "Ramanga spektroskopiyasi",
    "searchName": "Ramanga spektroskopiyasi",
    "model": "Renishaw inVia Raman Microscope",
    "sourceKind": "purchase",
    "price": "$3,000–$20,000",
    "priceEvidence": "",
    "source": "",
    "priceStatus": "",
    "whereToBuy": "1. Ishlab chiqaruvchining rasmiy savdo kanali.\n2. Authorized distributor/integrator.\n3. O‘zbekistondagi laboratoriya uskunalari yetkazib beruvchisi.\n4. Used/refurbished — faqat texnik tekshiruv, servis tarixi va calibration hujjati bilan.",
    "purchaseRule": "",
    "availabilityUz": "Aynan `Renishaw inVia Raman Microscope` uchun tayyor local stock holati ushbu bosqichda qat'iy tasdiqlanmagan. Mahalliy distributor/integratorga **model + konfiguratsiya** bilan RFQ yuborish kerak.",
    "importInfo": "Local stock bo‘lmasa, import qilinadi. RFQda model/catalog raqami, konfiguratsiya, ishlab chiqarilgan mamlakat, HS code, eksport qadoqlashi, kafolat, sertifikatlar va Incoterms alohida so‘raladi.",
    "delivery": "Transport narxi o‘lcham, og‘irlik, qadoqlash, kelib chiqish mamlakati va maxsus tashish talablariga bog‘liq. **EXW/FCA/DAP/DDP** shartlari quote'da aniq ko‘rsatilishi kerak.",
    "service": "- O‘zbekistonda authorized service bormi?\n- Kafolatni kim bajaradi?\n- Preventive maintenance davriyligi qanday?\n- Kalibrlash/verification talab qilinadimi?\n- Servis muhandisi kelish muddati qancha?\n\n**Status:** aynan `Renishaw inVia Raman Microscope` uchun O‘zbekistondagi servis holati yozma tasdiqlanishi kerak.",
    "spares": "Xarid bilan birga modelga mos **wear parts, service kit, sensor/probe/filter/tubing va boshqa sarf qismlar** ro‘yxati, narxi va lead time'i olinadi.",
    "tco": "**TCO =** xarid + import/bojxona/QQS + transport + o‘rnatish + kalibrlash + servis + ehtiyot qismlar + sarf materiallari + elektr/suv/gaz + dasturiy litsenziyalar + operator o‘qitish.\n\n**Hozirgi TCO:** RFQ va yillik foydalanish hajmisiz yakuniy hisoblanmagan.",
    "redFlags": "",
    "finalStatus": "**Narx:** $3,000–$20,000\n**O‘zbekiston:** aynan model bo‘yicha RFQ kerak\n**Import:** local stockga qarab\n**Yetkazib berish:** konfiguratsiyaga bog‘liq\n**Servis:** yozma tasdiq kerak\n**Ehtiyot qismlar:** alohida BOM/quote kerak\n**TCO:** RFQdan keyin hisoblanadi\n\n---"
  },
    "61": {
    "number": 61,
    "title": "Mikroto'm (Tissue sectioner)",
    "searchName": "Mikroto'm (Tissue sectioner)",
    "model": "Leica RM2255",
    "sourceKind": "purchase",
    "price": "$5,000–$30,000",
    "priceEvidence": "",
    "source": "",
    "priceStatus": "",
    "whereToBuy": "1. Ishlab chiqaruvchining rasmiy savdo kanali.\n2. Authorized distributor/integrator.\n3. O‘zbekistondagi laboratoriya uskunalari yetkazib beruvchisi.\n4. Used/refurbished — faqat texnik tekshiruv, servis tarixi va calibration hujjati bilan.",
    "purchaseRule": "",
    "availabilityUz": "Aynan `Leica RM2255` uchun tayyor local stock holati ushbu bosqichda qat'iy tasdiqlanmagan. Mahalliy distributor/integratorga **model + konfiguratsiya** bilan RFQ yuborish kerak.",
    "importInfo": "Local stock bo‘lmasa, import qilinadi. RFQda model/catalog raqami, konfiguratsiya, ishlab chiqarilgan mamlakat, HS code, eksport qadoqlashi, kafolat, sertifikatlar va Incoterms alohida so‘raladi.",
    "delivery": "Transport narxi o‘lcham, og‘irlik, qadoqlash, kelib chiqish mamlakati va maxsus tashish talablariga bog‘liq. **EXW/FCA/DAP/DDP** shartlari quote'da aniq ko‘rsatilishi kerak.",
    "service": "- O‘zbekistonda authorized service bormi?\n- Kafolatni kim bajaradi?\n- Preventive maintenance davriyligi qanday?\n- Kalibrlash/verification talab qilinadimi?\n- Servis muhandisi kelish muddati qancha?\n\n**Status:** aynan `Leica RM2255` uchun O‘zbekistondagi servis holati yozma tasdiqlanishi kerak.",
    "spares": "Xarid bilan birga modelga mos **wear parts, service kit, sensor/probe/filter/tubing va boshqa sarf qismlar** ro‘yxati, narxi va lead time'i olinadi.",
    "tco": "**TCO =** xarid + import/bojxona/QQS + transport + o‘rnatish + kalibrlash + servis + ehtiyot qismlar + sarf materiallari + elektr/suv/gaz + dasturiy litsenziyalar + operator o‘qitish.\n\n**Hozirgi TCO:** RFQ va yillik foydalanish hajmisiz yakuniy hisoblanmagan.",
    "redFlags": "",
    "finalStatus": "**Narx:** $5,000–$30,000\n**O‘zbekiston:** aynan model bo‘yicha RFQ kerak\n**Import:** local stockga qarab\n**Yetkazib berish:** konfiguratsiyaga bog‘liq\n**Servis:** yozma tasdiq kerak\n**Ehtiyot qismlar:** alohida BOM/quote kerak\n**TCO:** RFQdan keyin hisoblanadi\n\n---"
  },
    "62": {
    "number": 62,
    "title": "Kriostat",
    "searchName": "Kriostat",
    "model": "Leica CM3050 S",
    "sourceKind": "purchase",
    "price": "$2,000–$15,000",
    "priceEvidence": "",
    "source": "",
    "priceStatus": "",
    "whereToBuy": "1. Ishlab chiqaruvchining rasmiy savdo kanali.\n2. Authorized distributor/integrator.\n3. O‘zbekistondagi laboratoriya uskunalari yetkazib beruvchisi.\n4. Used/refurbished — faqat texnik tekshiruv, servis tarixi va calibration hujjati bilan.",
    "purchaseRule": "",
    "availabilityUz": "Aynan `Leica CM3050 S` uchun tayyor local stock holati ushbu bosqichda qat'iy tasdiqlanmagan. Mahalliy distributor/integratorga **model + konfiguratsiya** bilan RFQ yuborish kerak.",
    "importInfo": "Local stock bo‘lmasa, import qilinadi. RFQda model/catalog raqami, konfiguratsiya, ishlab chiqarilgan mamlakat, HS code, eksport qadoqlashi, kafolat, sertifikatlar va Incoterms alohida so‘raladi.",
    "delivery": "Transport narxi o‘lcham, og‘irlik, qadoqlash, kelib chiqish mamlakati va maxsus tashish talablariga bog‘liq. **EXW/FCA/DAP/DDP** shartlari quote'da aniq ko‘rsatilishi kerak.",
    "service": "- O‘zbekistonda authorized service bormi?\n- Kafolatni kim bajaradi?\n- Preventive maintenance davriyligi qanday?\n- Kalibrlash/verification talab qilinadimi?\n- Servis muhandisi kelish muddati qancha?\n\n**Status:** aynan `Leica CM3050 S` uchun O‘zbekistondagi servis holati yozma tasdiqlanishi kerak.",
    "spares": "Xarid bilan birga modelga mos **wear parts, service kit, sensor/probe/filter/tubing va boshqa sarf qismlar** ro‘yxati, narxi va lead time'i olinadi.",
    "tco": "**TCO =** xarid + import/bojxona/QQS + transport + o‘rnatish + kalibrlash + servis + ehtiyot qismlar + sarf materiallari + elektr/suv/gaz + dasturiy litsenziyalar + operator o‘qitish.\n\n**Hozirgi TCO:** RFQ va yillik foydalanish hajmisiz yakuniy hisoblanmagan.",
    "redFlags": "",
    "finalStatus": "**Narx:** $2,000–$15,000\n**O‘zbekiston:** aynan model bo‘yicha RFQ kerak\n**Import:** local stockga qarab\n**Yetkazib berish:** konfiguratsiyaga bog‘liq\n**Servis:** yozma tasdiq kerak\n**Ehtiyot qismlar:** alohida BOM/quote kerak\n**TCO:** RFQdan keyin hisoblanadi\n\n---"
  },
    "63": {
    "number": 63,
    "title": "Immuno-xistokimyo (IHC) stantsiyasi",
    "searchName": "Immuno-xistokimyo (IHC) stantsiyasi",
    "model": "Leica BOND-III",
    "sourceKind": "purchase",
    "price": "$2,000–$20,000",
    "priceEvidence": "",
    "source": "",
    "priceStatus": "",
    "whereToBuy": "1. Ishlab chiqaruvchining rasmiy savdo kanali.\n2. Authorized distributor/integrator.\n3. O‘zbekistondagi laboratoriya uskunalari yetkazib beruvchisi.\n4. Used/refurbished — faqat texnik tekshiruv, servis tarixi va calibration hujjati bilan.",
    "purchaseRule": "",
    "availabilityUz": "Aynan `Leica BOND-III` uchun tayyor local stock holati ushbu bosqichda qat'iy tasdiqlanmagan. Mahalliy distributor/integratorga **model + konfiguratsiya** bilan RFQ yuborish kerak.",
    "importInfo": "Local stock bo‘lmasa, import qilinadi. RFQda model/catalog raqami, konfiguratsiya, ishlab chiqarilgan mamlakat, HS code, eksport qadoqlashi, kafolat, sertifikatlar va Incoterms alohida so‘raladi.",
    "delivery": "Transport narxi o‘lcham, og‘irlik, qadoqlash, kelib chiqish mamlakati va maxsus tashish talablariga bog‘liq. **EXW/FCA/DAP/DDP** shartlari quote'da aniq ko‘rsatilishi kerak.",
    "service": "- O‘zbekistonda authorized service bormi?\n- Kafolatni kim bajaradi?\n- Preventive maintenance davriyligi qanday?\n- Kalibrlash/verification talab qilinadimi?\n- Servis muhandisi kelish muddati qancha?\n\n**Status:** aynan `Leica BOND-III` uchun O‘zbekistondagi servis holati yozma tasdiqlanishi kerak.",
    "spares": "Xarid bilan birga modelga mos **wear parts, service kit, sensor/probe/filter/tubing va boshqa sarf qismlar** ro‘yxati, narxi va lead time'i olinadi.",
    "tco": "**TCO =** xarid + import/bojxona/QQS + transport + o‘rnatish + kalibrlash + servis + ehtiyot qismlar + sarf materiallari + elektr/suv/gaz + dasturiy litsenziyalar + operator o‘qitish.\n\n**Hozirgi TCO:** RFQ va yillik foydalanish hajmisiz yakuniy hisoblanmagan.",
    "redFlags": "",
    "finalStatus": "**Narx:** $2,000–$20,000\n**O‘zbekiston:** aynan model bo‘yicha RFQ kerak\n**Import:** local stockga qarab\n**Yetkazib berish:** konfiguratsiyaga bog‘liq\n**Servis:** yozma tasdiq kerak\n**Ehtiyot qismlar:** alohida BOM/quote kerak\n**TCO:** RFQdan keyin hisoblanadi\n\n---"
  },
    "64": {
    "number": 64,
    "title": "Avtomatik bo'yash qurilmasi (stainer)",
    "searchName": "Avtomatik bo'yash qurilmasi (stainer)",
    "model": "Sakura Tissue-Tek Prisma Plus",
    "sourceKind": "purchase",
    "price": "$1,000–$8,000",
    "priceEvidence": "",
    "source": "",
    "priceStatus": "",
    "whereToBuy": "1. Ishlab chiqaruvchining rasmiy savdo kanali.\n2. Authorized distributor/integrator.\n3. O‘zbekistondagi laboratoriya uskunalari yetkazib beruvchisi.\n4. Used/refurbished — faqat texnik tekshiruv, servis tarixi va calibration hujjati bilan.",
    "purchaseRule": "",
    "availabilityUz": "Aynan `Sakura Tissue-Tek Prisma Plus` uchun tayyor local stock holati ushbu bosqichda qat'iy tasdiqlanmagan. Mahalliy distributor/integratorga **model + konfiguratsiya** bilan RFQ yuborish kerak.",
    "importInfo": "Local stock bo‘lmasa, import qilinadi. RFQda model/catalog raqami, konfiguratsiya, ishlab chiqarilgan mamlakat, HS code, eksport qadoqlashi, kafolat, sertifikatlar va Incoterms alohida so‘raladi.",
    "delivery": "Transport narxi o‘lcham, og‘irlik, qadoqlash, kelib chiqish mamlakati va maxsus tashish talablariga bog‘liq. **EXW/FCA/DAP/DDP** shartlari quote'da aniq ko‘rsatilishi kerak.",
    "service": "- O‘zbekistonda authorized service bormi?\n- Kafolatni kim bajaradi?\n- Preventive maintenance davriyligi qanday?\n- Kalibrlash/verification talab qilinadimi?\n- Servis muhandisi kelish muddati qancha?\n\n**Status:** aynan `Sakura Tissue-Tek Prisma Plus` uchun O‘zbekistondagi servis holati yozma tasdiqlanishi kerak.",
    "spares": "Xarid bilan birga modelga mos **wear parts, service kit, sensor/probe/filter/tubing va boshqa sarf qismlar** ro‘yxati, narxi va lead time'i olinadi.",
    "tco": "**TCO =** xarid + import/bojxona/QQS + transport + o‘rnatish + kalibrlash + servis + ehtiyot qismlar + sarf materiallari + elektr/suv/gaz + dasturiy litsenziyalar + operator o‘qitish.\n\n**Hozirgi TCO:** RFQ va yillik foydalanish hajmisiz yakuniy hisoblanmagan.",
    "redFlags": "",
    "finalStatus": "**Narx:** $1,000–$8,000\n**O‘zbekiston:** aynan model bo‘yicha RFQ kerak\n**Import:** local stockga qarab\n**Yetkazib berish:** konfiguratsiyaga bog‘liq\n**Servis:** yozma tasdiq kerak\n**Ehtiyot qismlar:** alohida BOM/quote kerak\n**TCO:** RFQdan keyin hisoblanadi\n\n---"
  },
    "65": {
    "number": 65,
    "title": "Mikromanipulyator",
    "searchName": "Mikromanipulyator",
    "model": "Eppendorf TransferMan 4r",
    "sourceKind": "purchase",
    "price": "$2,000–$15,000",
    "priceEvidence": "",
    "source": "",
    "priceStatus": "",
    "whereToBuy": "1. Ishlab chiqaruvchining rasmiy savdo kanali.\n2. Authorized distributor/integrator.\n3. O‘zbekistondagi laboratoriya uskunalari yetkazib beruvchisi.\n4. Used/refurbished — faqat texnik tekshiruv, servis tarixi va calibration hujjati bilan.",
    "purchaseRule": "",
    "availabilityUz": "Aynan `Eppendorf TransferMan 4r` uchun tayyor local stock holati ushbu bosqichda qat'iy tasdiqlanmagan. Mahalliy distributor/integratorga **model + konfiguratsiya** bilan RFQ yuborish kerak.",
    "importInfo": "Local stock bo‘lmasa, import qilinadi. RFQda model/catalog raqami, konfiguratsiya, ishlab chiqarilgan mamlakat, HS code, eksport qadoqlashi, kafolat, sertifikatlar va Incoterms alohida so‘raladi.",
    "delivery": "Transport narxi o‘lcham, og‘irlik, qadoqlash, kelib chiqish mamlakati va maxsus tashish talablariga bog‘liq. **EXW/FCA/DAP/DDP** shartlari quote'da aniq ko‘rsatilishi kerak.",
    "service": "- O‘zbekistonda authorized service bormi?\n- Kafolatni kim bajaradi?\n- Preventive maintenance davriyligi qanday?\n- Kalibrlash/verification talab qilinadimi?\n- Servis muhandisi kelish muddati qancha?\n\n**Status:** aynan `Eppendorf TransferMan 4r` uchun O‘zbekistondagi servis holati yozma tasdiqlanishi kerak.",
    "spares": "Xarid bilan birga modelga mos **wear parts, service kit, sensor/probe/filter/tubing va boshqa sarf qismlar** ro‘yxati, narxi va lead time'i olinadi.",
    "tco": "**TCO =** xarid + import/bojxona/QQS + transport + o‘rnatish + kalibrlash + servis + ehtiyot qismlar + sarf materiallari + elektr/suv/gaz + dasturiy litsenziyalar + operator o‘qitish.\n\n**Hozirgi TCO:** RFQ va yillik foydalanish hajmisiz yakuniy hisoblanmagan.",
    "redFlags": "",
    "finalStatus": "**Narx:** $2,000–$15,000\n**O‘zbekiston:** aynan model bo‘yicha RFQ kerak\n**Import:** local stockga qarab\n**Yetkazib berish:** konfiguratsiyaga bog‘liq\n**Servis:** yozma tasdiq kerak\n**Ehtiyot qismlar:** alohida BOM/quote kerak\n**TCO:** RFQdan keyin hisoblanadi\n\n---"
  },
    "66": {
    "number": 66,
    "title": "Elektroporatsion sistema",
    "searchName": "Elektroporatsion sistema",
    "model": "Bio-Rad Gene Pulser Xcell",
    "sourceKind": "purchase",
    "price": "$1,000–$7,000",
    "priceEvidence": "",
    "source": "",
    "priceStatus": "",
    "whereToBuy": "1. Ishlab chiqaruvchining rasmiy savdo kanali.\n2. Authorized distributor/integrator.\n3. O‘zbekistondagi laboratoriya uskunalari yetkazib beruvchisi.\n4. Used/refurbished — faqat texnik tekshiruv, servis tarixi va calibration hujjati bilan.",
    "purchaseRule": "",
    "availabilityUz": "Aynan `Bio-Rad Gene Pulser Xcell` uchun tayyor local stock holati ushbu bosqichda qat'iy tasdiqlanmagan. Mahalliy distributor/integratorga **model + konfiguratsiya** bilan RFQ yuborish kerak.",
    "importInfo": "Local stock bo‘lmasa, import qilinadi. RFQda model/catalog raqami, konfiguratsiya, ishlab chiqarilgan mamlakat, HS code, eksport qadoqlashi, kafolat, sertifikatlar va Incoterms alohida so‘raladi.",
    "delivery": "Transport narxi o‘lcham, og‘irlik, qadoqlash, kelib chiqish mamlakati va maxsus tashish talablariga bog‘liq. **EXW/FCA/DAP/DDP** shartlari quote'da aniq ko‘rsatilishi kerak.",
    "service": "- O‘zbekistonda authorized service bormi?\n- Kafolatni kim bajaradi?\n- Preventive maintenance davriyligi qanday?\n- Kalibrlash/verification talab qilinadimi?\n- Servis muhandisi kelish muddati qancha?\n\n**Status:** aynan `Bio-Rad Gene Pulser Xcell` uchun O‘zbekistondagi servis holati yozma tasdiqlanishi kerak.",
    "spares": "Xarid bilan birga modelga mos **wear parts, service kit, sensor/probe/filter/tubing va boshqa sarf qismlar** ro‘yxati, narxi va lead time'i olinadi.",
    "tco": "**TCO =** xarid + import/bojxona/QQS + transport + o‘rnatish + kalibrlash + servis + ehtiyot qismlar + sarf materiallari + elektr/suv/gaz + dasturiy litsenziyalar + operator o‘qitish.\n\n**Hozirgi TCO:** RFQ va yillik foydalanish hajmisiz yakuniy hisoblanmagan.",
    "redFlags": "",
    "finalStatus": "**Narx:** $1,000–$7,000\n**O‘zbekiston:** aynan model bo‘yicha RFQ kerak\n**Import:** local stockga qarab\n**Yetkazib berish:** konfiguratsiyaga bog‘liq\n**Servis:** yozma tasdiq kerak\n**Ehtiyot qismlar:** alohida BOM/quote kerak\n**TCO:** RFQdan keyin hisoblanadi\n\n---"
  },
    "67": {
    "number": 67,
    "title": "Bioprinter (3D biologik bosib chiqarish)",
    "searchName": "Bioprinter (3D biologik bosib chiqarish)",
    "model": "CELLINK BIO X6",
    "sourceKind": "purchase",
    "price": "$2,000–$15,000",
    "priceEvidence": "",
    "source": "",
    "priceStatus": "",
    "whereToBuy": "1. Ishlab chiqaruvchining rasmiy savdo kanali.\n2. Authorized distributor/integrator.\n3. O‘zbekistondagi laboratoriya uskunalari yetkazib beruvchisi.\n4. Used/refurbished — faqat texnik tekshiruv, servis tarixi va calibration hujjati bilan.",
    "purchaseRule": "",
    "availabilityUz": "Aynan `CELLINK BIO X6` uchun tayyor local stock holati ushbu bosqichda qat'iy tasdiqlanmagan. Mahalliy distributor/integratorga **model + konfiguratsiya** bilan RFQ yuborish kerak.",
    "importInfo": "Local stock bo‘lmasa, import qilinadi. RFQda model/catalog raqami, konfiguratsiya, ishlab chiqarilgan mamlakat, HS code, eksport qadoqlashi, kafolat, sertifikatlar va Incoterms alohida so‘raladi.",
    "delivery": "Transport narxi o‘lcham, og‘irlik, qadoqlash, kelib chiqish mamlakati va maxsus tashish talablariga bog‘liq. **EXW/FCA/DAP/DDP** shartlari quote'da aniq ko‘rsatilishi kerak.",
    "service": "- O‘zbekistonda authorized service bormi?\n- Kafolatni kim bajaradi?\n- Preventive maintenance davriyligi qanday?\n- Kalibrlash/verification talab qilinadimi?\n- Servis muhandisi kelish muddati qancha?\n\n**Status:** aynan `CELLINK BIO X6` uchun O‘zbekistondagi servis holati yozma tasdiqlanishi kerak.",
    "spares": "Xarid bilan birga modelga mos **wear parts, service kit, sensor/probe/filter/tubing va boshqa sarf qismlar** ro‘yxati, narxi va lead time'i olinadi.",
    "tco": "**TCO =** xarid + import/bojxona/QQS + transport + o‘rnatish + kalibrlash + servis + ehtiyot qismlar + sarf materiallari + elektr/suv/gaz + dasturiy litsenziyalar + operator o‘qitish.\n\n**Hozirgi TCO:** RFQ va yillik foydalanish hajmisiz yakuniy hisoblanmagan.",
    "redFlags": "",
    "finalStatus": "**Narx:** $2,000–$15,000\n**O‘zbekiston:** aynan model bo‘yicha RFQ kerak\n**Import:** local stockga qarab\n**Yetkazib berish:** konfiguratsiyaga bog‘liq\n**Servis:** yozma tasdiq kerak\n**Ehtiyot qismlar:** alohida BOM/quote kerak\n**TCO:** RFQdan keyin hisoblanadi\n\n---"
  },
    "68": {
    "number": 68,
    "title": "Spray dryer / nano spray dryer",
    "searchName": "Spray dryer / nano spray dryer",
    "model": "Buchi Nano Spray Dryer B-90 HP",
    "sourceKind": "purchase",
    "price": "$3,000–$25,000",
    "priceEvidence": "",
    "source": "",
    "priceStatus": "",
    "whereToBuy": "1. Ishlab chiqaruvchining rasmiy savdo kanali.\n2. Authorized distributor/integrator.\n3. O‘zbekistondagi laboratoriya uskunalari yetkazib beruvchisi.\n4. Used/refurbished — faqat texnik tekshiruv, servis tarixi va calibration hujjati bilan.",
    "purchaseRule": "",
    "availabilityUz": "Aynan `Buchi Nano Spray Dryer B-90 HP` uchun tayyor local stock holati ushbu bosqichda qat'iy tasdiqlanmagan. Mahalliy distributor/integratorga **model + konfiguratsiya** bilan RFQ yuborish kerak.",
    "importInfo": "Local stock bo‘lmasa, import qilinadi. RFQda model/catalog raqami, konfiguratsiya, ishlab chiqarilgan mamlakat, HS code, eksport qadoqlashi, kafolat, sertifikatlar va Incoterms alohida so‘raladi.",
    "delivery": "Transport narxi o‘lcham, og‘irlik, qadoqlash, kelib chiqish mamlakati va maxsus tashish talablariga bog‘liq. **EXW/FCA/DAP/DDP** shartlari quote'da aniq ko‘rsatilishi kerak.",
    "service": "- O‘zbekistonda authorized service bormi?\n- Kafolatni kim bajaradi?\n- Preventive maintenance davriyligi qanday?\n- Kalibrlash/verification talab qilinadimi?\n- Servis muhandisi kelish muddati qancha?\n\n**Status:** aynan `Buchi Nano Spray Dryer B-90 HP` uchun O‘zbekistondagi servis holati yozma tasdiqlanishi kerak.",
    "spares": "Xarid bilan birga modelga mos **wear parts, service kit, sensor/probe/filter/tubing va boshqa sarf qismlar** ro‘yxati, narxi va lead time'i olinadi.",
    "tco": "**TCO =** xarid + import/bojxona/QQS + transport + o‘rnatish + kalibrlash + servis + ehtiyot qismlar + sarf materiallari + elektr/suv/gaz + dasturiy litsenziyalar + operator o‘qitish.\n\n**Hozirgi TCO:** RFQ va yillik foydalanish hajmisiz yakuniy hisoblanmagan.",
    "redFlags": "",
    "finalStatus": "**Narx:** $3,000–$25,000\n**O‘zbekiston:** aynan model bo‘yicha RFQ kerak\n**Import:** local stockga qarab\n**Yetkazib berish:** konfiguratsiyaga bog‘liq\n**Servis:** yozma tasdiq kerak\n**Ehtiyot qismlar:** alohida BOM/quote kerak\n**TCO:** RFQdan keyin hisoblanadi\n\n---"
  },
    "69": {
    "number": 69,
    "title": "Dinamik yorug'lik sochilishi (DLS)",
    "searchName": "Dinamik yorug'lik sochilishi (DLS)",
    "model": "Malvern Panalytical Zetasizer Ultra",
    "sourceKind": "purchase",
    "price": "$2,000–$20,000",
    "priceEvidence": "",
    "source": "",
    "priceStatus": "",
    "whereToBuy": "1. Ishlab chiqaruvchining rasmiy savdo kanali.\n2. Authorized distributor/integrator.\n3. O‘zbekistondagi laboratoriya uskunalari yetkazib beruvchisi.\n4. Used/refurbished — faqat texnik tekshiruv, servis tarixi va calibration hujjati bilan.",
    "purchaseRule": "",
    "availabilityUz": "Aynan `Malvern Panalytical Zetasizer Ultra` uchun tayyor local stock holati ushbu bosqichda qat'iy tasdiqlanmagan. Mahalliy distributor/integratorga **model + konfiguratsiya** bilan RFQ yuborish kerak.",
    "importInfo": "Local stock bo‘lmasa, import qilinadi. RFQda model/catalog raqami, konfiguratsiya, ishlab chiqarilgan mamlakat, HS code, eksport qadoqlashi, kafolat, sertifikatlar va Incoterms alohida so‘raladi.",
    "delivery": "Transport narxi o‘lcham, og‘irlik, qadoqlash, kelib chiqish mamlakati va maxsus tashish talablariga bog‘liq. **EXW/FCA/DAP/DDP** shartlari quote'da aniq ko‘rsatilishi kerak.",
    "service": "- O‘zbekistonda authorized service bormi?\n- Kafolatni kim bajaradi?\n- Preventive maintenance davriyligi qanday?\n- Kalibrlash/verification talab qilinadimi?\n- Servis muhandisi kelish muddati qancha?\n\n**Status:** aynan `Malvern Panalytical Zetasizer Ultra` uchun O‘zbekistondagi servis holati yozma tasdiqlanishi kerak.",
    "spares": "Xarid bilan birga modelga mos **wear parts, service kit, sensor/probe/filter/tubing va boshqa sarf qismlar** ro‘yxati, narxi va lead time'i olinadi.",
    "tco": "**TCO =** xarid + import/bojxona/QQS + transport + o‘rnatish + kalibrlash + servis + ehtiyot qismlar + sarf materiallari + elektr/suv/gaz + dasturiy litsenziyalar + operator o‘qitish.\n\n**Hozirgi TCO:** RFQ va yillik foydalanish hajmisiz yakuniy hisoblanmagan.",
    "redFlags": "",
    "finalStatus": "**Narx:** $2,000–$20,000\n**O‘zbekiston:** aynan model bo‘yicha RFQ kerak\n**Import:** local stockga qarab\n**Yetkazib berish:** konfiguratsiyaga bog‘liq\n**Servis:** yozma tasdiq kerak\n**Ehtiyot qismlar:** alohida BOM/quote kerak\n**TCO:** RFQdan keyin hisoblanadi\n\n---"
  },
    "70": {
    "number": 70,
    "title": "Lateral-flow tezkor diagnostika testi",
    "searchName": "Lateral-flow tezkor diagnostika testi",
    "model": "SD Biosensor Standard F (multiplex)",
    "sourceKind": "purchase",
    "price": "$1,000–$10,000",
    "priceEvidence": "",
    "source": "",
    "priceStatus": "",
    "whereToBuy": "1. Ishlab chiqaruvchining rasmiy savdo kanali.\n2. Authorized distributor/integrator.\n3. O‘zbekistondagi laboratoriya uskunalari yetkazib beruvchisi.\n4. Used/refurbished — faqat texnik tekshiruv, servis tarixi va calibration hujjati bilan.",
    "purchaseRule": "",
    "availabilityUz": "Aynan `SD Biosensor Standard F (multiplex)` uchun tayyor local stock holati ushbu bosqichda qat'iy tasdiqlanmagan. Mahalliy distributor/integratorga **model + konfiguratsiya** bilan RFQ yuborish kerak.",
    "importInfo": "Local stock bo‘lmasa, import qilinadi. RFQda model/catalog raqami, konfiguratsiya, ishlab chiqarilgan mamlakat, HS code, eksport qadoqlashi, kafolat, sertifikatlar va Incoterms alohida so‘raladi.",
    "delivery": "Transport narxi o‘lcham, og‘irlik, qadoqlash, kelib chiqish mamlakati va maxsus tashish talablariga bog‘liq. **EXW/FCA/DAP/DDP** shartlari quote'da aniq ko‘rsatilishi kerak.",
    "service": "- O‘zbekistonda authorized service bormi?\n- Kafolatni kim bajaradi?\n- Preventive maintenance davriyligi qanday?\n- Kalibrlash/verification talab qilinadimi?\n- Servis muhandisi kelish muddati qancha?\n\n**Status:** aynan `SD Biosensor Standard F (multiplex)` uchun O‘zbekistondagi servis holati yozma tasdiqlanishi kerak.",
    "spares": "Xarid bilan birga modelga mos **wear parts, service kit, sensor/probe/filter/tubing va boshqa sarf qismlar** ro‘yxati, narxi va lead time'i olinadi.",
    "tco": "**TCO =** xarid + import/bojxona/QQS + transport + o‘rnatish + kalibrlash + servis + ehtiyot qismlar + sarf materiallari + elektr/suv/gaz + dasturiy litsenziyalar + operator o‘qitish.\n\n**Hozirgi TCO:** RFQ va yillik foydalanish hajmisiz yakuniy hisoblanmagan.",
    "redFlags": "",
    "finalStatus": "**Narx:** $1,000–$10,000\n**O‘zbekiston:** aynan model bo‘yicha RFQ kerak\n**Import:** local stockga qarab\n**Yetkazib berish:** konfiguratsiyaga bog‘liq\n**Servis:** yozma tasdiq kerak\n**Ehtiyot qismlar:** alohida BOM/quote kerak\n**TCO:** RFQdan keyin hisoblanadi\n\n---"
  },
    "71": {
    "number": 71,
    "title": "MALDI-TOF massa spektrometr",
    "searchName": "MALDI-TOF massa spektrometr",
    "model": "Bruker Microflex LT/SH",
    "sourceKind": "purchase",
    "price": "$2,000–$15,000",
    "priceEvidence": "",
    "source": "",
    "priceStatus": "",
    "whereToBuy": "1. Ishlab chiqaruvchining rasmiy savdo kanali.\n2. Authorized distributor/integrator.\n3. O‘zbekistondagi laboratoriya uskunalari yetkazib beruvchisi.\n4. Used/refurbished — faqat texnik tekshiruv, servis tarixi va calibration hujjati bilan.",
    "purchaseRule": "",
    "availabilityUz": "Aynan `Bruker Microflex LT/SH` uchun tayyor local stock holati ushbu bosqichda qat'iy tasdiqlanmagan. Mahalliy distributor/integratorga **model + konfiguratsiya** bilan RFQ yuborish kerak.",
    "importInfo": "Local stock bo‘lmasa, import qilinadi. RFQda model/catalog raqami, konfiguratsiya, ishlab chiqarilgan mamlakat, HS code, eksport qadoqlashi, kafolat, sertifikatlar va Incoterms alohida so‘raladi.",
    "delivery": "Transport narxi o‘lcham, og‘irlik, qadoqlash, kelib chiqish mamlakati va maxsus tashish talablariga bog‘liq. **EXW/FCA/DAP/DDP** shartlari quote'da aniq ko‘rsatilishi kerak.",
    "service": "- O‘zbekistonda authorized service bormi?\n- Kafolatni kim bajaradi?\n- Preventive maintenance davriyligi qanday?\n- Kalibrlash/verification talab qilinadimi?\n- Servis muhandisi kelish muddati qancha?\n\n**Status:** aynan `Bruker Microflex LT/SH` uchun O‘zbekistondagi servis holati yozma tasdiqlanishi kerak.",
    "spares": "Xarid bilan birga modelga mos **wear parts, service kit, sensor/probe/filter/tubing va boshqa sarf qismlar** ro‘yxati, narxi va lead time'i olinadi.",
    "tco": "**TCO =** xarid + import/bojxona/QQS + transport + o‘rnatish + kalibrlash + servis + ehtiyot qismlar + sarf materiallari + elektr/suv/gaz + dasturiy litsenziyalar + operator o‘qitish.\n\n**Hozirgi TCO:** RFQ va yillik foydalanish hajmisiz yakuniy hisoblanmagan.",
    "redFlags": "",
    "finalStatus": "**Narx:** $2,000–$15,000\n**O‘zbekiston:** aynan model bo‘yicha RFQ kerak\n**Import:** local stockga qarab\n**Yetkazib berish:** konfiguratsiyaga bog‘liq\n**Servis:** yozma tasdiq kerak\n**Ehtiyot qismlar:** alohida BOM/quote kerak\n**TCO:** RFQdan keyin hisoblanadi\n\n---"
  },
    "72": {
    "number": 72,
    "title": "Bioimpedans tahlilchi",
    "searchName": "Bioimpedans tahlilchi",
    "model": "Impedimed SFB7",
    "sourceKind": "purchase",
    "price": "$5,000–$40,000",
    "priceEvidence": "",
    "source": "",
    "priceStatus": "",
    "whereToBuy": "1. Ishlab chiqaruvchining rasmiy savdo kanali.\n2. Authorized distributor/integrator.\n3. O‘zbekistondagi laboratoriya uskunalari yetkazib beruvchisi.\n4. Used/refurbished — faqat texnik tekshiruv, servis tarixi va calibration hujjati bilan.",
    "purchaseRule": "",
    "availabilityUz": "Aynan `Impedimed SFB7` uchun tayyor local stock holati ushbu bosqichda qat'iy tasdiqlanmagan. Mahalliy distributor/integratorga **model + konfiguratsiya** bilan RFQ yuborish kerak.",
    "importInfo": "Local stock bo‘lmasa, import qilinadi. RFQda model/catalog raqami, konfiguratsiya, ishlab chiqarilgan mamlakat, HS code, eksport qadoqlashi, kafolat, sertifikatlar va Incoterms alohida so‘raladi.",
    "delivery": "Transport narxi o‘lcham, og‘irlik, qadoqlash, kelib chiqish mamlakati va maxsus tashish talablariga bog‘liq. **EXW/FCA/DAP/DDP** shartlari quote'da aniq ko‘rsatilishi kerak.",
    "service": "- O‘zbekistonda authorized service bormi?\n- Kafolatni kim bajaradi?\n- Preventive maintenance davriyligi qanday?\n- Kalibrlash/verification talab qilinadimi?\n- Servis muhandisi kelish muddati qancha?\n\n**Status:** aynan `Impedimed SFB7` uchun O‘zbekistondagi servis holati yozma tasdiqlanishi kerak.",
    "spares": "Xarid bilan birga modelga mos **wear parts, service kit, sensor/probe/filter/tubing va boshqa sarf qismlar** ro‘yxati, narxi va lead time'i olinadi.",
    "tco": "**TCO =** xarid + import/bojxona/QQS + transport + o‘rnatish + kalibrlash + servis + ehtiyot qismlar + sarf materiallari + elektr/suv/gaz + dasturiy litsenziyalar + operator o‘qitish.\n\n**Hozirgi TCO:** RFQ va yillik foydalanish hajmisiz yakuniy hisoblanmagan.",
    "redFlags": "",
    "finalStatus": "**Narx:** $5,000–$40,000\n**O‘zbekiston:** aynan model bo‘yicha RFQ kerak\n**Import:** local stockga qarab\n**Yetkazib berish:** konfiguratsiyaga bog‘liq\n**Servis:** yozma tasdiq kerak\n**Ehtiyot qismlar:** alohida BOM/quote kerak\n**TCO:** RFQdan keyin hisoblanadi\n\n---"
  },
    "73": {
    "number": 73,
    "title": "Termal tahlil qurilmasi (DSC)",
    "searchName": "Termal tahlil qurilmasi (DSC)",
    "model": "TA Instruments DSC 250",
    "sourceKind": "purchase",
    "price": "$1,000–$8,000",
    "priceEvidence": "",
    "source": "",
    "priceStatus": "",
    "whereToBuy": "1. Ishlab chiqaruvchining rasmiy savdo kanali.\n2. Authorized distributor/integrator.\n3. O‘zbekistondagi laboratoriya uskunalari yetkazib beruvchisi.\n4. Used/refurbished — faqat texnik tekshiruv, servis tarixi va calibration hujjati bilan.",
    "purchaseRule": "",
    "availabilityUz": "Aynan `TA Instruments DSC 250` uchun tayyor local stock holati ushbu bosqichda qat'iy tasdiqlanmagan. Mahalliy distributor/integratorga **model + konfiguratsiya** bilan RFQ yuborish kerak.",
    "importInfo": "Local stock bo‘lmasa, import qilinadi. RFQda model/catalog raqami, konfiguratsiya, ishlab chiqarilgan mamlakat, HS code, eksport qadoqlashi, kafolat, sertifikatlar va Incoterms alohida so‘raladi.",
    "delivery": "Transport narxi o‘lcham, og‘irlik, qadoqlash, kelib chiqish mamlakati va maxsus tashish talablariga bog‘liq. **EXW/FCA/DAP/DDP** shartlari quote'da aniq ko‘rsatilishi kerak.",
    "service": "- O‘zbekistonda authorized service bormi?\n- Kafolatni kim bajaradi?\n- Preventive maintenance davriyligi qanday?\n- Kalibrlash/verification talab qilinadimi?\n- Servis muhandisi kelish muddati qancha?\n\n**Status:** aynan `TA Instruments DSC 250` uchun O‘zbekistondagi servis holati yozma tasdiqlanishi kerak.",
    "spares": "Xarid bilan birga modelga mos **wear parts, service kit, sensor/probe/filter/tubing va boshqa sarf qismlar** ro‘yxati, narxi va lead time'i olinadi.",
    "tco": "**TCO =** xarid + import/bojxona/QQS + transport + o‘rnatish + kalibrlash + servis + ehtiyot qismlar + sarf materiallari + elektr/suv/gaz + dasturiy litsenziyalar + operator o‘qitish.\n\n**Hozirgi TCO:** RFQ va yillik foydalanish hajmisiz yakuniy hisoblanmagan.",
    "redFlags": "",
    "finalStatus": "**Narx:** $1,000–$8,000\n**O‘zbekiston:** aynan model bo‘yicha RFQ kerak\n**Import:** local stockga qarab\n**Yetkazib berish:** konfiguratsiyaga bog‘liq\n**Servis:** yozma tasdiq kerak\n**Ehtiyot qismlar:** alohida BOM/quote kerak\n**TCO:** RFQdan keyin hisoblanadi\n\n---"
  },
    "74": {
    "number": 74,
    "title": "Rotary evaporator (rotovap)",
    "searchName": "Rotary evaporator (rotovap)",
    "model": "Buchi R-300",
    "sourceKind": "purchase",
    "price": "$2,000–$20,000",
    "priceEvidence": "",
    "source": "",
    "priceStatus": "",
    "whereToBuy": "1. Ishlab chiqaruvchining rasmiy savdo kanali.\n2. Authorized distributor/integrator.\n3. O‘zbekistondagi laboratoriya uskunalari yetkazib beruvchisi.\n4. Used/refurbished — faqat texnik tekshiruv, servis tarixi va calibration hujjati bilan.",
    "purchaseRule": "",
    "availabilityUz": "Aynan `Buchi R-300` uchun tayyor local stock holati ushbu bosqichda qat'iy tasdiqlanmagan. Mahalliy distributor/integratorga **model + konfiguratsiya** bilan RFQ yuborish kerak.",
    "importInfo": "Local stock bo‘lmasa, import qilinadi. RFQda model/catalog raqami, konfiguratsiya, ishlab chiqarilgan mamlakat, HS code, eksport qadoqlashi, kafolat, sertifikatlar va Incoterms alohida so‘raladi.",
    "delivery": "Transport narxi o‘lcham, og‘irlik, qadoqlash, kelib chiqish mamlakati va maxsus tashish talablariga bog‘liq. **EXW/FCA/DAP/DDP** shartlari quote'da aniq ko‘rsatilishi kerak.",
    "service": "- O‘zbekistonda authorized service bormi?\n- Kafolatni kim bajaradi?\n- Preventive maintenance davriyligi qanday?\n- Kalibrlash/verification talab qilinadimi?\n- Servis muhandisi kelish muddati qancha?\n\n**Status:** aynan `Buchi R-300` uchun O‘zbekistondagi servis holati yozma tasdiqlanishi kerak.",
    "spares": "Xarid bilan birga modelga mos **wear parts, service kit, sensor/probe/filter/tubing va boshqa sarf qismlar** ro‘yxati, narxi va lead time'i olinadi.",
    "tco": "**TCO =** xarid + import/bojxona/QQS + transport + o‘rnatish + kalibrlash + servis + ehtiyot qismlar + sarf materiallari + elektr/suv/gaz + dasturiy litsenziyalar + operator o‘qitish.\n\n**Hozirgi TCO:** RFQ va yillik foydalanish hajmisiz yakuniy hisoblanmagan.",
    "redFlags": "",
    "finalStatus": "**Narx:** $2,000–$20,000\n**O‘zbekiston:** aynan model bo‘yicha RFQ kerak\n**Import:** local stockga qarab\n**Yetkazib berish:** konfiguratsiyaga bog‘liq\n**Servis:** yozma tasdiq kerak\n**Ehtiyot qismlar:** alohida BOM/quote kerak\n**TCO:** RFQdan keyin hisoblanadi\n\n---"
  },
    "75": {
    "number": 75,
    "title": "Sonikator (bath type)",
    "searchName": "Sonikator (bath type)",
    "model": "Elmasonic S60H",
    "sourceKind": "purchase",
    "price": "$3,000–$25,000",
    "priceEvidence": "",
    "source": "",
    "priceStatus": "",
    "whereToBuy": "1. Ishlab chiqaruvchining rasmiy savdo kanali.\n2. Authorized distributor/integrator.\n3. O‘zbekistondagi laboratoriya uskunalari yetkazib beruvchisi.\n4. Used/refurbished — faqat texnik tekshiruv, servis tarixi va calibration hujjati bilan.",
    "purchaseRule": "",
    "availabilityUz": "Aynan `Elmasonic S60H` uchun tayyor local stock holati ushbu bosqichda qat'iy tasdiqlanmagan. Mahalliy distributor/integratorga **model + konfiguratsiya** bilan RFQ yuborish kerak.",
    "importInfo": "Local stock bo‘lmasa, import qilinadi. RFQda model/catalog raqami, konfiguratsiya, ishlab chiqarilgan mamlakat, HS code, eksport qadoqlashi, kafolat, sertifikatlar va Incoterms alohida so‘raladi.",
    "delivery": "Transport narxi o‘lcham, og‘irlik, qadoqlash, kelib chiqish mamlakati va maxsus tashish talablariga bog‘liq. **EXW/FCA/DAP/DDP** shartlari quote'da aniq ko‘rsatilishi kerak.",
    "service": "- O‘zbekistonda authorized service bormi?\n- Kafolatni kim bajaradi?\n- Preventive maintenance davriyligi qanday?\n- Kalibrlash/verification talab qilinadimi?\n- Servis muhandisi kelish muddati qancha?\n\n**Status:** aynan `Elmasonic S60H` uchun O‘zbekistondagi servis holati yozma tasdiqlanishi kerak.",
    "spares": "Xarid bilan birga modelga mos **wear parts, service kit, sensor/probe/filter/tubing va boshqa sarf qismlar** ro‘yxati, narxi va lead time'i olinadi.",
    "tco": "**TCO =** xarid + import/bojxona/QQS + transport + o‘rnatish + kalibrlash + servis + ehtiyot qismlar + sarf materiallari + elektr/suv/gaz + dasturiy litsenziyalar + operator o‘qitish.\n\n**Hozirgi TCO:** RFQ va yillik foydalanish hajmisiz yakuniy hisoblanmagan.",
    "redFlags": "",
    "finalStatus": "**Narx:** $3,000–$25,000\n**O‘zbekiston:** aynan model bo‘yicha RFQ kerak\n**Import:** local stockga qarab\n**Yetkazib berish:** konfiguratsiyaga bog‘liq\n**Servis:** yozma tasdiq kerak\n**Ehtiyot qismlar:** alohida BOM/quote kerak\n**TCO:** RFQdan keyin hisoblanadi\n\n---\n\n# 51–75 BLOK YAKUNI\n\n**Tayyor:** 75 / 100\n\n**Keyingi blok:** II-D — 76–100-qurilmalar.\n\n> Eslatma: bu blokda ham ishonchli yakuniy quote bo‘lmagan joylarda raqamni “rasmiy narx” sifatida ko‘rsatishdan saqlandik. Xarid qarori uchun RFQ asosiy manba bo‘ladi."
  }
};

export default purchaseBlock3;
