import type { PurchaseContent } from "./learningData";

const purchaseBlock4: Record<number, PurchaseContent> = {
    "76": {
    "number": 76,
    "title": "Muhit tayyorlash stantsiyasi",
    "searchName": "Muhit tayyorlash stantsiyasi",
    "model": "Integra MEDIACLAVE 30",
    "sourceKind": "purchase",
    "price": "$2,000–$15,000",
    "priceEvidence": "",
    "source": "",
    "priceStatus": "",
    "whereToBuy": "1. Ishlab chiqaruvchining rasmiy savdo kanali.\n2. Authorized distributor/integrator.\n3. O‘zbekistondagi laboratoriya uskunalari yetkazib beruvchisi.\n4. Used/refurbished — faqat texnik tekshiruv, servis tarixi va calibration hujjati bilan.",
    "purchaseRule": "",
    "availabilityUz": "Aynan `Integra MEDIACLAVE 30` uchun tayyor local stock holati ushbu bosqichda qat'iy tasdiqlanmagan. Mahalliy distributor/integratorga **model + konfiguratsiya** bilan RFQ yuborish kerak.",
    "importInfo": "Local stock bo‘lmasa, import qilinadi. RFQda model/catalog raqami, konfiguratsiya, ishlab chiqarilgan mamlakat, HS code, eksport qadoqlashi, kafolat, sertifikatlar va Incoterms alohida so‘raladi.",
    "delivery": "Transport narxi o‘lcham, og‘irlik, qadoqlash, kelib chiqish mamlakati va maxsus tashish talablariga bog‘liq. **EXW/FCA/DAP/DDP** shartlari quote'da aniq ko‘rsatilishi kerak.",
    "service": "- O‘zbekistonda authorized service bormi?\n- Kafolatni kim bajaradi?\n- Preventive maintenance davriyligi qanday?\n- Kalibrlash/verification talab qilinadimi?\n- Servis muhandisi kelish muddati qancha?\n\n**Status:** aynan `Integra MEDIACLAVE 30` uchun O‘zbekistondagi servis holati yozma tasdiqlanishi kerak.",
    "spares": "Xarid bilan birga modelga mos **wear parts, service kit, sensor/probe/filter/tubing va boshqa sarf qismlar** ro‘yxati, narxi va lead time'i olinadi.",
    "tco": "**TCO =** xarid + import/bojxona/QQS + transport + o‘rnatish + kalibrlash + servis + ehtiyot qismlar + sarf materiallari + elektr/suv/gaz + dasturiy litsenziyalar + operator o‘qitish.\n\n**Hozirgi TCO:** RFQ va yillik foydalanish hajmisiz yakuniy hisoblanmagan.",
    "redFlags": "",
    "finalStatus": "**Narx:** $2,000–$15,000\n**O‘zbekiston:** aynan model bo‘yicha RFQ kerak\n**Import:** local stockga qarab\n**Yetkazib berish:** konfiguratsiyaga bog‘liq\n**Servis:** yozma tasdiq kerak\n**Ehtiyot qismlar:** alohida BOM/quote kerak\n**TCO:** RFQdan keyin hisoblanadi\n\n---"
  },
    "77": {
    "number": 77,
    "title": "Koloniyalar sanash qurilmasi",
    "searchName": "Koloniyalar sanash qurilmasi",
    "model": "Interscience Scan 500",
    "sourceKind": "purchase",
    "price": "$1,000–$10,000",
    "priceEvidence": "",
    "source": "",
    "priceStatus": "",
    "whereToBuy": "1. Ishlab chiqaruvchining rasmiy savdo kanali.\n2. Authorized distributor/integrator.\n3. O‘zbekistondagi laboratoriya uskunalari yetkazib beruvchisi.\n4. Used/refurbished — faqat texnik tekshiruv, servis tarixi va calibration hujjati bilan.",
    "purchaseRule": "",
    "availabilityUz": "Aynan `Interscience Scan 500` uchun tayyor local stock holati ushbu bosqichda qat'iy tasdiqlanmagan. Mahalliy distributor/integratorga **model + konfiguratsiya** bilan RFQ yuborish kerak.",
    "importInfo": "Local stock bo‘lmasa, import qilinadi. RFQda model/catalog raqami, konfiguratsiya, ishlab chiqarilgan mamlakat, HS code, eksport qadoqlashi, kafolat, sertifikatlar va Incoterms alohida so‘raladi.",
    "delivery": "Transport narxi o‘lcham, og‘irlik, qadoqlash, kelib chiqish mamlakati va maxsus tashish talablariga bog‘liq. **EXW/FCA/DAP/DDP** shartlari quote'da aniq ko‘rsatilishi kerak.",
    "service": "- O‘zbekistonda authorized service bormi?\n- Kafolatni kim bajaradi?\n- Preventive maintenance davriyligi qanday?\n- Kalibrlash/verification talab qilinadimi?\n- Servis muhandisi kelish muddati qancha?\n\n**Status:** aynan `Interscience Scan 500` uchun O‘zbekistondagi servis holati yozma tasdiqlanishi kerak.",
    "spares": "Xarid bilan birga modelga mos **wear parts, service kit, sensor/probe/filter/tubing va boshqa sarf qismlar** ro‘yxati, narxi va lead time'i olinadi.",
    "tco": "**TCO =** xarid + import/bojxona/QQS + transport + o‘rnatish + kalibrlash + servis + ehtiyot qismlar + sarf materiallari + elektr/suv/gaz + dasturiy litsenziyalar + operator o‘qitish.\n\n**Hozirgi TCO:** RFQ va yillik foydalanish hajmisiz yakuniy hisoblanmagan.",
    "redFlags": "",
    "finalStatus": "**Narx:** $1,000–$10,000\n**O‘zbekiston:** aynan model bo‘yicha RFQ kerak\n**Import:** local stockga qarab\n**Yetkazib berish:** konfiguratsiyaga bog‘liq\n**Servis:** yozma tasdiq kerak\n**Ehtiyot qismlar:** alohida BOM/quote kerak\n**TCO:** RFQdan keyin hisoblanadi\n\n---"
  },
    "78": {
    "number": 78,
    "title": "Stomacher (Homogenizator qopchali)",
    "searchName": "Stomacher (Homogenizator qopchali)",
    "model": "Seward Stomacher 400 Circulator",
    "sourceKind": "purchase",
    "price": "$2,000–$20,000",
    "priceEvidence": "",
    "source": "",
    "priceStatus": "",
    "whereToBuy": "1. Ishlab chiqaruvchining rasmiy savdo kanali.\n2. Authorized distributor/integrator.\n3. O‘zbekistondagi laboratoriya uskunalari yetkazib beruvchisi.\n4. Used/refurbished — faqat texnik tekshiruv, servis tarixi va calibration hujjati bilan.",
    "purchaseRule": "",
    "availabilityUz": "Aynan `Seward Stomacher 400 Circulator` uchun tayyor local stock holati ushbu bosqichda qat'iy tasdiqlanmagan. Mahalliy distributor/integratorga **model + konfiguratsiya** bilan RFQ yuborish kerak.",
    "importInfo": "Local stock bo‘lmasa, import qilinadi. RFQda model/catalog raqami, konfiguratsiya, ishlab chiqarilgan mamlakat, HS code, eksport qadoqlashi, kafolat, sertifikatlar va Incoterms alohida so‘raladi.",
    "delivery": "Transport narxi o‘lcham, og‘irlik, qadoqlash, kelib chiqish mamlakati va maxsus tashish talablariga bog‘liq. **EXW/FCA/DAP/DDP** shartlari quote'da aniq ko‘rsatilishi kerak.",
    "service": "- O‘zbekistonda authorized service bormi?\n- Kafolatni kim bajaradi?\n- Preventive maintenance davriyligi qanday?\n- Kalibrlash/verification talab qilinadimi?\n- Servis muhandisi kelish muddati qancha?\n\n**Status:** aynan `Seward Stomacher 400 Circulator` uchun O‘zbekistondagi servis holati yozma tasdiqlanishi kerak.",
    "spares": "Xarid bilan birga modelga mos **wear parts, service kit, sensor/probe/filter/tubing va boshqa sarf qismlar** ro‘yxati, narxi va lead time'i olinadi.",
    "tco": "**TCO =** xarid + import/bojxona/QQS + transport + o‘rnatish + kalibrlash + servis + ehtiyot qismlar + sarf materiallari + elektr/suv/gaz + dasturiy litsenziyalar + operator o‘qitish.\n\n**Hozirgi TCO:** RFQ va yillik foydalanish hajmisiz yakuniy hisoblanmagan.",
    "redFlags": "",
    "finalStatus": "**Narx:** $2,000–$20,000\n**O‘zbekiston:** aynan model bo‘yicha RFQ kerak\n**Import:** local stockga qarab\n**Yetkazib berish:** konfiguratsiyaga bog‘liq\n**Servis:** yozma tasdiq kerak\n**Ehtiyot qismlar:** alohida BOM/quote kerak\n**TCO:** RFQdan keyin hisoblanadi\n\n---"
  },
    "79": {
    "number": 79,
    "title": "Ko‘p rejimli mikroplanshet o‘quvchi",
    "searchName": "Ko‘p rejimli mikroplanshet o‘quvchi",
    "model": "Molecular Devices SpectraMax i3x",
    "sourceKind": "purchase",
    "price": "$1,500–$15,000",
    "priceEvidence": "",
    "source": "",
    "priceStatus": "",
    "whereToBuy": "1. Ishlab chiqaruvchining rasmiy savdo kanali.\n2. Authorized distributor/integrator.\n3. O‘zbekistondagi laboratoriya uskunalari yetkazib beruvchisi.\n4. Used/refurbished — faqat texnik tekshiruv, servis tarixi va calibration hujjati bilan.",
    "purchaseRule": "",
    "availabilityUz": "Aynan `Molecular Devices SpectraMax i3x` uchun tayyor local stock holati ushbu bosqichda qat'iy tasdiqlanmagan. Mahalliy distributor/integratorga **model + konfiguratsiya** bilan RFQ yuborish kerak.",
    "importInfo": "Local stock bo‘lmasa, import qilinadi. RFQda model/catalog raqami, konfiguratsiya, ishlab chiqarilgan mamlakat, HS code, eksport qadoqlashi, kafolat, sertifikatlar va Incoterms alohida so‘raladi.",
    "delivery": "Transport narxi o‘lcham, og‘irlik, qadoqlash, kelib chiqish mamlakati va maxsus tashish talablariga bog‘liq. **EXW/FCA/DAP/DDP** shartlari quote'da aniq ko‘rsatilishi kerak.",
    "service": "- O‘zbekistonda authorized service bormi?\n- Kafolatni kim bajaradi?\n- Preventive maintenance davriyligi qanday?\n- Kalibrlash/verification talab qilinadimi?\n- Servis muhandisi kelish muddati qancha?\n\n**Status:** aynan `Molecular Devices SpectraMax i3x` uchun O‘zbekistondagi servis holati yozma tasdiqlanishi kerak.",
    "spares": "Xarid bilan birga modelga mos **wear parts, service kit, sensor/probe/filter/tubing va boshqa sarf qismlar** ro‘yxati, narxi va lead time'i olinadi.",
    "tco": "**TCO =** xarid + import/bojxona/QQS + transport + o‘rnatish + kalibrlash + servis + ehtiyot qismlar + sarf materiallari + elektr/suv/gaz + dasturiy litsenziyalar + operator o‘qitish.\n\n**Hozirgi TCO:** RFQ va yillik foydalanish hajmisiz yakuniy hisoblanmagan.",
    "redFlags": "",
    "finalStatus": "**Narx:** $1,500–$15,000\n**O‘zbekiston:** aynan model bo‘yicha RFQ kerak\n**Import:** local stockga qarab\n**Yetkazib berish:** konfiguratsiyaga bog‘liq\n**Servis:** yozma tasdiq kerak\n**Ehtiyot qismlar:** alohida BOM/quote kerak\n**TCO:** RFQdan keyin hisoblanadi\n\n---"
  },
    "80": {
    "number": 80,
    "title": "Kapillyar elektroforez sistema (CE)",
    "searchName": "Kapillyar elektroforez sistema (CE)",
    "model": "Beckman Coulter PA 800 Plus",
    "sourceKind": "purchase",
    "price": "$3,000–$25,000",
    "priceEvidence": "",
    "source": "",
    "priceStatus": "",
    "whereToBuy": "1. Ishlab chiqaruvchining rasmiy savdo kanali.\n2. Authorized distributor/integrator.\n3. O‘zbekistondagi laboratoriya uskunalari yetkazib beruvchisi.\n4. Used/refurbished — faqat texnik tekshiruv, servis tarixi va calibration hujjati bilan.",
    "purchaseRule": "",
    "availabilityUz": "Aynan `Beckman Coulter PA 800 Plus` uchun tayyor local stock holati ushbu bosqichda qat'iy tasdiqlanmagan. Mahalliy distributor/integratorga **model + konfiguratsiya** bilan RFQ yuborish kerak.",
    "importInfo": "Local stock bo‘lmasa, import qilinadi. RFQda model/catalog raqami, konfiguratsiya, ishlab chiqarilgan mamlakat, HS code, eksport qadoqlashi, kafolat, sertifikatlar va Incoterms alohida so‘raladi.",
    "delivery": "Transport narxi o‘lcham, og‘irlik, qadoqlash, kelib chiqish mamlakati va maxsus tashish talablariga bog‘liq. **EXW/FCA/DAP/DDP** shartlari quote'da aniq ko‘rsatilishi kerak.",
    "service": "- O‘zbekistonda authorized service bormi?\n- Kafolatni kim bajaradi?\n- Preventive maintenance davriyligi qanday?\n- Kalibrlash/verification talab qilinadimi?\n- Servis muhandisi kelish muddati qancha?\n\n**Status:** aynan `Beckman Coulter PA 800 Plus` uchun O‘zbekistondagi servis holati yozma tasdiqlanishi kerak.",
    "spares": "Xarid bilan birga modelga mos **wear parts, service kit, sensor/probe/filter/tubing va boshqa sarf qismlar** ro‘yxati, narxi va lead time'i olinadi.",
    "tco": "**TCO =** xarid + import/bojxona/QQS + transport + o‘rnatish + kalibrlash + servis + ehtiyot qismlar + sarf materiallari + elektr/suv/gaz + dasturiy litsenziyalar + operator o‘qitish.\n\n**Hozirgi TCO:** RFQ va yillik foydalanish hajmisiz yakuniy hisoblanmagan.",
    "redFlags": "",
    "finalStatus": "**Narx:** $3,000–$25,000\n**O‘zbekiston:** aynan model bo‘yicha RFQ kerak\n**Import:** local stockga qarab\n**Yetkazib berish:** konfiguratsiyaga bog‘liq\n**Servis:** yozma tasdiq kerak\n**Ehtiyot qismlar:** alohida BOM/quote kerak\n**TCO:** RFQdan keyin hisoblanadi\n\n---"
  },
    "81": {
    "number": 81,
    "title": "Biosensor (SPR tizimi)",
    "searchName": "Biosensor (SPR tizimi)",
    "model": "Cytiva Biacore T200",
    "sourceKind": "purchase",
    "price": "$2,000–$15,000",
    "priceEvidence": "",
    "source": "",
    "priceStatus": "",
    "whereToBuy": "1. Ishlab chiqaruvchining rasmiy savdo kanali.\n2. Authorized distributor/integrator.\n3. O‘zbekistondagi laboratoriya uskunalari yetkazib beruvchisi.\n4. Used/refurbished — faqat texnik tekshiruv, servis tarixi va calibration hujjati bilan.",
    "purchaseRule": "",
    "availabilityUz": "Aynan `Cytiva Biacore T200` uchun tayyor local stock holati ushbu bosqichda qat'iy tasdiqlanmagan. Mahalliy distributor/integratorga **model + konfiguratsiya** bilan RFQ yuborish kerak.",
    "importInfo": "Local stock bo‘lmasa, import qilinadi. RFQda model/catalog raqami, konfiguratsiya, ishlab chiqarilgan mamlakat, HS code, eksport qadoqlashi, kafolat, sertifikatlar va Incoterms alohida so‘raladi.",
    "delivery": "Transport narxi o‘lcham, og‘irlik, qadoqlash, kelib chiqish mamlakati va maxsus tashish talablariga bog‘liq. **EXW/FCA/DAP/DDP** shartlari quote'da aniq ko‘rsatilishi kerak.",
    "service": "- O‘zbekistonda authorized service bormi?\n- Kafolatni kim bajaradi?\n- Preventive maintenance davriyligi qanday?\n- Kalibrlash/verification talab qilinadimi?\n- Servis muhandisi kelish muddati qancha?\n\n**Status:** aynan `Cytiva Biacore T200` uchun O‘zbekistondagi servis holati yozma tasdiqlanishi kerak.",
    "spares": "Xarid bilan birga modelga mos **wear parts, service kit, sensor/probe/filter/tubing va boshqa sarf qismlar** ro‘yxati, narxi va lead time'i olinadi.",
    "tco": "**TCO =** xarid + import/bojxona/QQS + transport + o‘rnatish + kalibrlash + servis + ehtiyot qismlar + sarf materiallari + elektr/suv/gaz + dasturiy litsenziyalar + operator o‘qitish.\n\n**Hozirgi TCO:** RFQ va yillik foydalanish hajmisiz yakuniy hisoblanmagan.",
    "redFlags": "",
    "finalStatus": "**Narx:** $2,000–$15,000\n**O‘zbekiston:** aynan model bo‘yicha RFQ kerak\n**Import:** local stockga qarab\n**Yetkazib berish:** konfiguratsiyaga bog‘liq\n**Servis:** yozma tasdiq kerak\n**Ehtiyot qismlar:** alohida BOM/quote kerak\n**TCO:** RFQdan keyin hisoblanadi\n\n---"
  },
    "82": {
    "number": 82,
    "title": "Mikrofluidik real-time PCR tizimi",
    "searchName": "Mikrofluidik real-time PCR tizimi",
    "model": "Fluidigm Biomark HD",
    "sourceKind": "purchase",
    "price": "$1,000–$8,000",
    "priceEvidence": "",
    "source": "",
    "priceStatus": "",
    "whereToBuy": "1. Ishlab chiqaruvchining rasmiy savdo kanali.\n2. Authorized distributor/integrator.\n3. O‘zbekistondagi laboratoriya uskunalari yetkazib beruvchisi.\n4. Used/refurbished — faqat texnik tekshiruv, servis tarixi va calibration hujjati bilan.",
    "purchaseRule": "",
    "availabilityUz": "Aynan `Fluidigm Biomark HD` uchun tayyor local stock holati ushbu bosqichda qat'iy tasdiqlanmagan. Mahalliy distributor/integratorga **model + konfiguratsiya** bilan RFQ yuborish kerak.",
    "importInfo": "Local stock bo‘lmasa, import qilinadi. RFQda model/catalog raqami, konfiguratsiya, ishlab chiqarilgan mamlakat, HS code, eksport qadoqlashi, kafolat, sertifikatlar va Incoterms alohida so‘raladi.",
    "delivery": "Transport narxi o‘lcham, og‘irlik, qadoqlash, kelib chiqish mamlakati va maxsus tashish talablariga bog‘liq. **EXW/FCA/DAP/DDP** shartlari quote'da aniq ko‘rsatilishi kerak.",
    "service": "- O‘zbekistonda authorized service bormi?\n- Kafolatni kim bajaradi?\n- Preventive maintenance davriyligi qanday?\n- Kalibrlash/verification talab qilinadimi?\n- Servis muhandisi kelish muddati qancha?\n\n**Status:** aynan `Fluidigm Biomark HD` uchun O‘zbekistondagi servis holati yozma tasdiqlanishi kerak.",
    "spares": "Xarid bilan birga modelga mos **wear parts, service kit, sensor/probe/filter/tubing va boshqa sarf qismlar** ro‘yxati, narxi va lead time'i olinadi.",
    "tco": "**TCO =** xarid + import/bojxona/QQS + transport + o‘rnatish + kalibrlash + servis + ehtiyot qismlar + sarf materiallari + elektr/suv/gaz + dasturiy litsenziyalar + operator o‘qitish.\n\n**Hozirgi TCO:** RFQ va yillik foydalanish hajmisiz yakuniy hisoblanmagan.",
    "redFlags": "",
    "finalStatus": "**Narx:** $1,000–$8,000\n**O‘zbekiston:** aynan model bo‘yicha RFQ kerak\n**Import:** local stockga qarab\n**Yetkazib berish:** konfiguratsiyaga bog‘liq\n**Servis:** yozma tasdiq kerak\n**Ehtiyot qismlar:** alohida BOM/quote kerak\n**TCO:** RFQdan keyin hisoblanadi\n\n---"
  },
    "83": {
    "number": 83,
    "title": "Eritilgan kislorod (DO) sensori/probi",
    "searchName": "Eritilgan kislorod (DO) sensori/probi",
    "model": "Mettler Toledo InPro 6800i",
    "sourceKind": "purchase",
    "price": "$2,000–$15,000",
    "priceEvidence": "",
    "source": "",
    "priceStatus": "",
    "whereToBuy": "1. Ishlab chiqaruvchining rasmiy savdo kanali.\n2. Authorized distributor/integrator.\n3. O‘zbekistondagi laboratoriya uskunalari yetkazib beruvchisi.\n4. Used/refurbished — faqat texnik tekshiruv, servis tarixi va calibration hujjati bilan.",
    "purchaseRule": "",
    "availabilityUz": "Aynan `Mettler Toledo InPro 6800i` uchun tayyor local stock holati ushbu bosqichda qat'iy tasdiqlanmagan. Mahalliy distributor/integratorga **model + konfiguratsiya** bilan RFQ yuborish kerak.",
    "importInfo": "Local stock bo‘lmasa, import qilinadi. RFQda model/catalog raqami, konfiguratsiya, ishlab chiqarilgan mamlakat, HS code, eksport qadoqlashi, kafolat, sertifikatlar va Incoterms alohida so‘raladi.",
    "delivery": "Transport narxi o‘lcham, og‘irlik, qadoqlash, kelib chiqish mamlakati va maxsus tashish talablariga bog‘liq. **EXW/FCA/DAP/DDP** shartlari quote'da aniq ko‘rsatilishi kerak.",
    "service": "- O‘zbekistonda authorized service bormi?\n- Kafolatni kim bajaradi?\n- Preventive maintenance davriyligi qanday?\n- Kalibrlash/verification talab qilinadimi?\n- Servis muhandisi kelish muddati qancha?\n\n**Status:** aynan `Mettler Toledo InPro 6800i` uchun O‘zbekistondagi servis holati yozma tasdiqlanishi kerak.",
    "spares": "Xarid bilan birga modelga mos **wear parts, service kit, sensor/probe/filter/tubing va boshqa sarf qismlar** ro‘yxati, narxi va lead time'i olinadi.",
    "tco": "**TCO =** xarid + import/bojxona/QQS + transport + o‘rnatish + kalibrlash + servis + ehtiyot qismlar + sarf materiallari + elektr/suv/gaz + dasturiy litsenziyalar + operator o‘qitish.\n\n**Hozirgi TCO:** RFQ va yillik foydalanish hajmisiz yakuniy hisoblanmagan.",
    "redFlags": "",
    "finalStatus": "**Narx:** $2,000–$15,000\n**O‘zbekiston:** aynan model bo‘yicha RFQ kerak\n**Import:** local stockga qarab\n**Yetkazib berish:** konfiguratsiyaga bog‘liq\n**Servis:** yozma tasdiq kerak\n**Ehtiyot qismlar:** alohida BOM/quote kerak\n**TCO:** RFQdan keyin hisoblanadi\n\n---"
  },
    "84": {
    "number": 84,
    "title": "Nazoratli tezlikda muzlatish tizimi (controlled-rate freezer)",
    "searchName": "Nazoratli tezlikda muzlatish tizimi (controlled-rate freezer)",
    "model": "Planer Kryo 560-16",
    "sourceKind": "purchase",
    "price": "$3,000–$20,000",
    "priceEvidence": "",
    "source": "",
    "priceStatus": "",
    "whereToBuy": "1. Ishlab chiqaruvchining rasmiy savdo kanali.\n2. Authorized distributor/integrator.\n3. O‘zbekistondagi laboratoriya uskunalari yetkazib beruvchisi.\n4. Used/refurbished — faqat texnik tekshiruv, servis tarixi va calibration hujjati bilan.",
    "purchaseRule": "",
    "availabilityUz": "Aynan `Planer Kryo 560-16` uchun tayyor local stock holati ushbu bosqichda qat'iy tasdiqlanmagan. Mahalliy distributor/integratorga **model + konfiguratsiya** bilan RFQ yuborish kerak.",
    "importInfo": "Local stock bo‘lmasa, import qilinadi. RFQda model/catalog raqami, konfiguratsiya, ishlab chiqarilgan mamlakat, HS code, eksport qadoqlashi, kafolat, sertifikatlar va Incoterms alohida so‘raladi.",
    "delivery": "Transport narxi o‘lcham, og‘irlik, qadoqlash, kelib chiqish mamlakati va maxsus tashish talablariga bog‘liq. **EXW/FCA/DAP/DDP** shartlari quote'da aniq ko‘rsatilishi kerak.",
    "service": "- O‘zbekistonda authorized service bormi?\n- Kafolatni kim bajaradi?\n- Preventive maintenance davriyligi qanday?\n- Kalibrlash/verification talab qilinadimi?\n- Servis muhandisi kelish muddati qancha?\n\n**Status:** aynan `Planer Kryo 560-16` uchun O‘zbekistondagi servis holati yozma tasdiqlanishi kerak.",
    "spares": "Xarid bilan birga modelga mos **wear parts, service kit, sensor/probe/filter/tubing va boshqa sarf qismlar** ro‘yxati, narxi va lead time'i olinadi.",
    "tco": "**TCO =** xarid + import/bojxona/QQS + transport + o‘rnatish + kalibrlash + servis + ehtiyot qismlar + sarf materiallari + elektr/suv/gaz + dasturiy litsenziyalar + operator o‘qitish.\n\n**Hozirgi TCO:** RFQ va yillik foydalanish hajmisiz yakuniy hisoblanmagan.",
    "redFlags": "",
    "finalStatus": "**Narx:** $3,000–$20,000\n**O‘zbekiston:** aynan model bo‘yicha RFQ kerak\n**Import:** local stockga qarab\n**Yetkazib berish:** konfiguratsiyaga bog‘liq\n**Servis:** yozma tasdiq kerak\n**Ehtiyot qismlar:** alohida BOM/quote kerak\n**TCO:** RFQdan keyin hisoblanadi\n\n---"
  },
    "85": {
    "number": 85,
    "title": "Termogravimetrik tahlilchi (TGA)",
    "searchName": "Termogravimetrik tahlilchi (TGA)",
    "model": "TA Instruments TGA 550",
    "sourceKind": "purchase",
    "price": "$5,000–$30,000",
    "priceEvidence": "",
    "source": "",
    "priceStatus": "",
    "whereToBuy": "1. Ishlab chiqaruvchining rasmiy savdo kanali.\n2. Authorized distributor/integrator.\n3. O‘zbekistondagi laboratoriya uskunalari yetkazib beruvchisi.\n4. Used/refurbished — faqat texnik tekshiruv, servis tarixi va calibration hujjati bilan.",
    "purchaseRule": "",
    "availabilityUz": "Aynan `TA Instruments TGA 550` uchun tayyor local stock holati ushbu bosqichda qat'iy tasdiqlanmagan. Mahalliy distributor/integratorga **model + konfiguratsiya** bilan RFQ yuborish kerak.",
    "importInfo": "Local stock bo‘lmasa, import qilinadi. RFQda model/catalog raqami, konfiguratsiya, ishlab chiqarilgan mamlakat, HS code, eksport qadoqlashi, kafolat, sertifikatlar va Incoterms alohida so‘raladi.",
    "delivery": "Transport narxi o‘lcham, og‘irlik, qadoqlash, kelib chiqish mamlakati va maxsus tashish talablariga bog‘liq. **EXW/FCA/DAP/DDP** shartlari quote'da aniq ko‘rsatilishi kerak.",
    "service": "- O‘zbekistonda authorized service bormi?\n- Kafolatni kim bajaradi?\n- Preventive maintenance davriyligi qanday?\n- Kalibrlash/verification talab qilinadimi?\n- Servis muhandisi kelish muddati qancha?\n\n**Status:** aynan `TA Instruments TGA 550` uchun O‘zbekistondagi servis holati yozma tasdiqlanishi kerak.",
    "spares": "Xarid bilan birga modelga mos **wear parts, service kit, sensor/probe/filter/tubing va boshqa sarf qismlar** ro‘yxati, narxi va lead time'i olinadi.",
    "tco": "**TCO =** xarid + import/bojxona/QQS + transport + o‘rnatish + kalibrlash + servis + ehtiyot qismlar + sarf materiallari + elektr/suv/gaz + dasturiy litsenziyalar + operator o‘qitish.\n\n**Hozirgi TCO:** RFQ va yillik foydalanish hajmisiz yakuniy hisoblanmagan.",
    "redFlags": "",
    "finalStatus": "**Narx:** $5,000–$30,000\n**O‘zbekiston:** aynan model bo‘yicha RFQ kerak\n**Import:** local stockga qarab\n**Yetkazib berish:** konfiguratsiyaga bog‘liq\n**Servis:** yozma tasdiq kerak\n**Ehtiyot qismlar:** alohida BOM/quote kerak\n**TCO:** RFQdan keyin hisoblanadi\n\n---"
  },
    "86": {
    "number": 86,
    "title": "Elektrokimyoviy analizator",
    "searchName": "Elektrokimyoviy analizator",
    "model": "Metrohm 910 PSTAT mini",
    "sourceKind": "purchase",
    "price": "$2,000–$15,000",
    "priceEvidence": "",
    "source": "",
    "priceStatus": "",
    "whereToBuy": "1. Ishlab chiqaruvchining rasmiy savdo kanali.\n2. Authorized distributor/integrator.\n3. O‘zbekistondagi laboratoriya uskunalari yetkazib beruvchisi.\n4. Used/refurbished — faqat texnik tekshiruv, servis tarixi va calibration hujjati bilan.",
    "purchaseRule": "",
    "availabilityUz": "Aynan `Metrohm 910 PSTAT mini` uchun tayyor local stock holati ushbu bosqichda qat'iy tasdiqlanmagan. Mahalliy distributor/integratorga **model + konfiguratsiya** bilan RFQ yuborish kerak.",
    "importInfo": "Local stock bo‘lmasa, import qilinadi. RFQda model/catalog raqami, konfiguratsiya, ishlab chiqarilgan mamlakat, HS code, eksport qadoqlashi, kafolat, sertifikatlar va Incoterms alohida so‘raladi.",
    "delivery": "Transport narxi o‘lcham, og‘irlik, qadoqlash, kelib chiqish mamlakati va maxsus tashish talablariga bog‘liq. **EXW/FCA/DAP/DDP** shartlari quote'da aniq ko‘rsatilishi kerak.",
    "service": "- O‘zbekistonda authorized service bormi?\n- Kafolatni kim bajaradi?\n- Preventive maintenance davriyligi qanday?\n- Kalibrlash/verification talab qilinadimi?\n- Servis muhandisi kelish muddati qancha?\n\n**Status:** aynan `Metrohm 910 PSTAT mini` uchun O‘zbekistondagi servis holati yozma tasdiqlanishi kerak.",
    "spares": "Xarid bilan birga modelga mos **wear parts, service kit, sensor/probe/filter/tubing va boshqa sarf qismlar** ro‘yxati, narxi va lead time'i olinadi.",
    "tco": "**TCO =** xarid + import/bojxona/QQS + transport + o‘rnatish + kalibrlash + servis + ehtiyot qismlar + sarf materiallari + elektr/suv/gaz + dasturiy litsenziyalar + operator o‘qitish.\n\n**Hozirgi TCO:** RFQ va yillik foydalanish hajmisiz yakuniy hisoblanmagan.",
    "redFlags": "",
    "finalStatus": "**Narx:** $2,000–$15,000\n**O‘zbekiston:** aynan model bo‘yicha RFQ kerak\n**Import:** local stockga qarab\n**Yetkazib berish:** konfiguratsiyaga bog‘liq\n**Servis:** yozma tasdiq kerak\n**Ehtiyot qismlar:** alohida BOM/quote kerak\n**TCO:** RFQdan keyin hisoblanadi\n\n---"
  },
    "87": {
    "number": 87,
    "title": "Kombinatorial kimyo roboti (liquid handler)",
    "searchName": "Kombinatorial kimyo roboti (liquid handler)",
    "model": "Hamilton STAR",
    "sourceKind": "purchase",
    "price": "$1,000–$10,000",
    "priceEvidence": "",
    "source": "",
    "priceStatus": "",
    "whereToBuy": "1. Ishlab chiqaruvchining rasmiy savdo kanali.\n2. Authorized distributor/integrator.\n3. O‘zbekistondagi laboratoriya uskunalari yetkazib beruvchisi.\n4. Used/refurbished — faqat texnik tekshiruv, servis tarixi va calibration hujjati bilan.",
    "purchaseRule": "",
    "availabilityUz": "Aynan `Hamilton STAR` uchun tayyor local stock holati ushbu bosqichda qat'iy tasdiqlanmagan. Mahalliy distributor/integratorga **model + konfiguratsiya** bilan RFQ yuborish kerak.",
    "importInfo": "Local stock bo‘lmasa, import qilinadi. RFQda model/catalog raqami, konfiguratsiya, ishlab chiqarilgan mamlakat, HS code, eksport qadoqlashi, kafolat, sertifikatlar va Incoterms alohida so‘raladi.",
    "delivery": "Transport narxi o‘lcham, og‘irlik, qadoqlash, kelib chiqish mamlakati va maxsus tashish talablariga bog‘liq. **EXW/FCA/DAP/DDP** shartlari quote'da aniq ko‘rsatilishi kerak.",
    "service": "- O‘zbekistonda authorized service bormi?\n- Kafolatni kim bajaradi?\n- Preventive maintenance davriyligi qanday?\n- Kalibrlash/verification talab qilinadimi?\n- Servis muhandisi kelish muddati qancha?\n\n**Status:** aynan `Hamilton STAR` uchun O‘zbekistondagi servis holati yozma tasdiqlanishi kerak.",
    "spares": "Xarid bilan birga modelga mos **wear parts, service kit, sensor/probe/filter/tubing va boshqa sarf qismlar** ro‘yxati, narxi va lead time'i olinadi.",
    "tco": "**TCO =** xarid + import/bojxona/QQS + transport + o‘rnatish + kalibrlash + servis + ehtiyot qismlar + sarf materiallari + elektr/suv/gaz + dasturiy litsenziyalar + operator o‘qitish.\n\n**Hozirgi TCO:** RFQ va yillik foydalanish hajmisiz yakuniy hisoblanmagan.",
    "redFlags": "",
    "finalStatus": "**Narx:** $1,000–$10,000\n**O‘zbekiston:** aynan model bo‘yicha RFQ kerak\n**Import:** local stockga qarab\n**Yetkazib berish:** konfiguratsiyaga bog‘liq\n**Servis:** yozma tasdiq kerak\n**Ehtiyot qismlar:** alohida BOM/quote kerak\n**TCO:** RFQdan keyin hisoblanadi\n\n---"
  },
    "88": {
    "number": 88,
    "title": "UV-Vis spektrofotometr (suv sifati)",
    "searchName": "UV-Vis spektrofotometr (suv sifati)",
    "model": "HACH DR6000",
    "sourceKind": "purchase",
    "price": "$2,000–$20,000",
    "priceEvidence": "",
    "source": "",
    "priceStatus": "",
    "whereToBuy": "1. Ishlab chiqaruvchining rasmiy savdo kanali.\n2. Authorized distributor/integrator.\n3. O‘zbekistondagi laboratoriya uskunalari yetkazib beruvchisi.\n4. Used/refurbished — faqat texnik tekshiruv, servis tarixi va calibration hujjati bilan.",
    "purchaseRule": "",
    "availabilityUz": "Aynan `HACH DR6000` uchun tayyor local stock holati ushbu bosqichda qat'iy tasdiqlanmagan. Mahalliy distributor/integratorga **model + konfiguratsiya** bilan RFQ yuborish kerak.",
    "importInfo": "Local stock bo‘lmasa, import qilinadi. RFQda model/catalog raqami, konfiguratsiya, ishlab chiqarilgan mamlakat, HS code, eksport qadoqlashi, kafolat, sertifikatlar va Incoterms alohida so‘raladi.",
    "delivery": "Transport narxi o‘lcham, og‘irlik, qadoqlash, kelib chiqish mamlakati va maxsus tashish talablariga bog‘liq. **EXW/FCA/DAP/DDP** shartlari quote'da aniq ko‘rsatilishi kerak.",
    "service": "- O‘zbekistonda authorized service bormi?\n- Kafolatni kim bajaradi?\n- Preventive maintenance davriyligi qanday?\n- Kalibrlash/verification talab qilinadimi?\n- Servis muhandisi kelish muddati qancha?\n\n**Status:** aynan `HACH DR6000` uchun O‘zbekistondagi servis holati yozma tasdiqlanishi kerak.",
    "spares": "Xarid bilan birga modelga mos **wear parts, service kit, sensor/probe/filter/tubing va boshqa sarf qismlar** ro‘yxati, narxi va lead time'i olinadi.",
    "tco": "**TCO =** xarid + import/bojxona/QQS + transport + o‘rnatish + kalibrlash + servis + ehtiyot qismlar + sarf materiallari + elektr/suv/gaz + dasturiy litsenziyalar + operator o‘qitish.\n\n**Hozirgi TCO:** RFQ va yillik foydalanish hajmisiz yakuniy hisoblanmagan.",
    "redFlags": "",
    "finalStatus": "**Narx:** $2,000–$20,000\n**O‘zbekiston:** aynan model bo‘yicha RFQ kerak\n**Import:** local stockga qarab\n**Yetkazib berish:** konfiguratsiyaga bog‘liq\n**Servis:** yozma tasdiq kerak\n**Ehtiyot qismlar:** alohida BOM/quote kerak\n**TCO:** RFQdan keyin hisoblanadi\n\n---"
  },
    "89": {
    "number": 89,
    "title": "Qo'l ushlaydigan spektrometr (Raman)",
    "searchName": "Qo'l ushlaydigan spektrometr (Raman)",
    "model": "Metrohm Mira M-3",
    "sourceKind": "purchase",
    "price": "$1,500–$12,000",
    "priceEvidence": "",
    "source": "",
    "priceStatus": "",
    "whereToBuy": "1. Ishlab chiqaruvchining rasmiy savdo kanali.\n2. Authorized distributor/integrator.\n3. O‘zbekistondagi laboratoriya uskunalari yetkazib beruvchisi.\n4. Used/refurbished — faqat texnik tekshiruv, servis tarixi va calibration hujjati bilan.",
    "purchaseRule": "",
    "availabilityUz": "Aynan `Metrohm Mira M-3` uchun tayyor local stock holati ushbu bosqichda qat'iy tasdiqlanmagan. Mahalliy distributor/integratorga **model + konfiguratsiya** bilan RFQ yuborish kerak.",
    "importInfo": "Local stock bo‘lmasa, import qilinadi. RFQda model/catalog raqami, konfiguratsiya, ishlab chiqarilgan mamlakat, HS code, eksport qadoqlashi, kafolat, sertifikatlar va Incoterms alohida so‘raladi.",
    "delivery": "Transport narxi o‘lcham, og‘irlik, qadoqlash, kelib chiqish mamlakati va maxsus tashish talablariga bog‘liq. **EXW/FCA/DAP/DDP** shartlari quote'da aniq ko‘rsatilishi kerak.",
    "service": "- O‘zbekistonda authorized service bormi?\n- Kafolatni kim bajaradi?\n- Preventive maintenance davriyligi qanday?\n- Kalibrlash/verification talab qilinadimi?\n- Servis muhandisi kelish muddati qancha?\n\n**Status:** aynan `Metrohm Mira M-3` uchun O‘zbekistondagi servis holati yozma tasdiqlanishi kerak.",
    "spares": "Xarid bilan birga modelga mos **wear parts, service kit, sensor/probe/filter/tubing va boshqa sarf qismlar** ro‘yxati, narxi va lead time'i olinadi.",
    "tco": "**TCO =** xarid + import/bojxona/QQS + transport + o‘rnatish + kalibrlash + servis + ehtiyot qismlar + sarf materiallari + elektr/suv/gaz + dasturiy litsenziyalar + operator o‘qitish.\n\n**Hozirgi TCO:** RFQ va yillik foydalanish hajmisiz yakuniy hisoblanmagan.",
    "redFlags": "",
    "finalStatus": "**Narx:** $1,500–$12,000\n**O‘zbekiston:** aynan model bo‘yicha RFQ kerak\n**Import:** local stockga qarab\n**Yetkazib berish:** konfiguratsiyaga bog‘liq\n**Servis:** yozma tasdiq kerak\n**Ehtiyot qismlar:** alohida BOM/quote kerak\n**TCO:** RFQdan keyin hisoblanadi\n\n---"
  },
    "90": {
    "number": 90,
    "title": "Antibiotik sezuvchanlik tizimi (AST)",
    "searchName": "Antibiotik sezuvchanlik tizimi (AST)",
    "model": "bioMérieux VITEK 2 XL",
    "sourceKind": "purchase",
    "price": "$5,000–$40,000",
    "priceEvidence": "",
    "source": "",
    "priceStatus": "",
    "whereToBuy": "1. Ishlab chiqaruvchining rasmiy savdo kanali.\n2. Authorized distributor/integrator.\n3. O‘zbekistondagi laboratoriya uskunalari yetkazib beruvchisi.\n4. Used/refurbished — faqat texnik tekshiruv, servis tarixi va calibration hujjati bilan.",
    "purchaseRule": "",
    "availabilityUz": "Aynan `bioMérieux VITEK 2 XL` uchun tayyor local stock holati ushbu bosqichda qat'iy tasdiqlanmagan. Mahalliy distributor/integratorga **model + konfiguratsiya** bilan RFQ yuborish kerak.",
    "importInfo": "Local stock bo‘lmasa, import qilinadi. RFQda model/catalog raqami, konfiguratsiya, ishlab chiqarilgan mamlakat, HS code, eksport qadoqlashi, kafolat, sertifikatlar va Incoterms alohida so‘raladi.",
    "delivery": "Transport narxi o‘lcham, og‘irlik, qadoqlash, kelib chiqish mamlakati va maxsus tashish talablariga bog‘liq. **EXW/FCA/DAP/DDP** shartlari quote'da aniq ko‘rsatilishi kerak.",
    "service": "- O‘zbekistonda authorized service bormi?\n- Kafolatni kim bajaradi?\n- Preventive maintenance davriyligi qanday?\n- Kalibrlash/verification talab qilinadimi?\n- Servis muhandisi kelish muddati qancha?\n\n**Status:** aynan `bioMérieux VITEK 2 XL` uchun O‘zbekistondagi servis holati yozma tasdiqlanishi kerak.",
    "spares": "Xarid bilan birga modelga mos **wear parts, service kit, sensor/probe/filter/tubing va boshqa sarf qismlar** ro‘yxati, narxi va lead time'i olinadi.",
    "tco": "**TCO =** xarid + import/bojxona/QQS + transport + o‘rnatish + kalibrlash + servis + ehtiyot qismlar + sarf materiallari + elektr/suv/gaz + dasturiy litsenziyalar + operator o‘qitish.\n\n**Hozirgi TCO:** RFQ va yillik foydalanish hajmisiz yakuniy hisoblanmagan.",
    "redFlags": "",
    "finalStatus": "**Narx:** $5,000–$40,000\n**O‘zbekiston:** aynan model bo‘yicha RFQ kerak\n**Import:** local stockga qarab\n**Yetkazib berish:** konfiguratsiyaga bog‘liq\n**Servis:** yozma tasdiq kerak\n**Ehtiyot qismlar:** alohida BOM/quote kerak\n**TCO:** RFQdan keyin hisoblanadi\n\n---"
  },
    "91": {
    "number": 91,
    "title": "qPCR uchun digital PCR (ddPCR)",
    "searchName": "qPCR uchun digital PCR (ddPCR)",
    "model": "Bio-Rad QX200 Droplet Digital PCR",
    "sourceKind": "purchase",
    "price": "$2,000–$15,000",
    "priceEvidence": "",
    "source": "",
    "priceStatus": "",
    "whereToBuy": "1. Ishlab chiqaruvchining rasmiy savdo kanali.\n2. Authorized distributor/integrator.\n3. O‘zbekistondagi laboratoriya uskunalari yetkazib beruvchisi.\n4. Used/refurbished — faqat texnik tekshiruv, servis tarixi va calibration hujjati bilan.",
    "purchaseRule": "",
    "availabilityUz": "Aynan `Bio-Rad QX200 Droplet Digital PCR` uchun tayyor local stock holati ushbu bosqichda qat'iy tasdiqlanmagan. Mahalliy distributor/integratorga **model + konfiguratsiya** bilan RFQ yuborish kerak.",
    "importInfo": "Local stock bo‘lmasa, import qilinadi. RFQda model/catalog raqami, konfiguratsiya, ishlab chiqarilgan mamlakat, HS code, eksport qadoqlashi, kafolat, sertifikatlar va Incoterms alohida so‘raladi.",
    "delivery": "Transport narxi o‘lcham, og‘irlik, qadoqlash, kelib chiqish mamlakati va maxsus tashish talablariga bog‘liq. **EXW/FCA/DAP/DDP** shartlari quote'da aniq ko‘rsatilishi kerak.",
    "service": "- O‘zbekistonda authorized service bormi?\n- Kafolatni kim bajaradi?\n- Preventive maintenance davriyligi qanday?\n- Kalibrlash/verification talab qilinadimi?\n- Servis muhandisi kelish muddati qancha?\n\n**Status:** aynan `Bio-Rad QX200 Droplet Digital PCR` uchun O‘zbekistondagi servis holati yozma tasdiqlanishi kerak.",
    "spares": "Xarid bilan birga modelga mos **wear parts, service kit, sensor/probe/filter/tubing va boshqa sarf qismlar** ro‘yxati, narxi va lead time'i olinadi.",
    "tco": "**TCO =** xarid + import/bojxona/QQS + transport + o‘rnatish + kalibrlash + servis + ehtiyot qismlar + sarf materiallari + elektr/suv/gaz + dasturiy litsenziyalar + operator o‘qitish.\n\n**Hozirgi TCO:** RFQ va yillik foydalanish hajmisiz yakuniy hisoblanmagan.",
    "redFlags": "",
    "finalStatus": "**Narx:** $2,000–$15,000\n**O‘zbekiston:** aynan model bo‘yicha RFQ kerak\n**Import:** local stockga qarab\n**Yetkazib berish:** konfiguratsiyaga bog‘liq\n**Servis:** yozma tasdiq kerak\n**Ehtiyot qismlar:** alohida BOM/quote kerak\n**TCO:** RFQdan keyin hisoblanadi\n\n---"
  },
    "92": {
    "number": 92,
    "title": "CRISPR-Cas9 reagent/tizim to‘plami",
    "searchName": "CRISPR-Cas9 reagent/tizim to‘plami",
    "model": "Integrated DNA Technologies (IDT) gRNA dizayn + Cas9 RNP",
    "sourceKind": "purchase",
    "price": "$3,000–$25,000",
    "priceEvidence": "",
    "source": "",
    "priceStatus": "",
    "whereToBuy": "1. Ishlab chiqaruvchining rasmiy savdo kanali.\n2. Authorized distributor/integrator.\n3. O‘zbekistondagi laboratoriya uskunalari yetkazib beruvchisi.\n4. Used/refurbished — faqat texnik tekshiruv, servis tarixi va calibration hujjati bilan.",
    "purchaseRule": "",
    "availabilityUz": "Aynan `Integrated DNA Technologies (IDT) gRNA dizayn + Cas9 RNP` uchun tayyor local stock holati ushbu bosqichda qat'iy tasdiqlanmagan. Mahalliy distributor/integratorga **model + konfiguratsiya** bilan RFQ yuborish kerak.",
    "importInfo": "Local stock bo‘lmasa, import qilinadi. RFQda model/catalog raqami, konfiguratsiya, ishlab chiqarilgan mamlakat, HS code, eksport qadoqlashi, kafolat, sertifikatlar va Incoterms alohida so‘raladi.",
    "delivery": "Transport narxi o‘lcham, og‘irlik, qadoqlash, kelib chiqish mamlakati va maxsus tashish talablariga bog‘liq. **EXW/FCA/DAP/DDP** shartlari quote'da aniq ko‘rsatilishi kerak.",
    "service": "- O‘zbekistonda authorized service bormi?\n- Kafolatni kim bajaradi?\n- Preventive maintenance davriyligi qanday?\n- Kalibrlash/verification talab qilinadimi?\n- Servis muhandisi kelish muddati qancha?\n\n**Status:** aynan `Integrated DNA Technologies (IDT) gRNA dizayn + Cas9 RNP` uchun O‘zbekistondagi servis holati yozma tasdiqlanishi kerak.",
    "spares": "Xarid bilan birga modelga mos **wear parts, service kit, sensor/probe/filter/tubing va boshqa sarf qismlar** ro‘yxati, narxi va lead time'i olinadi.",
    "tco": "**TCO =** xarid + import/bojxona/QQS + transport + o‘rnatish + kalibrlash + servis + ehtiyot qismlar + sarf materiallari + elektr/suv/gaz + dasturiy litsenziyalar + operator o‘qitish.\n\n**Hozirgi TCO:** RFQ va yillik foydalanish hajmisiz yakuniy hisoblanmagan.",
    "redFlags": "",
    "finalStatus": "**Narx:** $3,000–$25,000\n**O‘zbekiston:** aynan model bo‘yicha RFQ kerak\n**Import:** local stockga qarab\n**Yetkazib berish:** konfiguratsiyaga bog‘liq\n**Servis:** yozma tasdiq kerak\n**Ehtiyot qismlar:** alohida BOM/quote kerak\n**TCO:** RFQdan keyin hisoblanadi\n\n---"
  },
    "93": {
    "number": 93,
    "title": "Elektr impulsi generatori (Electroporator)",
    "searchName": "Elektr impulsi generatori (Electroporator)",
    "model": "Lonza 4D-Nucleofector X Unit",
    "sourceKind": "purchase",
    "price": "$1,000–$8,000",
    "priceEvidence": "",
    "source": "",
    "priceStatus": "",
    "whereToBuy": "1. Ishlab chiqaruvchining rasmiy savdo kanali.\n2. Authorized distributor/integrator.\n3. O‘zbekistondagi laboratoriya uskunalari yetkazib beruvchisi.\n4. Used/refurbished — faqat texnik tekshiruv, servis tarixi va calibration hujjati bilan.",
    "purchaseRule": "",
    "availabilityUz": "Aynan `Lonza 4D-Nucleofector X Unit` uchun tayyor local stock holati ushbu bosqichda qat'iy tasdiqlanmagan. Mahalliy distributor/integratorga **model + konfiguratsiya** bilan RFQ yuborish kerak.",
    "importInfo": "Local stock bo‘lmasa, import qilinadi. RFQda model/catalog raqami, konfiguratsiya, ishlab chiqarilgan mamlakat, HS code, eksport qadoqlashi, kafolat, sertifikatlar va Incoterms alohida so‘raladi.",
    "delivery": "Transport narxi o‘lcham, og‘irlik, qadoqlash, kelib chiqish mamlakati va maxsus tashish talablariga bog‘liq. **EXW/FCA/DAP/DDP** shartlari quote'da aniq ko‘rsatilishi kerak.",
    "service": "- O‘zbekistonda authorized service bormi?\n- Kafolatni kim bajaradi?\n- Preventive maintenance davriyligi qanday?\n- Kalibrlash/verification talab qilinadimi?\n- Servis muhandisi kelish muddati qancha?\n\n**Status:** aynan `Lonza 4D-Nucleofector X Unit` uchun O‘zbekistondagi servis holati yozma tasdiqlanishi kerak.",
    "spares": "Xarid bilan birga modelga mos **wear parts, service kit, sensor/probe/filter/tubing va boshqa sarf qismlar** ro‘yxati, narxi va lead time'i olinadi.",
    "tco": "**TCO =** xarid + import/bojxona/QQS + transport + o‘rnatish + kalibrlash + servis + ehtiyot qismlar + sarf materiallari + elektr/suv/gaz + dasturiy litsenziyalar + operator o‘qitish.\n\n**Hozirgi TCO:** RFQ va yillik foydalanish hajmisiz yakuniy hisoblanmagan.",
    "redFlags": "",
    "finalStatus": "**Narx:** $1,000–$8,000\n**O‘zbekiston:** aynan model bo‘yicha RFQ kerak\n**Import:** local stockga qarab\n**Yetkazib berish:** konfiguratsiyaga bog‘liq\n**Servis:** yozma tasdiq kerak\n**Ehtiyot qismlar:** alohida BOM/quote kerak\n**TCO:** RFQdan keyin hisoblanadi\n\n---"
  },
    "94": {
    "number": 94,
    "title": "Hujayra sanaygich (automated)",
    "searchName": "Hujayra sanaygich (automated)",
    "model": "Bio-Rad TC20 Automated Cell Counter",
    "sourceKind": "purchase",
    "price": "$2,000–$20,000",
    "priceEvidence": "",
    "source": "",
    "priceStatus": "",
    "whereToBuy": "1. Ishlab chiqaruvchining rasmiy savdo kanali.\n2. Authorized distributor/integrator.\n3. O‘zbekistondagi laboratoriya uskunalari yetkazib beruvchisi.\n4. Used/refurbished — faqat texnik tekshiruv, servis tarixi va calibration hujjati bilan.",
    "purchaseRule": "",
    "availabilityUz": "Aynan `Bio-Rad TC20 Automated Cell Counter` uchun tayyor local stock holati ushbu bosqichda qat'iy tasdiqlanmagan. Mahalliy distributor/integratorga **model + konfiguratsiya** bilan RFQ yuborish kerak.",
    "importInfo": "Local stock bo‘lmasa, import qilinadi. RFQda model/catalog raqami, konfiguratsiya, ishlab chiqarilgan mamlakat, HS code, eksport qadoqlashi, kafolat, sertifikatlar va Incoterms alohida so‘raladi.",
    "delivery": "Transport narxi o‘lcham, og‘irlik, qadoqlash, kelib chiqish mamlakati va maxsus tashish talablariga bog‘liq. **EXW/FCA/DAP/DDP** shartlari quote'da aniq ko‘rsatilishi kerak.",
    "service": "- O‘zbekistonda authorized service bormi?\n- Kafolatni kim bajaradi?\n- Preventive maintenance davriyligi qanday?\n- Kalibrlash/verification talab qilinadimi?\n- Servis muhandisi kelish muddati qancha?\n\n**Status:** aynan `Bio-Rad TC20 Automated Cell Counter` uchun O‘zbekistondagi servis holati yozma tasdiqlanishi kerak.",
    "spares": "Xarid bilan birga modelga mos **wear parts, service kit, sensor/probe/filter/tubing va boshqa sarf qismlar** ro‘yxati, narxi va lead time'i olinadi.",
    "tco": "**TCO =** xarid + import/bojxona/QQS + transport + o‘rnatish + kalibrlash + servis + ehtiyot qismlar + sarf materiallari + elektr/suv/gaz + dasturiy litsenziyalar + operator o‘qitish.\n\n**Hozirgi TCO:** RFQ va yillik foydalanish hajmisiz yakuniy hisoblanmagan.",
    "redFlags": "",
    "finalStatus": "**Narx:** $2,000–$20,000\n**O‘zbekiston:** aynan model bo‘yicha RFQ kerak\n**Import:** local stockga qarab\n**Yetkazib berish:** konfiguratsiyaga bog‘liq\n**Servis:** yozma tasdiq kerak\n**Ehtiyot qismlar:** alohida BOM/quote kerak\n**TCO:** RFQdan keyin hisoblanadi\n\n---"
  },
    "95": {
    "number": 95,
    "title": "Xromatografik kolonka sistema (Ion exchange)",
    "searchName": "Xromatografik kolonka sistema (Ion exchange)",
    "model": "Bio-Rad NGC Chromatography System",
    "sourceKind": "purchase",
    "price": "$1,000–$10,000",
    "priceEvidence": "",
    "source": "",
    "priceStatus": "",
    "whereToBuy": "1. Ishlab chiqaruvchining rasmiy savdo kanali.\n2. Authorized distributor/integrator.\n3. O‘zbekistondagi laboratoriya uskunalari yetkazib beruvchisi.\n4. Used/refurbished — faqat texnik tekshiruv, servis tarixi va calibration hujjati bilan.",
    "purchaseRule": "",
    "availabilityUz": "Aynan `Bio-Rad NGC Chromatography System` uchun tayyor local stock holati ushbu bosqichda qat'iy tasdiqlanmagan. Mahalliy distributor/integratorga **model + konfiguratsiya** bilan RFQ yuborish kerak.",
    "importInfo": "Local stock bo‘lmasa, import qilinadi. RFQda model/catalog raqami, konfiguratsiya, ishlab chiqarilgan mamlakat, HS code, eksport qadoqlashi, kafolat, sertifikatlar va Incoterms alohida so‘raladi.",
    "delivery": "Transport narxi o‘lcham, og‘irlik, qadoqlash, kelib chiqish mamlakati va maxsus tashish talablariga bog‘liq. **EXW/FCA/DAP/DDP** shartlari quote'da aniq ko‘rsatilishi kerak.",
    "service": "- O‘zbekistonda authorized service bormi?\n- Kafolatni kim bajaradi?\n- Preventive maintenance davriyligi qanday?\n- Kalibrlash/verification talab qilinadimi?\n- Servis muhandisi kelish muddati qancha?\n\n**Status:** aynan `Bio-Rad NGC Chromatography System` uchun O‘zbekistondagi servis holati yozma tasdiqlanishi kerak.",
    "spares": "Xarid bilan birga modelga mos **wear parts, service kit, sensor/probe/filter/tubing va boshqa sarf qismlar** ro‘yxati, narxi va lead time'i olinadi.",
    "tco": "**TCO =** xarid + import/bojxona/QQS + transport + o‘rnatish + kalibrlash + servis + ehtiyot qismlar + sarf materiallari + elektr/suv/gaz + dasturiy litsenziyalar + operator o‘qitish.\n\n**Hozirgi TCO:** RFQ va yillik foydalanish hajmisiz yakuniy hisoblanmagan.",
    "redFlags": "",
    "finalStatus": "**Narx:** $1,000–$10,000\n**O‘zbekiston:** aynan model bo‘yicha RFQ kerak\n**Import:** local stockga qarab\n**Yetkazib berish:** konfiguratsiyaga bog‘liq\n**Servis:** yozma tasdiq kerak\n**Ehtiyot qismlar:** alohida BOM/quote kerak\n**TCO:** RFQdan keyin hisoblanadi\n\n---"
  },
    "96": {
    "number": 96,
    "title": "Avtomatik gradient mikser",
    "searchName": "Avtomatik gradient mikser",
    "model": "Gradient Master (BioComp Instruments)",
    "sourceKind": "purchase",
    "price": "$2,000–$15,000",
    "priceEvidence": "",
    "source": "",
    "priceStatus": "",
    "whereToBuy": "1. Ishlab chiqaruvchining rasmiy savdo kanali.\n2. Authorized distributor/integrator.\n3. O‘zbekistondagi laboratoriya uskunalari yetkazib beruvchisi.\n4. Used/refurbished — faqat texnik tekshiruv, servis tarixi va calibration hujjati bilan.",
    "purchaseRule": "",
    "availabilityUz": "Aynan `Gradient Master (BioComp Instruments)` uchun tayyor local stock holati ushbu bosqichda qat'iy tasdiqlanmagan. Mahalliy distributor/integratorga **model + konfiguratsiya** bilan RFQ yuborish kerak.",
    "importInfo": "Local stock bo‘lmasa, import qilinadi. RFQda model/catalog raqami, konfiguratsiya, ishlab chiqarilgan mamlakat, HS code, eksport qadoqlashi, kafolat, sertifikatlar va Incoterms alohida so‘raladi.",
    "delivery": "Transport narxi o‘lcham, og‘irlik, qadoqlash, kelib chiqish mamlakati va maxsus tashish talablariga bog‘liq. **EXW/FCA/DAP/DDP** shartlari quote'da aniq ko‘rsatilishi kerak.",
    "service": "- O‘zbekistonda authorized service bormi?\n- Kafolatni kim bajaradi?\n- Preventive maintenance davriyligi qanday?\n- Kalibrlash/verification talab qilinadimi?\n- Servis muhandisi kelish muddati qancha?\n\n**Status:** aynan `Gradient Master (BioComp Instruments)` uchun O‘zbekistondagi servis holati yozma tasdiqlanishi kerak.",
    "spares": "Xarid bilan birga modelga mos **wear parts, service kit, sensor/probe/filter/tubing va boshqa sarf qismlar** ro‘yxati, narxi va lead time'i olinadi.",
    "tco": "**TCO =** xarid + import/bojxona/QQS + transport + o‘rnatish + kalibrlash + servis + ehtiyot qismlar + sarf materiallari + elektr/suv/gaz + dasturiy litsenziyalar + operator o‘qitish.\n\n**Hozirgi TCO:** RFQ va yillik foydalanish hajmisiz yakuniy hisoblanmagan.",
    "redFlags": "",
    "finalStatus": "**Narx:** $2,000–$15,000\n**O‘zbekiston:** aynan model bo‘yicha RFQ kerak\n**Import:** local stockga qarab\n**Yetkazib berish:** konfiguratsiyaga bog‘liq\n**Servis:** yozma tasdiq kerak\n**Ehtiyot qismlar:** alohida BOM/quote kerak\n**TCO:** RFQdan keyin hisoblanadi\n\n---"
  },
    "97": {
    "number": 97,
    "title": "Preparativ ultrasentrifuga",
    "searchName": "Preparativ ultrasentrifuga",
    "model": "Beckman Coulter Optima XPN-90",
    "sourceKind": "purchase",
    "price": "$5,000–$50,000",
    "priceEvidence": "",
    "source": "",
    "priceStatus": "",
    "whereToBuy": "1. Ishlab chiqaruvchining rasmiy savdo kanali.\n2. Authorized distributor/integrator.\n3. O‘zbekistondagi laboratoriya uskunalari yetkazib beruvchisi.\n4. Used/refurbished — faqat texnik tekshiruv, servis tarixi va calibration hujjati bilan.",
    "purchaseRule": "",
    "availabilityUz": "Aynan `Beckman Coulter Optima XPN-90` uchun tayyor local stock holati ushbu bosqichda qat'iy tasdiqlanmagan. Mahalliy distributor/integratorga **model + konfiguratsiya** bilan RFQ yuborish kerak.",
    "importInfo": "Local stock bo‘lmasa, import qilinadi. RFQda model/catalog raqami, konfiguratsiya, ishlab chiqarilgan mamlakat, HS code, eksport qadoqlashi, kafolat, sertifikatlar va Incoterms alohida so‘raladi.",
    "delivery": "Transport narxi o‘lcham, og‘irlik, qadoqlash, kelib chiqish mamlakati va maxsus tashish talablariga bog‘liq. **EXW/FCA/DAP/DDP** shartlari quote'da aniq ko‘rsatilishi kerak.",
    "service": "- O‘zbekistonda authorized service bormi?\n- Kafolatni kim bajaradi?\n- Preventive maintenance davriyligi qanday?\n- Kalibrlash/verification talab qilinadimi?\n- Servis muhandisi kelish muddati qancha?\n\n**Status:** aynan `Beckman Coulter Optima XPN-90` uchun O‘zbekistondagi servis holati yozma tasdiqlanishi kerak.",
    "spares": "Xarid bilan birga modelga mos **wear parts, service kit, sensor/probe/filter/tubing va boshqa sarf qismlar** ro‘yxati, narxi va lead time'i olinadi.",
    "tco": "**TCO =** xarid + import/bojxona/QQS + transport + o‘rnatish + kalibrlash + servis + ehtiyot qismlar + sarf materiallari + elektr/suv/gaz + dasturiy litsenziyalar + operator o‘qitish.\n\n**Hozirgi TCO:** RFQ va yillik foydalanish hajmisiz yakuniy hisoblanmagan.",
    "redFlags": "",
    "finalStatus": "**Narx:** $5,000–$50,000\n**O‘zbekiston:** aynan model bo‘yicha RFQ kerak\n**Import:** local stockga qarab\n**Yetkazib berish:** konfiguratsiyaga bog‘liq\n**Servis:** yozma tasdiq kerak\n**Ehtiyot qismlar:** alohida BOM/quote kerak\n**TCO:** RFQdan keyin hisoblanadi\n\n---"
  },
    "98": {
    "number": 98,
    "title": "Bioinformatik ish stantsiyasi",
    "searchName": "Bioinformatik ish stantsiyasi",
    "model": "Lenovo ThinkStation P620 + CLC Genomics Workbench",
    "sourceKind": "purchase",
    "price": "$2,000–$20,000",
    "priceEvidence": "",
    "source": "",
    "priceStatus": "",
    "whereToBuy": "1. Ishlab chiqaruvchining rasmiy savdo kanali.\n2. Authorized distributor/integrator.\n3. O‘zbekistondagi laboratoriya uskunalari yetkazib beruvchisi.\n4. Used/refurbished — faqat texnik tekshiruv, servis tarixi va calibration hujjati bilan.",
    "purchaseRule": "",
    "availabilityUz": "Aynan `Lenovo ThinkStation P620 + CLC Genomics Workbench` uchun tayyor local stock holati ushbu bosqichda qat'iy tasdiqlanmagan. Mahalliy distributor/integratorga **model + konfiguratsiya** bilan RFQ yuborish kerak.",
    "importInfo": "Local stock bo‘lmasa, import qilinadi. RFQda model/catalog raqami, konfiguratsiya, ishlab chiqarilgan mamlakat, HS code, eksport qadoqlashi, kafolat, sertifikatlar va Incoterms alohida so‘raladi.",
    "delivery": "Transport narxi o‘lcham, og‘irlik, qadoqlash, kelib chiqish mamlakati va maxsus tashish talablariga bog‘liq. **EXW/FCA/DAP/DDP** shartlari quote'da aniq ko‘rsatilishi kerak.",
    "service": "- O‘zbekistonda authorized service bormi?\n- Kafolatni kim bajaradi?\n- Preventive maintenance davriyligi qanday?\n- Kalibrlash/verification talab qilinadimi?\n- Servis muhandisi kelish muddati qancha?\n\n**Status:** aynan `Lenovo ThinkStation P620 + CLC Genomics Workbench` uchun O‘zbekistondagi servis holati yozma tasdiqlanishi kerak.",
    "spares": "Xarid bilan birga modelga mos **wear parts, service kit, sensor/probe/filter/tubing va boshqa sarf qismlar** ro‘yxati, narxi va lead time'i olinadi.",
    "tco": "**TCO =** xarid + import/bojxona/QQS + transport + o‘rnatish + kalibrlash + servis + ehtiyot qismlar + sarf materiallari + elektr/suv/gaz + dasturiy litsenziyalar + operator o‘qitish.\n\n**Hozirgi TCO:** RFQ va yillik foydalanish hajmisiz yakuniy hisoblanmagan.",
    "redFlags": "",
    "finalStatus": "**Narx:** $2,000–$20,000\n**O‘zbekiston:** aynan model bo‘yicha RFQ kerak\n**Import:** local stockga qarab\n**Yetkazib berish:** konfiguratsiyaga bog‘liq\n**Servis:** yozma tasdiq kerak\n**Ehtiyot qismlar:** alohida BOM/quote kerak\n**TCO:** RFQdan keyin hisoblanadi\n\n---"
  },
    "99": {
    "number": 99,
    "title": "Human liver S9 fraction — biologik reagent",
    "searchName": "Human liver S9 fraction — biologik reagent",
    "model": "XenoTech Human Liver S9 Kit",
    "sourceKind": "purchase",
    "price": "$1,000–$10,000",
    "priceEvidence": "",
    "source": "",
    "priceStatus": "",
    "whereToBuy": "1. Ishlab chiqaruvchining rasmiy savdo kanali.\n2. Authorized distributor/integrator.\n3. O‘zbekistondagi laboratoriya uskunalari yetkazib beruvchisi.\n4. Used/refurbished — faqat texnik tekshiruv, servis tarixi va calibration hujjati bilan.",
    "purchaseRule": "",
    "availabilityUz": "Aynan `XenoTech Human Liver S9 Kit` uchun tayyor local stock holati ushbu bosqichda qat'iy tasdiqlanmagan. Mahalliy distributor/integratorga **model + konfiguratsiya** bilan RFQ yuborish kerak.",
    "importInfo": "Local stock bo‘lmasa, import qilinadi. RFQda model/catalog raqami, konfiguratsiya, ishlab chiqarilgan mamlakat, HS code, eksport qadoqlashi, kafolat, sertifikatlar va Incoterms alohida so‘raladi.",
    "delivery": "Transport narxi o‘lcham, og‘irlik, qadoqlash, kelib chiqish mamlakati va maxsus tashish talablariga bog‘liq. **EXW/FCA/DAP/DDP** shartlari quote'da aniq ko‘rsatilishi kerak.",
    "service": "- O‘zbekistonda authorized service bormi?\n- Kafolatni kim bajaradi?\n- Preventive maintenance davriyligi qanday?\n- Kalibrlash/verification talab qilinadimi?\n- Servis muhandisi kelish muddati qancha?\n\n**Status:** aynan `XenoTech Human Liver S9 Kit` uchun O‘zbekistondagi servis holati yozma tasdiqlanishi kerak.",
    "spares": "Xarid bilan birga modelga mos **wear parts, service kit, sensor/probe/filter/tubing va boshqa sarf qismlar** ro‘yxati, narxi va lead time'i olinadi.",
    "tco": "**TCO =** xarid + import/bojxona/QQS + transport + o‘rnatish + kalibrlash + servis + ehtiyot qismlar + sarf materiallari + elektr/suv/gaz + dasturiy litsenziyalar + operator o‘qitish.\n\n**Hozirgi TCO:** RFQ va yillik foydalanish hajmisiz yakuniy hisoblanmagan.",
    "redFlags": "",
    "finalStatus": "**Narx:** $1,000–$10,000\n**O‘zbekiston:** aynan model bo‘yicha RFQ kerak\n**Import:** local stockga qarab\n**Yetkazib berish:** konfiguratsiyaga bog‘liq\n**Servis:** yozma tasdiq kerak\n**Ehtiyot qismlar:** alohida BOM/quote kerak\n**TCO:** RFQdan keyin hisoblanadi\n\n---"
  },
    "100": {
    "number": 100,
    "title": "Biofilm o'rganish reaktori",
    "searchName": "Biofilm o'rganish reaktori",
    "model": "BioSurface Technologies CDC Biofilm Reactor",
    "sourceKind": "purchase",
    "price": "$3,000–$30,000",
    "priceEvidence": "",
    "source": "",
    "priceStatus": "",
    "whereToBuy": "1. Ishlab chiqaruvchining rasmiy savdo kanali.\n2. Authorized distributor/integrator.\n3. O‘zbekistondagi laboratoriya uskunalari yetkazib beruvchisi.\n4. Used/refurbished — faqat texnik tekshiruv, servis tarixi va calibration hujjati bilan.",
    "purchaseRule": "",
    "availabilityUz": "Aynan `BioSurface Technologies CDC Biofilm Reactor` uchun tayyor local stock holati ushbu bosqichda qat'iy tasdiqlanmagan. Mahalliy distributor/integratorga **model + konfiguratsiya** bilan RFQ yuborish kerak.",
    "importInfo": "Local stock bo‘lmasa, import qilinadi. RFQda model/catalog raqami, konfiguratsiya, ishlab chiqarilgan mamlakat, HS code, eksport qadoqlashi, kafolat, sertifikatlar va Incoterms alohida so‘raladi.",
    "delivery": "Transport narxi o‘lcham, og‘irlik, qadoqlash, kelib chiqish mamlakati va maxsus tashish talablariga bog‘liq. **EXW/FCA/DAP/DDP** shartlari quote'da aniq ko‘rsatilishi kerak.",
    "service": "- O‘zbekistonda authorized service bormi?\n- Kafolatni kim bajaradi?\n- Preventive maintenance davriyligi qanday?\n- Kalibrlash/verification talab qilinadimi?\n- Servis muhandisi kelish muddati qancha?\n\n**Status:** aynan `BioSurface Technologies CDC Biofilm Reactor` uchun O‘zbekistondagi servis holati yozma tasdiqlanishi kerak.",
    "spares": "Xarid bilan birga modelga mos **wear parts, service kit, sensor/probe/filter/tubing va boshqa sarf qismlar** ro‘yxati, narxi va lead time'i olinadi.",
    "tco": "**TCO =** xarid + import/bojxona/QQS + transport + o‘rnatish + kalibrlash + servis + ehtiyot qismlar + sarf materiallari + elektr/suv/gaz + dasturiy litsenziyalar + operator o‘qitish.\n\n**Hozirgi TCO:** RFQ va yillik foydalanish hajmisiz yakuniy hisoblanmagan.",
    "redFlags": "",
    "finalStatus": "**Narx:** $3,000–$30,000\n**O‘zbekiston:** aynan model bo‘yicha RFQ kerak\n**Import:** local stockga qarab\n**Yetkazib berish:** konfiguratsiyaga bog‘liq\n**Servis:** yozma tasdiq kerak\n**Ehtiyot qismlar:** alohida BOM/quote kerak\n**TCO:** RFQdan keyin hisoblanadi\n\n---\n\n# 76–100 BLOK YAKUNI\n\n**Tayyor:** 100 / 100\n\n## II-BOSQICH YAKUNLANDI\n\n- ✅ 1–25\n- ✅ 26–50\n- ✅ 51–75\n- ✅ 76–100\n\n**Keyingi ish:** 4 ta blokni bitta `BIOTECH_100_XARID_BAZASI_MASTER.md` fayliga birlashtirish va keyin kerak bo‘lsa **real RFQ narxlari + O‘zbekiston distributorlarining aniq kontaktlari + import/logistika + TCO** bilan ikkinchi tekshiruvdan o‘tkazish."
  }
};

export default purchaseBlock4;
